package io.dataroots.savingstreak.loyalty;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One anniversary that has been paid: which deposit paid it, which of that deposit's anniversaries
 * it was, the moment that anniversary fell, the whole euros the bonus was worked out from, and the
 * points it credited.
 *
 * <p>What makes the sweep idempotent, and by construction rather than by care. A row per deposit
 * per anniversary, unique over the pair, means a second pass over the same rows cannot pay twice
 * even if the rule underneath it were rewritten — the same way an expired batch of points carries
 * the moment it went so that the expiry sweep can be run whenever a trainer likes.
 *
 * <p>The uniqueness is not declared here, and that is not an oversight. The schema is generated
 * from the entity model ({@code ddl-auto=update}) against SQLite, whose dialect writes a composite
 * unique clause nowhere: declared as {@code @UniqueConstraint} — or as a {@code @Index} marked
 * unique, which Hibernate turns into one — the table is created without it and the only statement
 * that reaches the database is an {@code alter table ... drop constraint} that does nothing. The
 * generated DDL in a DEBUG start-up log says so out loud. So {@link LoyaltyOnStartUp} creates the
 * index itself, in a statement SQLite does accept, before the application serves anything — and the
 * guarantee is then actually in the file rather than only in an annotation.
 *
 * <p>Deriving the same fact from the points ledger was rejected: it would need Points to say out
 * loud which anniversaries it has seen, which is precisely the kind of question that module refuses
 * to answer. A counter on the deposit was rejected because it discards everything below.
 *
 * <p>Because this is also the audit trail. The euros are written down because they are otherwise
 * gone: the deposit's remaining amount moves on the next time its holder withdraws anything, and
 * then nothing anywhere says what a past bonus was a tenth of. A reviewer checking the arithmetic
 * by hand a year later reads it here.
 *
 * <p>Never rewritten. What an anniversary paid is what happened, and a later withdrawal forfeits
 * only the anniversaries the money did not reach.
 *
 * <p>Package-private, like the repository: what the Loyalty module records, and how, is nobody
 * else's business — no test asserts on it, and what a deposit has been paid is read back through
 * the points ledger.
 */
@Entity
class LoyaltyBonusPaid {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The deposit whose money stayed put, which is what the clock belongs to. */
    private long depositId;

    /**
     * Whose points these were.
     *
     * <p>Written down beside the deposit rather than looked back up through it, because it is what
     * the credit was made against and a row that records a payment records who was paid.
     */
    private long customerId;

    /**
     * Which anniversary this was — one for the first, two for the second, and so on.
     *
     * <p>The ordinal rather than only the moment. Half of the unique constraint is this column, and
     * an ordinal is the half a sweep can ask about without recomputing a date: "has this deposit
     * been paid its third?" is the question, and the moment the third fell is an answer to a
     * different one.
     */
    private int anniversaryOrdinal;

    /**
     * The moment the anniversary fell, which is what the batch of points was dated at.
     *
     * <p>The anniversary rather than the moment the sweep noticed, for the reason an expired batch
     * gives: the money had stayed put for a year whether or not anything was running at half past
     * three that morning, and dating it by the run would make the same anniversary report a
     * different moment depending on when the job next ran.
     */
    private Instant anniversaryAt;

    /**
     * The whole euros still in the deposit when the anniversary was judged, which the points below
     * are a tenth of.
     *
     * <p>The only place this figure survives. It is the audit trail: the deposit's remaining amount
     * is a live figure and the next withdrawal moves it, so a reviewer redoing the arithmetic has
     * nothing else to redo it from.
     */
    private long wholeEurosItWasWorkedOutFrom;

    /** What the anniversary paid, and what was credited to the customer's pot under it. */
    private long points;

    protected LoyaltyBonusPaid() {
        // for JPA
    }

    private LoyaltyBonusPaid(long depositId, long customerId, int anniversaryOrdinal,
                             Instant anniversaryAt, long wholeEurosItWasWorkedOutFrom, long points) {
        this.depositId = depositId;
        this.customerId = customerId;
        this.anniversaryOrdinal = anniversaryOrdinal;
        this.anniversaryAt = anniversaryAt;
        this.wholeEurosItWasWorkedOutFrom = wholeEurosItWasWorkedOutFrom;
        this.points = points;
    }

    /**
     * An anniversary that has just been paid, with everything it was decided from.
     *
     * <p>Only ever written for an anniversary that paid something. An anniversary worth nothing — a
     * deposit drawn below ten euros, or emptied — is not an event and leaves no row behind, the same
     * way a streak uplift of nothing leaves no batch: money never comes back into a deposit, so
     * nothing worth nothing today can be worth something tomorrow, and a table of zeroes would only
     * make "what has this deposit been paid" a figure nobody can add up.
     */
    static LoyaltyBonusPaid of(long depositId, long customerId, int anniversaryOrdinal,
                               Instant anniversaryAt, long wholeEuros, long points) {
        return new LoyaltyBonusPaid(
                depositId, customerId, anniversaryOrdinal, anniversaryAt, wholeEuros, points);
    }

    Long getId() {
        return id;
    }

    long getDepositId() {
        return depositId;
    }

    int getAnniversaryOrdinal() {
        return anniversaryOrdinal;
    }
}
