package io.dataroots.savingstreak.challenges;

import java.time.Instant;
import java.time.LocalDate;

import io.dataroots.savingstreak.streaks.SavingsWeek;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * A season: a named window the bank runs a set of challenges in, with a day it opens on and a day it
 * closes on.
 *
 * <p><strong>Why a season is a row and not a flag on a challenge.</strong> Several challenges belong
 * to one campaign — that is what makes it a campaign rather than a challenge with an end date — and
 * they all have to open and close together. Two definitions each carrying their own pair of dates
 * could drift apart by a day and produce a "season" half of which was still joinable, which is not a
 * state anybody could explain to a customer. So the window is written down once and the definitions
 * name it, exactly as they name a {@link ChallengeKind}.
 *
 * <p><strong>The window is two dates and the clock reads instants, and this is where the two are
 * reconciled.</strong> A campaign is a thing the bank announces on a poster — "until the 31st of
 * March" — so it is stated in days, and the day it is is a question about where somebody is
 * standing. The zone is {@link SavingsWeek#ZONE_WEEKS_ARE_COUNTED_IN}, borrowed rather than written
 * out again, because it is the zone this application already counts every calendar thing in: the
 * Monday a savings week starts on, the day a bill is due, the anniversary a batch of points expires
 * on, and the whole days the development clock moves through. A season counted in any other zone
 * would close on a different day from the one a trainer winding the clock would land on.
 *
 * <p><strong>Both ends are inclusive.</strong> It opens at midnight at the start of {@code opensOn}
 * and it is still open all through {@code closesOn}; it has closed once the day has moved past that
 * date. "Closes on the 31st" meaning "shut all day on the 31st" would be a poster that lied by a
 * day, and a customer who read the date on the card and came back on the last afternoon would be
 * refused for no reason they could see.
 *
 * <p><strong>A single-day season is legal and a backwards one is not.</strong> A window whose close
 * is before its open is not a short season, it is a season nobody can ever join, and a row that can
 * only be a mistake is refused where it is written rather than puzzled over later.
 *
 * <p>Package-private, like the definitions and the enrolments beside it. {@link ASeason} is what
 * leaves the module.
 */
@Entity
class Campaign {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * What a definition names this season by, and what the seed matches on when it decides whether
     * this row is already there.
     *
     * <p>Unique, for the reason a challenge's code is: it is the name the window is looked up by,
     * and two rows sharing one would be two answers to the question of whether a challenge is open.
     */
    @Column(nullable = false, unique = true)
    private String code;

    /** What the banner is headed with while the season is running. */
    private String title;

    /** The first day it can be joined on, inclusive. */
    private LocalDate opensOn;

    /** The last day it can be joined on, inclusive — see this class's own note. */
    private LocalDate closesOn;

    protected Campaign() {
        // for JPA
    }

    private Campaign(String code, String title, LocalDate opensOn, LocalDate closesOn) {
        this.code = code;
        this.title = title;
        this.opensOn = opensOn;
        this.closesOn = closesOn;
    }

    /**
     * A season the bank is running, from the day it opens to the day it closes, both inclusive.
     *
     * @throws IllegalArgumentException if the window is backwards, which is a season nobody could
     *                                  ever join and so a row that can only be a mistake
     */
    static Campaign running(String code, String title, LocalDate opensOn, LocalDate closesOn) {
        if (closesOn.isBefore(opensOn)) {
            throw new IllegalArgumentException(code + " closes on " + closesOn + ", which is before "
                    + "it opens on " + opensOn + ". A season whose window runs backwards is one "
                    + "nobody could ever join.");
        }
        return new Campaign(code, title, opensOn, closesOn);
    }

    String code() {
        return code;
    }

    String title() {
        return title;
    }

    LocalDate opensOn() {
        return opensOn;
    }

    LocalDate closesOn() {
        return closesOn;
    }

    /** Whether the day this moment falls on has reached the first day of the window. */
    boolean hasOpenedBy(Instant moment) {
        return !theDayOf(moment).isBefore(opensOn);
    }

    /** Whether the day this moment falls on has gone past the last day of the window. */
    boolean hasClosedBy(Instant moment) {
        return theDayOf(moment).isAfter(closesOn);
    }

    /** Whether it can be joined at this moment, which is the only question enrolling asks. */
    boolean isOpenAt(Instant moment) {
        return hasOpenedBy(moment) && !hasClosedBy(moment);
    }

    /** This season as the rest of the application reads it, as of the moment it is asking about. */
    ASeason asRunning(Instant moment) {
        return new ASeason(code, title, opensOn, closesOn, isOpenAt(moment));
    }

    /**
     * Which day a moment is, where this application counts its days.
     *
     * <p>Converted rather than truncated, for the reason {@link SavingsWeek} gives about a week: a
     * deposit at 00:30 on the first of March in Brussels is 23:30 on the last of February in UTC,
     * and a season read off the clock's own reading would have opened a day late for anybody who
     * looked before one in the morning.
     */
    private static LocalDate theDayOf(Instant moment) {
        return LocalDate.ofInstant(moment, SavingsWeek.ZONE_WEEKS_ARE_COUNTED_IN);
    }
}
