package io.dataroots.savingstreak.challenges;

import java.math.BigDecimal;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One challenge the bank offers: what it is called, what it says to the customer, the question it
 * asks, the ladder it is climbed by, and whether it can be taken on again.
 *
 * <p><strong>A row rather than a constant, and that is the point.</strong> The rewards catalogue
 * next door is an enum because changing a price should be a release. A challenge is the opposite
 * case: the bank wants to add one, retune a threshold, change what a rung pays or run a January
 * season, and none of those is a change to how the application works. So this is a table, seeded by
 * {@link ChallengesOnStartUp}, and "configurable challenges" means rows. What the challenge
 * <em>means</em> is still code — that is {@link ChallengeKind}.
 *
 * <p><strong>The three rungs are six columns, not a table.</strong> Every challenge has exactly
 * bronze, silver and gold; a child table would be able to express two rungs, or four, or a gold
 * cheaper than its silver, and every one of those is a shape this module would then have to refuse
 * at run time. Six columns can only ever describe the shape that exists, and {@link #rungs()} is
 * where they become the ladder everything else reads.
 *
 * <p><strong>The kind's parameter is the bank's figure for the kinds that ask one.</strong>
 * {@code BALANCE_HELD} needs a floor — "at least EUR 1,000, for ninety days" — and a floor is a
 * number the bank tunes, so it belongs beside the thresholds rather than inside the enum. It is null
 * on every kind that asks no question of its own, which is the other four.
 *
 * <p><strong>The campaign is a code and not a relation</strong>, for the reason every identifier in
 * this application is: it is null on an evergreen challenge, which is always open, and a challenge
 * that belongs to a season is judged against that season's window rather than navigated to. The
 * window itself is a {@link Campaign} row, because several challenges share one and dates copied
 * onto each of them could drift into a season half of which was still joinable.
 *
 * <p>Package-private, like the repository that reads it. What this module records, and how, is
 * nobody else's business; {@link AChallengeAsItStands} is what leaves.
 */
@Entity
class ChallengeDefinition {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * What an enrolment names this challenge by, and what the seed matches on when it decides
     * whether this row is already there.
     *
     * <p>Unique, because the code is the name the API is addressed with and two rows sharing one
     * would be two answers to a request naming it. A single-column unique constraint is one SQLite
     * does accept from generated schema, which is why it is declared here rather than made into an
     * index by the start-up step the way this application's composite guarantees have to be.
     */
    @Column(nullable = false, unique = true)
    private String code;

    /** What the card is headed with. */
    private String title;

    /**
     * What the card says underneath: what the challenge asks for, in the words a customer decides on
     * rather than a restatement of the threshold.
     *
     * <p>Long enough to say the thing the arithmetic cannot, which for a saving challenge is that a
     * withdrawal costs them nothing here. A customer who believes using their savings will wipe out
     * their progress will not use their savings, and an application that makes people afraid of
     * their own money has failed at the thing it is for.
     */
    @Column(length = 1000)
    private String words;

    @Enumerated(EnumType.STRING)
    private ChallengeKind kind;

    /** The kind's own figure, where it has one, and null where it does not. */
    private BigDecimal kindParameter;

    private BigDecimal bronzeThreshold;

    private long bronzePoints;

    private BigDecimal silverThreshold;

    private long silverPoints;

    private BigDecimal goldThreshold;

    private long goldPoints;

    /**
     * Whether it can be taken on again once finished.
     *
     * <p>A property of the kind's family rather than of anybody's taste, and it is stored because
     * the bank may want a one-off run of a repeatable kind for a season. A flow kind can be repeated
     * because a fresh enrolment takes a fresh mark to measure from, so the second EUR 500 is a real
     * second EUR 500; a stock kind cannot, because the same thousand euros would otherwise be worth
     * a gold badge every time somebody re-enrolled.
     */
    private boolean repeatable;

    /** The season this belongs to, and null for an evergreen challenge, which is always open. */
    private String campaignCode;

    protected ChallengeDefinition() {
        // for JPA
    }

    private ChallengeDefinition(String code, String title, String words, ChallengeKind kind,
                                BigDecimal kindParameter, List<ChallengeRung> rungs,
                                boolean repeatable, String campaignCode) {
        this.code = code;
        this.title = title;
        this.words = words;
        this.kind = kind;
        this.kindParameter = kindParameter;
        this.bronzeThreshold = rungs.get(0).threshold();
        this.bronzePoints = rungs.get(0).points();
        this.silverThreshold = rungs.get(1).threshold();
        this.silverPoints = rungs.get(1).points();
        this.goldThreshold = rungs.get(2).threshold();
        this.goldPoints = rungs.get(2).points();
        this.repeatable = repeatable;
        this.campaignCode = campaignCode;
    }

    /**
     * A challenge as the seed describes it, with its ladder given cheapest first.
     *
     * <p>The ladder has to be three rungs in the order they are climbed, and saying so here rather
     * than trusting the caller is what makes the six columns above safe to fill positionally: a seed
     * that listed gold first would otherwise produce a challenge whose bronze is the hardest rung on
     * it, and nothing downstream could tell.
     */
    static ChallengeDefinition offering(String code, String title, String words, ChallengeKind kind,
                                        BigDecimal kindParameter, List<ChallengeRung> rungs,
                                        boolean repeatable, String campaignCode) {
        if (rungs.size() != Rung.values().length) {
            throw new IllegalArgumentException(code + " needs one rung for each of "
                    + List.of(Rung.values()) + " and was given " + rungs.size());
        }
        for (int step = 0; step < rungs.size(); step++) {
            if (rungs.get(step).rung() != Rung.values()[step]) {
                throw new IllegalArgumentException(code + " lists its rungs out of the order they "
                        + "are climbed: expected " + Rung.values()[step] + " at position " + step
                        + " and found " + rungs.get(step).rung());
            }
        }
        return new ChallengeDefinition(
                code, title, words, kind, kindParameter, rungs, repeatable, campaignCode);
    }

    String code() {
        return code;
    }

    String title() {
        return title;
    }

    String words() {
        return words;
    }

    ChallengeKind kind() {
        return kind;
    }

    /**
     * The kind's own figure, and null where the kind asks none — which is every kind but
     * {@code BALANCE_HELD}.
     *
     * <p>Read by the {@link HowAChallengeIsRead} for the kind and by nothing else, because what the
     * number means is the kind's business: a floor in euros to a balance held, nothing at all to new
     * saving. A reading that wants one and finds null is looking at a row that was seeded wrong, and
     * that is its own refusal to make rather than this row's.
     */
    BigDecimal kindParameter() {
        return kindParameter;
    }

    /**
     * The season this belongs to, and null on an evergreen challenge, which is always open.
     *
     * <p>A code rather than a relation, for the reason every identifier in this application is one:
     * a challenge that belongs to a season is judged against its window rather than navigated to.
     * A code naming a {@link Campaign} row that is not there is a definition seeded wrong, and it is
     * refused where enrolment is decided rather than silently read as evergreen — a challenge that
     * quietly lost its season would be one the bank thought it had closed.
     */
    String campaignCode() {
        return campaignCode;
    }

    boolean repeatable() {
        return repeatable;
    }

    /** The ladder, cheapest first, which is the order everything that reads it depends on. */
    List<ChallengeRung> rungs() {
        return List.of(
                new ChallengeRung(Rung.BRONZE, bronzeThreshold, bronzePoints),
                new ChallengeRung(Rung.SILVER, silverThreshold, silverPoints),
                new ChallengeRung(Rung.GOLD, goldThreshold, goldPoints));
    }
}
