package io.dataroots.savingstreak.challenges;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One customer taking on one challenge: when they joined, where the challenge stood for them at that
 * moment, and where the enrolment now stands.
 *
 * <p><strong>The mark it measures from is the only figure here, and it is the one that matters.</strong>
 * {@code measuringFrom} is the most the customer had ever saved at the instant they enrolled, read
 * from the deposit ledger and written down once. Everything the challenge reports afterwards is the
 * mark now less this, so a challenge counts the saving somebody did <em>since</em> they joined and
 * nothing their past already did — and money that only refills the gap a withdrawal left, which
 * raises no mark, moves it by nothing. The argument is in {@link TheReadingSinceYouEnrolled}; this
 * is where the number lives.
 *
 * <p><strong>Nothing about progress is stored.</strong> There is no counter here, no rung column and
 * no total, because the development clock winds time in both directions and a stored figure would
 * routinely find itself describing a week that is now in the future. The reading is worked out on
 * every read. The mark is not progress — it is a reading taken at a moment that has passed, which is
 * exactly the sort of thing that has to be recorded rather than recomputed.
 *
 * <p><strong>By customer, and the savings accounts are not mentioned.</strong> Points are one pot
 * per person and the high-water mark already spans every savings account somebody holds; an
 * enrolment keyed by account would contradict both, and would make "save EUR 500" satisfiable twice
 * by one customer with two accounts.
 *
 * <p><strong>Ended rather than removed.</strong> Leaving sets {@link EnrolmentState#ABANDONED} and
 * reaching the last rung sets {@link EnrolmentState#COMPLETED}; either way an {@code endedAt} is
 * written and the row stays, because the awards hanging off it point at it by identifier and have
 * to keep pointing at something, and because a customer leaving or finishing a challenge is a thing
 * that happened and nothing else records it. The moment is set once, the way a notification's
 * {@code readAt} is: a moment that could be overwritten would be a record of when it was last asked
 * about.
 *
 * <p>Package-private, like the repository. {@link AnEnrolment} is what leaves the module.
 */
@Entity
class ChallengeEnrolment {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long customerId;

    /**
     * The challenge by its code rather than by a relation to its row, the way every identifier in
     * this application is held. It is also what keeps an enrolment readable after a definition has
     * been retuned: the code is the name the customer joined under.
     */
    private String challengeCode;

    /**
     * Written as its name rather than as its position, so a row means the same thing after a value
     * is added to the enum, and so a reviewer reading the table with a SQLite client sees the state
     * rather than an ordinal to look up.
     */
    @Enumerated(EnumType.STRING)
    private EnrolmentState state;

    /** The most the customer had ever saved when they joined. See this class's own note. */
    private BigDecimal measuringFrom;

    private Instant enrolledAt;

    /** When it stopped being counted, and null while it still is. */
    private Instant endedAt;

    protected ChallengeEnrolment() {
        // for JPA
    }

    private ChallengeEnrolment(long customerId, String challengeCode, BigDecimal measuringFrom,
                               Instant enrolledAt) {
        this.customerId = customerId;
        this.challengeCode = challengeCode;
        this.state = EnrolmentState.ACTIVE;
        this.measuringFrom = measuringFrom;
        this.enrolledAt = enrolledAt;
        this.endedAt = null;
    }

    /**
     * A customer joining a challenge, with the mark already on it. The mark is not something that
     * arrives afterwards: an enrolment without one would be a moment in which the challenge had no
     * answer to what it was counting from, and the obvious repair — reading the mark on the next
     * request instead — would quietly make everything saved in between count.
     */
    static ChallengeEnrolment taking(long customerId, String challengeCode, BigDecimal measuringFrom,
                                     Instant enrolledAt) {
        return new ChallengeEnrolment(customerId, challengeCode, measuringFrom, enrolledAt);
    }

    /** The customer leaving it. Everything already awarded to them is somewhere else and is kept. */
    void abandon(Instant at) {
        this.state = EnrolmentState.ABANDONED;
        this.endedAt = at;
    }

    /**
     * The enrolment finished: its last rung has been awarded and there is nothing left to judge.
     *
     * <p>Set by the judging pass at the moment gold is written down, rather than worked out on
     * every read from whether three awards exist. The distinction matters for the same reason the
     * mark does: a challenge whose gold threshold the bank lowers next month must not quietly
     * finish enrolments that never reached the old one, and one whose threshold is raised must not
     * un-finish the people who did. Completion is something that happened at a moment, so it is
     * recorded at that moment.
     *
     * <p>It is also what makes a repeatable challenge repeatable. An enrolment that is no longer
     * live is no longer judged and no longer stands in the way of taking the same challenge on
     * again — which is the whole difference between finishing something and being stuck in it.
     */
    void complete(Instant at) {
        this.state = EnrolmentState.COMPLETED;
        this.endedAt = at;
    }

    /**
     * The season it belongs to closed while it was still running, so it lapses.
     *
     * <p>Set on the same pass that judges it for the last time, and after that judgement rather than
     * instead of it: the rungs the reading cleared by the close are awarded first and only then does
     * the enrolment end, because failing to finish a season costs a customer the prize and nothing
     * they had already won. Everything awarded points at this row by identifier and none of it is
     * touched here.
     *
     * <p>Apart from {@link #complete} although both end the enrolment at a moment, because the two
     * are different facts about the same customer: one of them reached gold and the other ran out of
     * time. A campaign close that quietly completed what it caught would tell somebody who got two
     * rungs in that they had finished.
     *
     * <p>Apart from {@link #abandon} too, and not merely for tidiness. Leaving is something the
     * customer did, and a card that reported "you left this" to somebody whose season had ended
     * under them would be blaming them for the calendar.
     */
    void lapse(Instant at) {
        this.state = EnrolmentState.EXPIRED;
        this.endedAt = at;
    }

    Long id() {
        return id;
    }

    /**
     * Whose enrolment this is.
     *
     * <p>Said out loud because a {@link HowAChallengeIsRead} is handed the enrolment and nothing
     * else about the person, and every reading there will ever be is about a customer: the mark, the
     * run of secured weeks, what is held in savings, the goals finished. Carrying the identifier
     * beside it in every signature would be carrying a thing the row already holds.
     */
    long customerId() {
        return customerId;
    }

    /**
     * When they joined, which is the other end of every window a reading measures over.
     *
     * <p>{@link AnEnrolment} carries it out of the module and this says it in here, for the kinds
     * that count days or weeks rather than differencing two marks.
     */
    Instant enrolledAt() {
        return enrolledAt;
    }

    String challengeCode() {
        return challengeCode;
    }

    EnrolmentState state() {
        return state;
    }

    BigDecimal measuringFrom() {
        return measuringFrom;
    }

    AnEnrolment asTaken() {
        return new AnEnrolment(id, challengeCode, state, measuringFrom, enrolledAt, endedAt);
    }
}
