package io.dataroots.savingstreak.challenges;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One rung, reached: whose it is, which enrolment reached it, which challenge and which rung, the
 * moment it happened, the reading that won it and the points it paid.
 *
 * <p><strong>An award is a fact, recorded and never recomputed.</strong> Everything else this module
 * reports is derived on every read — the reading, the next rung, what that rung still asks for — and
 * that is right, because those answer "where do I stand" and the answer changes as the money does.
 * This answers a different question: <em>what was I paid, and why</em>. Once written it is never
 * revoked, never re-priced and never deleted, whatever becomes of the balance afterwards. The bank
 * retuning a threshold next month changes what everybody's card asks for next and changes nothing
 * about what anybody has already been paid, which is only true because the reading and the points
 * are written down here rather than worked out again from a definition that has since moved.
 *
 * <p>It is the same line the deposit ledger already draws, and the same one a paid loyalty
 * anniversary draws: history is recorded, state is derived.
 *
 * <p><strong>A badge is an award.</strong> There is no second entity for the trophy case and no
 * separate notion of a badge, because a badge is not a different thing from having reached a rung —
 * it is what having reached one looks like on a screen. The trophy case is this table read newest
 * first.
 *
 * <p><strong>Keyed by the enrolment and not by customer-and-challenge</strong>, and that is what
 * makes a repeatable challenge work at all: a customer who has been round {@code SAVE_FIVE_HUNDRED}
 * twice has two enrolments, each measuring from its own mark, and each is entitled to its own
 * bronze. "Has this rung been awarded yet" is therefore a question about an enrolment, which is the
 * only scope in which it has one answer. The customer is written down beside it all the same,
 * because the trophy case is read by person and a row that records a payment records who was paid.
 *
 * <p><strong>The reading is the audit trail and is the only place it survives.</strong> A reading is
 * derived from a mark that keeps rising, so nothing anywhere else can say what it was on the day a
 * rung was cleared. A reviewer asking a year later why bronze was awarded reads the figure here and
 * compares it against the threshold the definition carried then.
 *
 * <p>Package-private, like everything this module stores. {@link AnAchievement} is what leaves.
 */
@Entity
class ChallengeAward {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Whose achievement this is, which is who the points went to and whose trophy case it is in. */
    private long customerId;

    /**
     * The enrolment that reached it, which is the scope "already awarded" is asked in.
     *
     * <p>An identifier rather than a relation, the way every identifier in this application is held.
     * It also means an award outlives whatever happens to its enrolment: leaving a challenge ends
     * the enrolment and touches nothing here, because quitting costs nobody anything they had
     * already earned.
     */
    private long enrolmentId;

    /**
     * The challenge by the code the customer took it on under, copied here rather than followed back
     * through the enrolment.
     *
     * <p>Written down because this row is a record of something that happened and a record that had
     * to be joined through two tables to say what it was about would be a record that stops meaning
     * anything the first time either of them is retuned.
     */
    private String challengeCode;

    /**
     * Written as its name rather than as its position, so a row means the same thing after a value
     * is added to the enum, and so a reviewer reading the table with a SQLite client sees the rung
     * rather than an ordinal to look up.
     */
    @Enumerated(EnumType.STRING)
    private Rung rung;

    /** When the rung was cleared, which is also the moment the points it paid were earned at. */
    private Instant awardedAt;

    /**
     * What the enrolment read at the moment this rung was cleared — euros of new saving for a {@link
     * ChallengeKind#NEW_SAVINGS} challenge, and whatever the kind counts in for the kinds that
     * follow it.
     *
     * <p>The reading rather than the threshold, deliberately: one large deposit clears three rungs
     * at once and all three are won by the same reading, which is the honest record of what
     * happened. It is also the figure that explains a badge to somebody reading it a year later.
     */
    private BigDecimal reading;

    /** What the rung paid, as the definition priced it at the moment it was reached. */
    private long points;

    protected ChallengeAward() {
        // for JPA
    }

    private ChallengeAward(long customerId, long enrolmentId, String challengeCode, Rung rung,
                           BigDecimal reading, long points, Instant awardedAt) {
        this.customerId = customerId;
        this.enrolmentId = enrolmentId;
        this.challengeCode = challengeCode;
        this.rung = rung;
        this.reading = reading;
        this.points = points;
        this.awardedAt = awardedAt;
    }

    /**
     * A rung just reached, with everything that decided it.
     *
     * <p>Everything arrives at once because an award is written once and never touched again: there
     * is no setter here and no moment at which one of these fields is not yet known. A row that
     * could be completed afterwards would be a row that could be corrected afterwards, and the one
     * thing this table promises is that nothing in it is.
     */
    static ChallengeAward won(long customerId, long enrolmentId, String challengeCode, Rung rung,
                              BigDecimal reading, long points, Instant awardedAt) {
        return new ChallengeAward(
                customerId, enrolmentId, challengeCode, rung, reading, points, awardedAt);
    }

    Long id() {
        return id;
    }

    long enrolmentId() {
        return enrolmentId;
    }

    String challengeCode() {
        return challengeCode;
    }

    /** What the enrolment read when this rung was cleared, which is the figure that is never redone. */
    BigDecimal reading() {
        return reading;
    }

    Rung rung() {
        return rung;
    }

    long points() {
        return points;
    }

    /** The award as the rest of the application reads it, with the challenge's title alongside. */
    AnAchievement asWon(String challengeTitle) {
        return new AnAchievement(
                id, challengeCode, challengeTitle, rung, awardedAt, reading, points);
    }
}
