package io.dataroots.savingstreak.challenges;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One of the customer's savings goals, seen standing at {@code COMPLETED} while an enrolment in a
 * {@link ChallengeKind#GOALS_COMPLETED} challenge was looking: whose it is, which enrolment saw it,
 * which goal on which savings account, when it was first seen, and whether it had already been
 * finished before that enrolment began.
 *
 * <p><strong>This is the only thing this module stores that is not an award, and it is stored
 * because the goals module does not date completion.</strong> A goal is {@code COMPLETED} when its
 * allocation has reached its target, which is a comparison between two figures that both move — so
 * the goals ledger can say whether a goal is finished <em>now</em> and can never say when it became
 * so, or whether it has been finished, emptied and finished again since Tuesday. "How many goals
 * have you finished since you enrolled" is therefore a question no derivation over that ledger
 * answers, and the alternative — teaching the goals module to write a {@code completedAt} — was
 * weighed in the feature spec and rejected: it changes a module this feature has no other business
 * in, and it would still need back-filling for every goal already complete.
 *
 * <p>So the reading takes an observation instead. Each pass looks at what the customer's goals say
 * now and writes down the ones this enrolment has not written down before, and the reading is the
 * count of those rows. What is stored is not progress — it is a sighting, at a moment that has
 * passed, which is exactly the sort of thing this application records rather than recomputes.
 *
 * <p><strong>Keyed by the enrolment and the goal, and that pair is what makes each goal count
 * once.</strong> Finishing a goal, emptying it and finishing it again is one goal and so one row:
 * the second sighting finds the first already there and writes nothing. Two different goals are two
 * rows and count twice. And keying by the <em>enrolment</em> rather than by the customer is what
 * keeps the challenge repeatable — a second time round is a second enrolment with sightings of its
 * own, so the goals that filled the first round do not fill the second one for free. A unique index
 * over the two columns is created by {@link ChallengesOnStartUp}, because SQLite writes no composite
 * unique clause from the entity model.
 *
 * <p><strong>{@code alreadyFinishedWhenTheyEnrolled} is a row that deliberately counts for
 * nothing.</strong> A goal that had already reached its target at the moment the customer took the
 * challenge on is not something they did since, and enrolling counts from the moment you enrol.
 * It is written down all the same rather than passed over, for two reasons: the question has to be
 * settled once and stay settled — a goal already finished at enrolment, then emptied and refinished,
 * is still a goal they had already finished — and the answer costs a walk back through that goal's
 * money moves, which is not a thing to redo on every read of a tab.
 *
 * <p>Package-private, like everything this module stores. Nothing of it leaves the module; the
 * reading it adds up to does.
 */
@Entity
class GoalSeenFinished {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Whose goal it is, which is also whose challenge it counts towards. */
    private long customerId;

    /**
     * The enrolment that saw it, which is the scope "already seen" is asked in.
     *
     * <p>An identifier rather than a relation, the way every identifier in this application is held.
     */
    private long enrolmentId;

    /**
     * The challenge by the code the customer took it on under, copied here rather than followed back
     * through the enrolment, for the reason {@link ChallengeAward} copies it: a record that has to be
     * joined through two tables to say what it was about stops meaning anything the first time
     * either of them is retuned.
     */
    private String challengeCode;

    /**
     * Which savings account the goal is on. Not part of the key — a goal identifier is the goal, and
     * the account is where it lives rather than what it is — and written down because a challenge
     * spans every savings account its customer holds, and a reviewer asking why a reading is two
     * rather than one wants to see which accounts the two came off.
     */
    private long savingsAccountId;

    /** The goal itself, which is the identity a goal counts once by. */
    private long goalId;

    /** When this enrolment first saw it finished, which is the moment the pass was judging as of. */
    private Instant seenAt;

    /**
     * Whether it had already reached its target when the customer enrolled, in which case it counts
     * for nothing. See this class's own note: the row exists so that the question is settled once.
     */
    private boolean alreadyFinishedWhenTheyEnrolled;

    protected GoalSeenFinished() {
        // for JPA
    }

    private GoalSeenFinished(long customerId, long enrolmentId, String challengeCode,
                             long savingsAccountId, long goalId, Instant seenAt,
                             boolean alreadyFinishedWhenTheyEnrolled) {
        this.customerId = customerId;
        this.enrolmentId = enrolmentId;
        this.challengeCode = challengeCode;
        this.savingsAccountId = savingsAccountId;
        this.goalId = goalId;
        this.seenAt = seenAt;
        this.alreadyFinishedWhenTheyEnrolled = alreadyFinishedWhenTheyEnrolled;
    }

    /**
     * A goal just seen finished, with everything that decided it.
     *
     * <p>Everything arrives at once because a sighting is written once and never touched again:
     * there is no setter here and no moment at which one of these fields is not yet known. A row
     * that could be completed afterwards would be a row whose verdict could be changed afterwards,
     * and the one thing this table promises is that each goal is judged against an enrolment once.
     */
    static GoalSeenFinished seen(long customerId, long enrolmentId, String challengeCode,
                                 long savingsAccountId, long goalId, Instant seenAt,
                                 boolean alreadyFinishedWhenTheyEnrolled) {
        return new GoalSeenFinished(customerId, enrolmentId, challengeCode, savingsAccountId, goalId,
                seenAt, alreadyFinishedWhenTheyEnrolled);
    }

    long goalId() {
        return goalId;
    }

    long savingsAccountId() {
        return savingsAccountId;
    }

    /** Whether this sighting is one of the ones the reading is a count of. */
    boolean countsTowardsTheChallenge() {
        return !alreadyFinishedWhenTheyEnrolled;
    }
}
