package io.dataroots.savingstreak.points;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One dated batch of points earned by a customer: how many it was worth, how many of those are still
 * unspent, when it was earned, why, and what produced it.
 *
 * <p>Earned by the customer rather than by the savings account the money went into. A customer
 * saving towards two goals earns one pot of points, so which account a deposit was paid into decides
 * where the euros sit and nothing about who the points belong to. Which savings account produced a
 * batch is still answerable — {@code sourceReferenceId} names the deposit, and a deposit knows the
 * account it landed in — and this module has no business keeping a second copy of it.
 *
 * <p>A batch rather than a running total, because points acquire an age. What remains is now less
 * than what was earned for any batch a reward has been taken out of: spending goes oldest-first, and
 * which batch paid for what is a question about individual batches that a total could not answer.
 * What was earned is never written down again — a deposit's reward cannot change after the fact.
 *
 * <p>The age is what finishes a batch off. On the day it was promised it would go, whatever is left
 * in it expires, and the batch is the only thing that could have been asked: a total has no age to
 * have run out — and, since this release, no total could carry the promise either, because the day
 * is written on the batch rather than worked out again every night.
 *
 * <p>Package-private, and that is the point of the module: no caller can learn that points are
 * stored this way, so no caller can come to depend on it.
 */
@Entity
class PointsCredit {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Whose points these are.
     *
     * <p>Nullable in the database only because a batch credited before points belonged to a customer
     * has no value in it. {@link PointsOnStartUp} fills those in before the application serves a
     * single request, so nothing that reads this ever sees a null.
     */
    private Long customerId;

    private long points;

    private long remainingPoints;

    private Instant earnedAt;

    /**
     * When this batch's lifetime is up: the moment it was promised it would expire, written as it
     * was earned and never written again.
     *
     * <p><strong>Stamped rather than recomputed, and that is the whole of this ticket.</strong> The
     * sweep used to work out twelve months from {@link #earnedAt} every night against a constant, so
     * the figure a batch lived by was whatever the constant said tonight rather than whatever it
     * said the day the batch was earned. Shorten the scheme's lifetime to six months and every batch
     * older than six months would die in that night's sweep — including every batch whose owner had
     * been promised a year. A deposit already keeps the rate it was paid at; this is the same answer
     * for the same reason, and it is the only way a change to the points lifetime can leave history
     * alone.
     *
     * <p>The moment rather than the number of months. What a customer is owed is a date, and a
     * column holding "12" would still need the rule applied to it on every read — which is the
     * recomputation this column exists to stop. It also means a reader of the table can see when a
     * batch goes without knowing any rule at all.
     *
     * <p>Nullable in the database only because a batch credited before this release has no value in
     * it. {@link PointsOnStartUp} stamps those with the twelve months they were promised before the
     * application serves a single request, so nothing that reads this ever sees a null — and the
     * sweep says so out loud rather than falling over if it ever does.
     */
    private Instant expiresAt;

    /**
     * When this batch's lifetime ran out, and null for every batch that still has one.
     *
     * <p>Beside {@link #expiresAt} and emphatically not the same fact: one is the promise, made when
     * the batch was earned, and the other is the promise having been kept. A batch that is past its
     * expiry and has not yet been swept has the first and not the second, which is exactly the state
     * a customer is in between an anniversary falling at lunchtime and the sweep running at three
     * the next morning.
     *
     * <p>The anniversary rather than the moment the sweep noticed. The batch expired when its twelve
     * months were up whether or not anything was running at three that morning, and dating it by the
     * run would make the same batch report a different moment depending on when the job next ran.
     *
     * <p>Written instead of emptying {@link #remainingPoints}, which is deliberately left alone:
     * that figure is then what was still in the batch when it went, and it is the only place the
     * number survives. Zeroed, an expired batch would be indistinguishable from a fully spent one.
     */
    private Instant expiredAt;

    @Enumerated(EnumType.STRING)
    private PointsReason reason;

    /**
     * The identifier of the thing that caused this batch, in the module the {@link #reason} names —
     * a deposit under any of the three reasons a deposit earns under, and the gift under {@link
     * PointsReason#GIFT_RECEIVED}.
     *
     * <p>Meaningful only alongside the reason, which it always has been: this is a bare number with
     * no foreign key behind it, and reading one module's identifiers as another's is what the
     * reason is asked for in order to prevent. {@link PointsCreditRepository#earnedBy} says the
     * same thing from the query's end — the reasons are named in it precisely so that a gift's
     * reference is never read as a deposit's.
     */
    private long sourceReferenceId;

    protected PointsCredit() {
        // for JPA
    }

    private PointsCredit(long customerId, long points, PointsReason reason,
                         long sourceReferenceId, Instant earnedAt, Instant expiresAt) {
        this.customerId = customerId;
        this.points = points;
        this.remainingPoints = points;
        this.reason = reason;
        this.sourceReferenceId = sourceReferenceId;
        this.earnedAt = earnedAt;
        this.expiresAt = expiresAt;
    }

    /** The points a deposit earns simply by being made, all of them still there to be spent. */
    static PointsCredit baseAccrualFor(long customerId, long depositId, long points,
                                       Instant earnedAt, Instant expiresAt) {
        return new PointsCredit(customerId, points, PointsReason.BASE_ACCRUAL, depositId, earnedAt,
                expiresAt);
    }

    /**
     * The uplift a deposit earned on top of its euros because the account was on a run of weeks.
     *
     * <p>A batch of its own, dated at the same moment as the base accrual it sits beside. A batch is
     * a batch to everything that reads them: spending draws from the oldest first and neither knows
     * nor cares which reason wrote it, so a bonus is spendable exactly as the euros are.
     */
    static PointsCredit streakBonusFor(long customerId, long depositId, long points,
                                       Instant earnedAt, Instant expiresAt) {
        return new PointsCredit(customerId, points, PointsReason.STREAK_BONUS, depositId, earnedAt,
                expiresAt);
    }

    /**
     * A tenth of the euros a deposit still held on one of its anniversaries, paid for the money
     * having stayed where it was put.
     *
     * <p>An ordinary batch, and that is the whole of what this ledger knows about it: spendable on
     * any reward, spent oldest-first alongside everything else, and gone twelve months after the
     * moment it was earned. Nothing here can tell it from a deposit's own credit except the reason
     * written on it.
     *
     * <p>Dated at the anniversary rather than at the moment the sweep that paid it ran, which the
     * caller supplies. A batch for an anniversary long past therefore arrives already beyond its own
     * twelve months and is swept away by the expiry job the same night — the honest outcome of both
     * rules holding at once, and visible in the log rather than special-cased here.
     */
    static PointsCredit loyaltyBonusFor(long customerId, long depositId, long points,
                                        Instant earnedAt, Instant expiresAt) {
        return new PointsCredit(customerId, points, PointsReason.LOYALTY_BONUS, depositId, earnedAt,
                expiresAt);
    }

    /**
     * A slice of another customer's pot, arriving in this one because they gave it away: as many
     * points as came out of their batch, dated at the moment <em>their</em> batch was earned.
     *
     * <p>The inherited date is the whole reason a gift is sliced rather than spent and re-credited.
     * A fresh date would restart the twelve months on every hop, and two customers passing the same
     * points back and forth would keep a balance alive indefinitely — "a point lasts twelve months"
     * would hold for everybody who never gifted and be void for everybody who did. Dating the
     * arrival at the original earning closes that by construction rather than by another rule.
     *
     * <p>An ordinary batch in every other respect, which is the point of crediting it this way:
     * spendable on any reward, spent oldest-first alongside everything else, counted in what the
     * customer is told expires next, and gone twelve months after the moment it was earned. Nothing
     * in this ledger can tell it from a deposit's own credit except the reason written on it — and
     * a batch handed over after its own anniversary has passed arrives already beyond its twelve
     * months and goes in the same night's sweep, which is both rules holding at once rather than
     * either misbehaving.
     *
     * <p>The reference is the gift rather than a deposit. Nothing about this batch points at a
     * deposit, because no deposit of this customer's earned it.
     */
    static PointsCredit giftReceivedFor(long customerId, long giftId, long points,
                                        Instant earnedAt, Instant expiresAt) {
        return new PointsCredit(customerId, points, PointsReason.GIFT_RECEIVED, giftId, earnedAt,
                expiresAt);
    }

    /**
     * What a rung of a challenge paid the customer for reaching it: the points that rung is worth,
     * dated at the moment the reading cleared it.
     *
     * <p>An ordinary batch, and that is the whole of what this ledger knows about a challenge.
     * Spendable on any reward, spent oldest-first alongside everything else, counted in what the
     * customer is told expires next, and gone twelve months after the moment it was earned —
     * nothing here can tell it from a deposit's own credit except the reason written on it. What a
     * rung asks for, what it pays and whether it has already been paid are the Challenges module's
     * rule end to end, and a ledger that had an opinion about any of them would be a second opinion
     * about a figure that has one.
     *
     * <p>The reference is the award rather than a deposit. No deposit of this customer's earned
     * these points: a rung is cleared by a reading over the whole of their saving, one deposit may
     * clear three rungs and the next may clear none, and the thing that says which rung was paid
     * and what reading won it is the award. Reading this reference as a deposit is exactly what the
     * reason beside it exists to prevent.
     */
    static PointsCredit challengeRewardFor(long customerId, long awardId, long points,
                                           Instant earnedAt, Instant expiresAt) {
        return new PointsCredit(customerId, points, PointsReason.CHALLENGE_REWARD, awardId, earnedAt,
                expiresAt);
    }

    /**
     * What a claim cost, handed back because an administrator revoked the voucher it paid for:
     * a new batch, dated at the moment of the cancellation.
     *
     * <p><strong>A new batch rather than the old ones topped back up, which is the whole of the
     * decision and the reason this is a factory at all.</strong> Points are spent oldest-first,
     * so a claim takes from the batches closest to their own twelve months — and by the time
     * anybody notices the claim was a mistake, some of those batches may have gone. Putting the
     * points back where they came from would put them into batches that have already expired,
     * where the balance would not count them and nothing could ever spend them, while the
     * customer had been told they had their points back. A refund nobody can spend is worse than
     * no refund, because only one of the two is visible from the outside. Nothing here even knows
     * which batches paid, and deliberately: this ledger has never recorded that, and inventing
     * the record in order to reverse it would be building the wrong thing twice over.
     *
     * <p>Dated at the cancellation rather than inherited, which is where this parts company with
     * {@link #giftReceivedFor} above. A gift inherits its date because two customers passing
     * points back and forth would otherwise keep a balance alive for ever; a refund has nobody to
     * pass to, and the customer is being handed back something they never had the use of. Twelve
     * months of its own, from today, is what makes it worth what it should be worth — and it is
     * the one thing that would be quietly wrong if this reused a factory above it.
     *
     * <p>An ordinary batch in every other respect, which is the point of crediting it this way:
     * spendable on any reward, spent oldest-first alongside everything else, counted in what the
     * customer is told expires next, giftable, and gone twelve months after the moment it was
     * credited. Nothing in this ledger can tell it from a deposit's own credit except the reason
     * written on it.
     *
     * <p>The reference is the claim that was cancelled. No deposit of this customer's earned
     * these points, and the claim is the only thing that says which voucher they came back from.
     */
    static PointsCredit redemptionCancelledFor(long customerId, long redemptionId, long points,
                                               Instant refundedAt, Instant expiresAt) {
        return new PointsCredit(customerId, points, PointsReason.REDEMPTION_CANCELLED,
                redemptionId, refundedAt, expiresAt);
    }

    /**
     * How much of this batch has neither been spent nor expired — or, once {@link #expiredAt} is
     * set, how much of it was left when its lifetime ran out.
     */
    long getRemainingPoints() {
        return remainingPoints;
    }

    /** When it was earned, which is what its lifetime was counted from. */
    Instant getEarnedAt() {
        return earnedAt;
    }

    /**
     * The moment this batch was promised it would go, which is the only thing anything reads to
     * decide whether it has.
     *
     * <p>Null only for a batch written before this release and only until {@link PointsOnStartUp}
     * has run, which is before the application answers anything.
     */
    Instant getExpiresAt() {
        return expiresAt;
    }

    /**
     * Writes the promise onto a batch credited before this release, and answers whether it had to.
     *
     * <p><strong>A floor and never a reset</strong>, which is the whole of the rule every
     * {@code …OnStartUp} in this application follows: a batch that already carries an expiry keeps
     * the one it carries, whatever this is offered. A start-up pass that corrected what it found
     * would make every stamp last until the next restart, and a stamp that a restart can move is not
     * a promise — it is the recomputation this column exists to replace, run once a morning instead
     * of once a night.
     *
     * <p>The batch decides, so that the backfill cannot get it wrong by forgetting to ask first, in
     * the same way {@link #expire} is the batch's own and not a caller's.
     */
    boolean stampExpiringAt(Instant promised) {
        if (expiresAt != null) {
            return false;
        }
        expiresAt = promised;
        return true;
    }

    /** Why it was earned, which a sweep says out loud so a lost bonus is not read as lost euros. */
    PointsReason getReason() {
        return reason;
    }

    Long getId() {
        return id;
    }

    Long getCustomerId() {
        return customerId;
    }

    /**
     * Ends this batch as at the moment it was promised it would go, and answers how many points that
     * cost the customer.
     *
     * <p>The batch decides, so that nothing outside can expire one twice: a batch that has already
     * gone answers zero and keeps the moment it originally went, which is what makes a second sweep
     * over the same rows a sweep that takes nothing.
     */
    long expire(Instant anniversary) {
        if (expiredAt != null) {
            return 0;
        }
        expiredAt = anniversary;
        return remainingPoints;
    }

    /**
     * Takes up to {@code wanted} points out of this batch and answers how many that was — all of
     * them if the batch is big enough, and everything left in it if it is not.
     *
     * <p>The batch decides how much of itself can be taken, so no caller has to work out the
     * smaller of two numbers and none can take a batch below zero by getting it wrong.
     */
    long take(long wanted) {
        long taken = Math.min(wanted, remainingPoints);
        remainingPoints -= taken;
        return taken;
    }
}
