package io.dataroots.savingstreak.points;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One dated batch of points earned by a savings account: how many it was worth, how many of those
 * are still unspent, when it was earned, why, and what produced it.
 *
 * <p>A batch rather than a running total, because points acquire an age. What remains is now less
 * than what was earned for any batch a reward has been taken out of: spending goes oldest-first, and
 * which batch paid for what is a question about individual batches that a total could not answer.
 * What was earned is never written down again — a deposit's reward cannot change after the fact.
 *
 * <p>Package-private, and that is the point of the module: no caller can learn that points are
 * stored this way, so no caller can come to depend on it.
 */
@Entity
class PointsCredit {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long savingsAccountId;

    private long points;

    private long remainingPoints;

    private Instant earnedAt;

    @Enumerated(EnumType.STRING)
    private PointsReason reason;

    /** What earned the points — a deposit, for as long as base accrual is the only reason. */
    private long sourceReferenceId;

    protected PointsCredit() {
        // for JPA
    }

    private PointsCredit(long savingsAccountId, long points, PointsReason reason,
                         long sourceReferenceId, Instant earnedAt) {
        this.savingsAccountId = savingsAccountId;
        this.points = points;
        this.remainingPoints = points;
        this.reason = reason;
        this.sourceReferenceId = sourceReferenceId;
        this.earnedAt = earnedAt;
    }

    /** The points a deposit earns simply by being made, all of them still there to be spent. */
    static PointsCredit baseAccrualFor(long savingsAccountId, long depositId, long points, Instant earnedAt) {
        return new PointsCredit(savingsAccountId, points, PointsReason.BASE_ACCRUAL, depositId, earnedAt);
    }

    long getRemainingPoints() {
        return remainingPoints;
    }

    /**
     * Takes up to {@code wanted} points out of this batch and answers how many that was — all of
     * them if the batch is big enough, and everything left in it if it is not.
     *
     * <p>The batch decides how much of itself can be taken, so no caller has to work out the
     * smaller of two numbers and none can take a batch below zero by getting it wrong.
     */
    long take(long wanted) {
        long taken = Math.min(wanted, remainingPoints);
        remainingPoints -= taken;
        return taken;
    }
}
