package io.dataroots.savingstreak.accounts;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One date a recurring bill fell due, and what became of it: which bill, which account, the day it
 * was due, the moment it was actually settled, what was asked for, and whether it was paid.
 *
 * <p><strong>One row per bill per due date, whether or not money moved.</strong> That is why this
 * table exists beside the money that left rather than being derived from it: a due date that met an
 * empty account is as much a part of the history as one that took nine hundred euros, and a ledger
 * of movements has no row for a movement that did not happen. It is also the only thing that can
 * answer "when was my rent last taken" — {@link CurrentAccount} keeps a figure rather than a sum of
 * records, so the balance says nothing at all about which bills moved it.
 *
 * <p><strong>Unique over the bill and the day due, and that uniqueness is the idempotency.</strong>
 * A trainer runs the nightly job by hand, twice, and a demonstration that took the rent twice would
 * be worse than no demonstration. The bill's cursor also keeps a second run from finding the date
 * due — but the check and the guarantee are different things. Two runs at the same moment would both
 * read the same cursor and the same empty set of settled dates, and only a rule the database keeps
 * stops both of them from withdrawing. On this table that is money, not points. It is the same
 * bargain {@link IncomePaid}, {@code RuleOccurrence} and {@code LoyaltyBonusPaid} strike.
 *
 * <p>The uniqueness is not declared here, and that is not an oversight. The schema is generated from
 * the entity model ({@code ddl-auto=update}) against SQLite, whose dialect writes a composite unique
 * clause nowhere: declared as {@code @UniqueConstraint} — or as a {@code @Index} marked unique,
 * which Hibernate turns into one — the table is created without it and the only statement that
 * reaches the database is an {@code alter table ... drop constraint} that does nothing. So
 * {@link AccountsOnStartUp} creates the index itself, in a statement SQLite does accept, before the
 * application serves anything.
 *
 * <p><strong>Both moments are kept because they are different facts.</strong> {@code dueOn} is the
 * day the money was owed and is half the key; {@code settledAt} is when the application got round to
 * it, which on a wound clock or after downtime is a different day — and the gap between them is the
 * lateness, which is what a trainer demonstrating catch-up points at. A day rather than a moment for
 * the first of the two, because that is what is promised: a bill is declared for a day of the month,
 * and it is also what makes the pair a key at all — two moments a night apart are two different
 * values, and "the first" is one.
 *
 * <p><strong>The amount is what was asked for, written down because the declaration can change and
 * this cannot.</strong> A customer whose rent goes up in March has a February row that still says
 * what February cost. It is the same figure on a paid row and on an unpaid one: what an unpaid row
 * records is a debit that was presented for that much and refused, and a zero there would lose the
 * one number a customer needs in order to know what they still owe.
 *
 * <p>Package-private, like the bill it belongs to and like every row in this module.
 * {@link ABillThatFellDue} is what leaves.
 */
@Entity
class BillOccurrence {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The bill this happened to, as an identifier rather than a relation — the same way this module
     * holds every other reference between its rows, and for the reason a history has to outlive what
     * it is about: a bill that has been ended keeps its dates, and they read exactly as they did.
     * Half of what makes this row unique.
     */
    private long recurringBillId;

    /**
     * The account the money was to leave, carried rather than read back through the bill.
     *
     * <p>The bill can be ended and the declaration on it changed, and neither of those should make a
     * settled date harder to explain. It is also what lets everything this account was presented
     * with be asked for in one query, which is the read the still-owed list and the ledger are
     * about.
     */
    private long currentAccountId;

    /** The day the money was owed, and the other half of the key. */
    private LocalDate dueOn;

    /** The moment the date was actually settled, off the application's clock. */
    private Instant settledAt;

    /** What was asked for on that date, to the cent. */
    private BigDecimal amount;

    /** Whether the money left, written as its name so a row read with a SQLite client says so. */
    @Enumerated(EnumType.STRING)
    private BillOutcome outcome;

    /**
     * The moment this date was presented and refused, which is the moment it became an arrear — and
     * null on a date that was paid the first time it was presented.
     *
     * <p><strong>Kept beside {@code settledAt} rather than instead of it, because the two are
     * different facts and {@code settledAt} moves.</strong> An arrear settled two months late has
     * its {@code settledAt} moved to the day the money was finally taken, which is exactly what the
     * ledger needs and exactly what destroys the record of when the hole opened. This field does not
     * move, ever: a date went unpaid once, on one night, and the pair of moments is the stretch of
     * time the account carried that debt for.
     *
     * <p>That stretch is what the notifications module's 04:00 raiser reads. Whether a customer's
     * arrears have <em>crossed</em> the piling-up threshold — rather than merely standing over it
     * for the fortieth night running — is a question about how the count moved over time, and it can
     * only be answered from rows that say when each debt started and when it ended. It is also what
     * makes a notification re-derivable without re-running a debit, which is the separation the
     * whole 02:30-records-facts, 04:00-reads-them arrangement exists to keep.
     *
     * <p>It is also the marker for "this date ever went unpaid", and survives the settlement: a row
     * carrying a moment here fell short once, whatever its outcome reads now. A row written before
     * this column existed carries null and is therefore invisible to the raiser, which is the right
     * answer rather than a gap — a notification that cannot say what the account was short is not
     * worth raising, and there is nowhere left to find the figure out.
     */
    private Instant fellShortAt;

    /**
     * What the current account actually held at the moment this date was presented and refused, and
     * null on a date that was paid.
     *
     * <p>The other half of the sentence a customer needs: the amount says what was asked for, this
     * says what was there, and the difference is how far short they were. Written down at 02:30
     * rather than read back at 04:00 because a balance is a figure about now and this is a figure
     * about a night that has passed — the account may well have been paid into since, and a
     * notification quoting tonight's balance against March's rent would be telling a customer
     * something that was never true.
     *
     * <p>It is not updated when the arrear is later settled, for the reason {@code fellShortAt} is
     * not: it is what happened on the night it happened.
     */
    private BigDecimal balanceThatFellShort;

    protected BillOccurrence() {
        // for JPA
    }

    private BillOccurrence(long recurringBillId, long currentAccountId, LocalDate dueOn,
                           Instant settledAt, BigDecimal amount, BillOutcome outcome,
                           Instant fellShortAt, BigDecimal balanceThatFellShort) {
        this.recurringBillId = recurringBillId;
        this.currentAccountId = currentAccountId;
        this.dueOn = dueOn;
        this.settledAt = settledAt;
        this.amount = amount;
        this.outcome = outcome;
        this.fellShortAt = fellShortAt;
        this.balanceThatFellShort = balanceThatFellShort;
    }

    /** A due date whose money left the account on the night it was presented. */
    static BillOccurrence paid(long recurringBillId, long currentAccountId, LocalDate dueOn,
                               Instant settledAt, BigDecimal amount) {
        return new BillOccurrence(recurringBillId, currentAccountId, dueOn, settledAt, amount,
                BillOutcome.PAID, null, null);
    }

    /**
     * A due date that was presented and refused: nothing moved, it stays owed, and the night it
     * happened on and the balance that fell short are written down with it.
     *
     * <p>Two factories rather than one taking an outcome, so that a paid row carrying a shortfall —
     * or an unpaid one carrying none — cannot be constructed at all. It is the bargain
     * {@code Notification}'s own factories strike for the same reason.
     */
    static BillOccurrence fellShort(long recurringBillId, long currentAccountId, LocalDate dueOn,
                                    Instant fellShortAt, BigDecimal amount,
                                    BigDecimal balanceThatFellShort) {
        return new BillOccurrence(recurringBillId, currentAccountId, dueOn, fellShortAt, amount,
                BillOutcome.UNPAID, fellShortAt, balanceThatFellShort);
    }

    /**
     * Records that this date, which had gone unpaid, has now been settled: the outcome becomes
     * {@link BillOutcome#PAID} and the moment moves to when the money was actually taken.
     *
     * <p><strong>The row is updated in place rather than a second one written.</strong> One row per
     * bill per due date is the rule the unique index keeps, and an arrear settled two months late is
     * still one March rent — a second row under that date could not be written at all, and a row
     * written under the day it was settled on would be the history claiming March's rent fell due in
     * May.
     *
     * <p><strong>{@code dueOn} does not move, and neither does {@code amount}.</strong> The day it
     * was owed from is a fact about March and stays one, which is what lets the ledger show both
     * dates and what lets the lateness be worked out at all. The amount is what was originally
     * asked for, and an arrear costs exactly that and never a cent more: no interest, no fee, no
     * charge of any kind. The accumulation is the whole of the consequence.
     */
    void settledLate(Instant when) {
        this.settledAt = when;
        this.outcome = BillOutcome.PAID;
    }

    Long getId() {
        return id;
    }

    long getRecurringBillId() {
        return recurringBillId;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    LocalDate getDueOn() {
        return dueOn;
    }

    Instant getSettledAt() {
        return settledAt;
    }

    BigDecimal getAmount() {
        return amount;
    }

    BillOutcome getOutcome() {
        return outcome;
    }

    Instant getFellShortAt() {
        return fellShortAt;
    }

    BigDecimal getBalanceThatFellShort() {
        return balanceThatFellShort;
    }
}
