package io.dataroots.savingstreak.accounts;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * A bank customer, and in this training scenario the whole of the identity model.
 *
 * <p>Signing in is recognising the address somebody typed, and that is all it is: there is no
 * password on this record, no session on the server, and nothing anywhere that stops a request from
 * naming an account it was never shown. Authentication is a slice this application has not built.
 * The contact details are what a customer signs in with because it is the one thing they already
 * know about themselves — not because knowing it proves anything.
 */
@Entity
public class Customer {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String contactDetails;

    protected Customer() {
        // for JPA
    }

    public Customer(String name, String contactDetails) {
        this.name = name;
        this.contactDetails = contactDetails;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getContactDetails() {
        return contactDetails;
    }
}
