package io.dataroots.savingstreak.accounts;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One payday that has been credited: which current account, the day it was due, the moment it was
 * actually paid, and what landed.
 *
 * <p>What makes the job idempotent, and by construction rather than by care. A row per current
 * account per day due, <strong>unique over the pair</strong>, means a second run over the same
 * account cannot pay the same payday twice even if the cursor underneath it were rewritten — the
 * same bargain {@code LoyaltyBonusPaid} strikes for an anniversary, and for the same reason.
 *
 * <p>The uniqueness is not declared here, and that is not an oversight. The schema is generated from
 * the entity model ({@code ddl-auto=update}) against SQLite, whose dialect writes a composite unique
 * clause nowhere: declared as {@code @UniqueConstraint} — or as a {@code @Index} marked unique,
 * which Hibernate turns into one — the table is created without it and the only statement that
 * reaches the database is an {@code alter table ... drop constraint} that does nothing. The
 * generated DDL in a DEBUG start-up log says so out loud. So {@link AccountsOnStartUp} creates the
 * index itself, in a statement SQLite does accept, before the application serves anything — and the
 * guarantee is then actually in the file rather than only in an annotation.
 *
 * <p>Deriving the same fact from the balance was never possible: a current account's balance is a
 * figure rather than a sum of records, as {@link CurrentAccount} explains, so nothing about it says
 * which paydays put money into it. This table is the only record there is.
 *
 * <p>Both moments are kept, because they are different facts. {@code dueOn} is the day the customer
 * was owed the money and is half the key; {@code paidAt} is when the application got round to it,
 * which on a wound clock or after downtime is a different day — and the gap between them is the
 * lateness, which is a thing a trainer demonstrating catch-up wants to be able to point at.
 *
 * <p>Never rewritten. What was paid is what happened, and a later change to the declared figure
 * changes what lands next month rather than what landed last.
 *
 * <p>Package-private, like the repository and like every row in this module.
 */
@Entity
class IncomePaid {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The account the money landed in, and half of what makes this row unique. */
    private long currentAccountId;

    /**
     * The day the money was due, which is the day the customer names when they ask why their
     * balance moved — and the other half of the key.
     *
     * <p>A day rather than a moment, because that is what is promised: an income is declared for a
     * day of the month, the job that credits it runs at one in the morning, and an exact time would
     * be precision nobody said. It is also what makes the pair a key at all — two moments a night
     * apart are two different values, and "the twenty-fifth" is one.
     */
    private LocalDate dueOn;

    /** The moment the credit was actually made, off the application's clock. */
    private Instant paidAt;

    /** What landed, written down because the declared figure can change and this one cannot. */
    private BigDecimal amount;

    protected IncomePaid() {
        // for JPA
    }

    private IncomePaid(long currentAccountId, LocalDate dueOn, Instant paidAt, BigDecimal amount) {
        this.currentAccountId = currentAccountId;
        this.dueOn = dueOn;
        this.paidAt = paidAt;
        this.amount = amount;
    }

    /** A payday that has just been credited, with everything it was decided from. */
    static IncomePaid of(long currentAccountId, LocalDate dueOn, Instant paidAt, BigDecimal amount) {
        return new IncomePaid(currentAccountId, dueOn, paidAt, amount);
    }

    LocalDate getDueOn() {
        return dueOn;
    }
}
