package io.dataroots.savingstreak.accounts;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * What a customer says lands in one current account every month: a day of the month and an amount.
 *
 * <p><strong>Declared, never invented.</strong> There is no default salary and no figure derived
 * from anything the customer has done. An account with no row here receives nothing and behaves
 * exactly as a current account behaved before this existed — which is the honest state, because a
 * default would be the application putting words in a customer's mouth and then paying them. It is
 * the same argument {@code TheWeeklyAmountThatCanBeSaved} makes about a capacity nobody declared,
 * and it lands harder here because the consequence is money.
 *
 * <p><strong>One row per current account, and changing it replaces the figure.</strong> A second
 * declaration is the customer saying what they are paid now, not a second salary, so the row is
 * rewritten rather than appended to. The uniqueness is a single column, which is the one shape the
 * SQLite dialect does write out — the composite one this feature also needs is created at start-up
 * instead, and {@link IncomePaid} says why.
 *
 * <p><strong>The cursor is the point of this row that is not the declaration.</strong>
 * {@code paidThrough} is the moment through which this account's paydays have been settled, and it
 * starts at the moment the income was declared. That is what makes a declaration made today a
 * promise about the future rather than a year of back pay: every payday strictly after the cursor
 * and at or before now is credited, and the paydays that fell while nobody had declared anything are
 * on the wrong side of it for ever.
 *
 * <p>A cursor rather than "the latest day already paid" because the two answer different questions
 * when nothing has been paid at all. The latest paid day of an account that has never been paid is
 * an absence, and an absence has to be read as something — either as the beginning of time, which is
 * the year of back pay, or as the declaration, which is what this column simply holds. The record of
 * what has been paid is still kept, in {@link IncomePaid}, and it is what makes the job idempotent;
 * the cursor is what makes it bounded.
 *
 * <p>Package-private, like every row in this module. {@link DeclaredIncome} is what leaves.
 */
@Entity
class MonthlyIncome {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The account the money lands in, at most once.
     *
     * <p>Unique because two rows for one account would be two answers to a question that has one,
     * and a customer would be paid twice a month by whichever pair of rows the job happened to read.
     */
    @Column(unique = true)
    private long currentAccountId;

    /**
     * The day of the month the money lands on, 1 to 31 as a customer would say it.
     *
     * <p>Kept as the day that was said rather than as the day it will actually fall on, because they
     * differ every February and the customer's answer is the 31st all the same. Which day a short
     * month lands it on is {@link WhenIncomeIsDue}'s arithmetic, made on every run, so a declaration
     * made in a long month does not carry a clamped day into the next short one.
     */
    private int dayOfMonth;

    /** What lands, to the cent. */
    private BigDecimal amount;

    /** When the figure now in force was declared, replaced along with it. */
    private Instant declaredAt;

    /**
     * The moment through which this account's paydays have been settled — the cursor.
     *
     * <p>Set to the declaration when the income is first declared, and moved to the moment of each
     * run as the run finishes with the account. A payday is credited when it falls strictly after
     * this and at or before the moment being run for.
     *
     * <p>Left where it is when the declaration changes, deliberately, and this is a narrower claim
     * than it first reads as. It protects a payday moved <strong>earlier</strong>: a customer paid
     * on the 25th who says on the 26th that they are paid on the 5th has had January's salary, and a
     * cursor past the 25th puts the 5th of January behind it where it belongs. It does <em>not</em>
     * protect a payday moved <strong>later within a month already paid</strong> — the 5th moved to
     * the 25th on the 20th of January falls in front of a cursor sitting at the 6th, and this column
     * has nothing to say about it. What stops that being a second salary is {@link IncomePaid}: one
     * salary a calendar month, asked of the record rather than inferred from the cursor.
     *
     * <p>Which is the division of labour the rest of this row already describes. The cursor is what
     * keeps a run bounded — it is why a declaration made today is not a year of back pay — and the
     * record is what makes the run idempotent. A cursor that jumped forward on every edit would be
     * the bound doing the record's job, and would silently swallow a payday that fell between the
     * two edits and had not been paid at all.
     */
    private Instant paidThrough;

    protected MonthlyIncome() {
        // for JPA
    }

    MonthlyIncome(long currentAccountId, int dayOfMonth, BigDecimal amount, Instant declaredAt) {
        this.currentAccountId = currentAccountId;
        this.dayOfMonth = dayOfMonth;
        this.amount = amount;
        this.declaredAt = declaredAt;
        this.paidThrough = declaredAt;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    int getDayOfMonth() {
        return dayOfMonth;
    }

    BigDecimal getAmount() {
        return amount;
    }

    Instant getDeclaredAt() {
        return declaredAt;
    }

    Instant getPaidThrough() {
        return paidThrough;
    }

    /**
     * The customer says what they are paid now. The figure and the day are replaced and the cursor
     * is left alone, which guards a payday moved earlier and nothing else — the field says why, and
     * says where a payday moved later is guarded instead.
     */
    void redeclare(int dayOfMonth, BigDecimal amount, Instant declaredAt) {
        this.dayOfMonth = dayOfMonth;
        this.amount = amount;
        this.declaredAt = declaredAt;
    }

    /**
     * The run has finished with this account, so nothing at or before this moment is due any more.
     *
     * <p>Never moved backwards. The clock this application runs on only reads forward, but a cursor
     * that could be wound back would be a job that pays a month twice on the run after it — and the
     * record of what has been paid would be the only thing stopping it, which is one guarantee doing
     * two jobs.
     */
    void settledThrough(Instant moment) {
        if (paidThrough == null || moment.isAfter(paidThrough)) {
            paidThrough = moment;
        }
    }
}
