package io.dataroots.savingstreak.accounts;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One thing a customer says leaves their current account every month: a name they recognise, a day
 * of the month and an amount.
 *
 * <p><strong>The outbound mirror of {@link MonthlyIncome}</strong>, and it lives beside it because
 * it is a fact about a current account. Nothing in deposits, automation, goals or streaks needs to
 * know it exists: what a bill does to the rest of this application is move the balance those modules
 * already read, and a module that had heard of a rent would be a module with an opinion about one.
 *
 * <p><strong>Declared, never invented.</strong> There is no generated spending and no randomness —
 * there is none anywhere in this application, and a bill nobody typed would be the one dishonest
 * thing in it. A household scenario is a named set of declarations in the demo seed, and nothing
 * else.
 *
 * <p><strong>Many per account, unlike an income, and that is the one shape the two do not
 * share.</strong> A salary is one figure a month, so {@link MonthlyIncome} is unique on the account
 * and a second declaration rewrites it. A household has a rent and a phone bill and an energy bill,
 * so a second bill here is a second bill: there is no uniqueness on the account, and a customer who
 * declares two rents by mistake has two rents until they end one. What bounds the list instead is a
 * cap on how many may stand at once — see {@code AccountsService}, and the identical reasoning
 * behind the cap on saving rules. An unbounded list is a denial of service on every nightly run
 * that walks it.
 *
 * <p><strong>The day is kept as the customer said it, 1 to 31.</strong> The 31st stays the 31st;
 * which day a short month takes it on is arithmetic made on every run, so that a bill declared in a
 * long month does not carry a clamped day into the next short one. Refusing the 31st here would
 * make a real rent undeclarable, which is why the rule is 1 to 31 and not 1 to 28.
 *
 * <p><strong>The cursor is the one field that is not the declaration.</strong>
 * {@code settledThrough} is the moment through which this bill's due dates have been settled, and
 * it starts at the moment the bill was declared, exactly as an income's does. That is what makes a
 * bill declared today a promise about the future rather than a year of back rent: the due dates
 * that fell while nobody had declared anything are on the wrong side of it for ever. It is read and
 * moved by {@link BillsAreTakenWhenTheyFallDue}'s nightly run and by nothing else, and it moves past
 * a date that went unpaid as well as one that was taken — see the field below, which says why
 * holding it back would be worse than moving it.
 *
 * <p><strong>Ending is one-way</strong>, following the precedent {@code RuleState} set: the bill
 * leaves the standing list, stays readable among the ended, and cannot be changed or ended again.
 * {@link BillState} argues why.
 *
 * <p>Package-private, like every row in this module. {@link ADeclaredBill} is what leaves.
 */
@Entity
class RecurringBill {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The account the money leaves. Not unique, deliberately: see above, a household has more than
     * one bill and the cap rather than a constraint is what keeps the list finite.
     */
    private long currentAccountId;

    /**
     * What the customer calls it — "Rent", "Energy", "Phone".
     *
     * <p>The whole reason a bill is a row rather than a figure. A balance that fell by nine hundred
     * euros with nothing saying what took it is a number a customer cannot argue with, and arguing
     * with it is the skill this application exists to teach.
     */
    private String name;

    /**
     * The day of the month it goes out on, 1 to 31 as a customer would say it.
     *
     * <p>Kept as the day that was said rather than as the day it will actually fall on, for the
     * reason {@link MonthlyIncome} gives about the same column: they differ every February and the
     * customer's answer is the 31st all the same.
     */
    private int dayOfMonth;

    /** What goes out, to the cent. */
    private BigDecimal amount;

    /** When the bill now in force was declared. Replaced along with the figures it describes. */
    private Instant declaredAt;

    /** Whether it is still going out every month, or has been ended for good. */
    @Enumerated(EnumType.STRING)
    private BillState state;

    /** When it was ended, and nothing at all while it still stands. Filled exactly when ended. */
    private Instant endedAt;

    /**
     * The moment through which this bill's due dates have been settled — the cursor.
     *
     * <p>Set to the declaration when the bill is first declared, and moved by the run that takes it
     * once there is one. A due date is taken when it falls strictly after this and at or before the
     * moment being run for.
     *
     * <p>Left where it is when the declaration changes, for the reason {@link MonthlyIncome} argues
     * at length: a customer correcting their rent is not asking to be charged again for the months
     * already settled, nor to have a date that fell yesterday quietly swallowed.
     *
     * <p><strong>It advances past a date that went unpaid.</strong> A bill the account could not
     * cover is recorded as {@link BillOutcome#UNPAID} and the cursor moves on all the same, because
     * arrears are tracked by those rows and not by holding the cursor back — a cursor left behind
     * would re-derive the same date every night for ever, which would settle it twice the first time
     * the money was there and destroy the idempotence the record exists to give.
     */
    private Instant settledThrough;

    protected RecurringBill() {
        // for JPA
    }

    RecurringBill(long currentAccountId, String name, int dayOfMonth, BigDecimal amount,
                  Instant declaredAt) {
        this.currentAccountId = currentAccountId;
        this.name = name;
        this.dayOfMonth = dayOfMonth;
        this.amount = amount;
        this.declaredAt = declaredAt;
        this.state = BillState.STANDING;
        this.settledThrough = declaredAt;
    }

    Long getId() {
        return id;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    String getName() {
        return name;
    }

    int getDayOfMonth() {
        return dayOfMonth;
    }

    BigDecimal getAmount() {
        return amount;
    }

    Instant getDeclaredAt() {
        return declaredAt;
    }

    BillState getState() {
        return state;
    }

    Instant getEndedAt() {
        return endedAt;
    }

    Instant getSettledThrough() {
        return settledThrough;
    }

    /** Whether this bill is over, which is the one thing every change to it has to ask first. */
    boolean isEnded() {
        return !state.isStillStanding();
    }

    /**
     * The customer says what this bill is now: its name, its day, its amount. All three at once,
     * because what is written is the bill as it would then read — which of the three the customer
     * actually named is {@code AccountsService}'s question, and it fills the others from what is
     * already here.
     *
     * <p>The cursor and the moment it was first declared are deliberately untouched. The field says
     * why for the cursor; the moment is re-stamped because it is "when the figure now in force was
     * declared", which is the same reading {@link MonthlyIncome#redeclare} gives it.
     */
    void nowSays(String name, int dayOfMonth, BigDecimal amount, Instant declaredAt) {
        this.name = name;
        this.dayOfMonth = dayOfMonth;
        this.amount = amount;
        this.declaredAt = declaredAt;
    }

    /**
     * Moves the cursor to the moment this bill's due dates are now settled through.
     *
     * <p>Written by the nightly run and by nothing else. On an ordinary run that is the moment the
     * run judged every bill against, so that the next run counts from there; on a run whose catch-up
     * was capped it is the beginning of the last date this run actually settled, so that the next
     * run continues from exactly where this one put it down rather than skipping what it left.
     *
     * <p>Only ever forwards in practice, because the application's clock only moves forwards. It is
     * not enforced here: the guard that actually matters is the record, which refuses a second
     * settlement of a due date whatever any cursor says.
     */
    void settledThrough(Instant settledThrough) {
        this.settledThrough = settledThrough;
    }

    /**
     * Ends the bill for good, and answers whether it was still standing — so that a second ending
     * can be refused by whoever asked rather than quietly written twice.
     *
     * <p>The name, the day and the amount are left exactly as they were. They are what the record is
     * <em>for</em>: a customer reading what they used to pay is reading these three, and an ending
     * that cleared them would leave a row saying only that something once went out.
     */
    boolean end(Instant endedAt) {
        if (isEnded()) {
            return false;
        }
        this.state = BillState.ENDED;
        this.endedAt = endedAt;
        return true;
    }
}
