package io.dataroots.savingstreak.sharedpots;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One customer asking another to join a shared pot: which pot, who asked, who was asked, what role
 * they were offered, where the asking stands, and when it was sent and answered.
 *
 * <p>A row of its own rather than a membership that is not real yet, because an invitation is a
 * thing that happened and that outlives its answer. A declined invitation is not a membership with a
 * flag off — there is no membership — and the pot's own list has to go on showing that somebody was
 * asked and said no, which is the record {@link SharedPotsService} reads back.
 *
 * <p><strong>The customer invited is stored as an identifier and not as the address that was
 * typed.</strong> The address is how a person names somebody they know the email of, and it is
 * resolved once, when the invitation is sent: an invitation that kept the text would be a second
 * answer to "who is this for" that nothing keeps true — an address changed afterwards would leave an
 * invitation pointing at nobody, or worse, at whoever took the address over. It is the same line
 * every other module draws about referring to a customer.
 *
 * <p>The role and the state are stored as their words rather than as their positions, so that a
 * value added to {@link PotRole} or {@link InvitationState} cannot silently change what every
 * existing row means.
 *
 * <p>{@code answeredAt} is the moment it stopped waiting, whoever stopped it — accepted, declined or
 * revoked. One column for the three, because what it is used for is the same in all three cases:
 * saying when this stopped being a question. Which of the three it was is the state's job, and a
 * column per outcome would be three nulls on every row to say one thing.
 *
 * <p>There is deliberately no expiry moment here. Nothing in this application expires an invitation;
 * {@link InvitationState} argues that out.
 *
 * <p>Package-private, like the repository that reads it. {@link APotInvitation} is what leaves.
 */
@Entity
class PotInvitation {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long sharedPotId;

    /** The owner who sent it. Kept after it is answered, because the pot's record says who asked. */
    private long invitedByCustomerId;

    /** The customer the address resolved to when it was sent. */
    private long invitedCustomerId;

    /** What they would be to the pot if they accept — and, once they have, what they are. */
    @Enumerated(EnumType.STRING)
    private PotRole role;

    @Enumerated(EnumType.STRING)
    private InvitationState state;

    /** When it was sent, off the application's clock rather than the machine's. */
    private Instant invitedAt;

    /** When it stopped waiting, and null for as long as it still is. */
    private Instant answeredAt;

    protected PotInvitation() {
        // for JPA
    }

    private PotInvitation(long sharedPotId, long invitedByCustomerId, long invitedCustomerId,
                          PotRole role, Instant invitedAt) {
        this.sharedPotId = sharedPotId;
        this.invitedByCustomerId = invitedByCustomerId;
        this.invitedCustomerId = invitedCustomerId;
        this.role = role;
        this.state = InvitationState.PENDING;
        this.invitedAt = invitedAt;
    }

    /**
     * An invitation about to be sent. It starts {@link InvitationState#PENDING} and can start
     * nowhere else: an invitation nobody has answered is the only kind there is to make.
     */
    static PotInvitation of(long sharedPotId, long invitedByCustomerId, long invitedCustomerId,
                            PotRole role, Instant invitedAt) {
        return new PotInvitation(sharedPotId, invitedByCustomerId, invitedCustomerId, role, invitedAt);
    }

    /**
     * Closes the invitation, one way or another, at the moment it stopped waiting.
     *
     * <p>It does not check that it was waiting. Whether this invitation may be answered at all is a
     * rule about who is asking and what has already happened to it, and it is
     * {@link SharedPotsService}'s to keep — a row that policed itself would be a second place the
     * rule lived, with nothing keeping the two agreed.
     */
    void answeredAs(InvitationState answer, Instant answeredAt) {
        this.state = answer;
        this.answeredAt = answeredAt;
    }

    Long getId() {
        return id;
    }

    long getSharedPotId() {
        return sharedPotId;
    }

    long getInvitedByCustomerId() {
        return invitedByCustomerId;
    }

    long getInvitedCustomerId() {
        return invitedCustomerId;
    }

    PotRole getRole() {
        return role;
    }

    InvitationState getState() {
        return state;
    }

    Instant getInvitedAt() {
        return invitedAt;
    }

    Instant getAnsweredAt() {
        return answeredAt;
    }
}
