package io.dataroots.savingstreak.sharedpots;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One customer's belonging to one shared pot: which pot, which customer, what they are to it, and
 * when they joined.
 *
 * <p>A row rather than a list of identifiers on the pot, because belonging is a thing that happens
 * and then changes. A role is promoted and demoted, a member leaves and is settled, and the pot's
 * history has to go on reading correctly afterwards — none of which a column on the pot could say.
 *
 * <p>The customer is an identifier and not a relation, the way every other module's reference to a
 * customer is: this module keeps no handle on {@code Customer}, asks Accounts what somebody is
 * called when it has to name them, and is therefore never a second place where a renamed customer
 * has an old name.
 *
 * <p>The role is stored as its word rather than as its position, so that a value added to
 * {@link PotRole} cannot silently change what every existing row means.
 *
 * <p>One membership per customer per pot, which is a rule the database keeps rather than one this
 * module merely intends: {@link SharedPotsOnStartUp} makes the index that says so, and without it
 * two invitations accepted at the same moment would be two roles for one person with nothing to say
 * which of them is theirs.
 *
 * <p>Package-private, like the repository that reads it. {@link APotMember} is what leaves.
 */
@Entity
class PotMembership {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long sharedPotId;

    private long customerId;

    @Enumerated(EnumType.STRING)
    private PotRole role;

    /**
     * When they became a member, off the application's clock. For the pot that opened a moment ago
     * this is the moment the pot itself was opened, because its owner has belonged to it since it
     * existed — there has never been a pot with nobody allowed to administer it.
     */
    private Instant joinedAt;

    protected PotMembership() {
        // for JPA
    }

    private PotMembership(long sharedPotId, long customerId, PotRole role, Instant joinedAt) {
        this.sharedPotId = sharedPotId;
        this.customerId = customerId;
        this.role = role;
        this.joinedAt = joinedAt;
    }

    static PotMembership of(long sharedPotId, long customerId, PotRole role, Instant joinedAt) {
        return new PotMembership(sharedPotId, customerId, role, joinedAt);
    }

    long getSharedPotId() {
        return sharedPotId;
    }

    long getCustomerId() {
        return customerId;
    }

    PotRole getRole() {
        return role;
    }

    Instant getJoinedAt() {
        return joinedAt;
    }

    /**
     * Changes what this member is to the pot, leaving everything else about their belonging to it
     * exactly as it was.
     *
     * <p>The same row rather than a new one, because it is the same membership: they have belonged
     * to this pot since the moment they joined it, and a promotion is not a second joining. The
     * moment is deliberately untouched — it is what orders the list of members, and a change that
     * quietly reset it would make the person who was promoted read as the person who joined last.
     *
     * <p>A method on the membership rather than a setter, for the reason every other entity in this
     * application has one: the row is changed by something that can be named, and the name says what
     * happened to it.
     */
    void holdsInstead(PotRole role) {
        this.role = role;
    }
}
