package io.dataroots.savingstreak.sharedpots;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * A savings pot that belongs to a group of customers rather than to one of them: a name somebody
 * chose, the savings account the euros live in, and the moment it was opened.
 *
 * <p>It holds no money and no members. The euros are the deposits module's record exactly as they
 * already are — a pot's savings account is a savings account, and what is in it is the sum of what
 * the deposits into it still hold — and who belongs to the pot is a row per member in
 * {@link PotMembership}, because membership is a thing that starts, changes role and ends, and a
 * list of identifiers on this row could say none of that.
 *
 * <p><strong>The pot points at its savings account, and never the other way round.</strong> An
 * account that named its pot would make the Accounts module aware that shared pots exist, which is
 * exactly the dependency this arrangement is here to avoid: Accounts knows that a savings account
 * may be held by nobody, and it does not know why. The identifier is a plain column for the same
 * reason every other module's is — this module has no handle on {@code SavingsAccount} and wants
 * none, and whether the account exists was settled by the service that opened it.
 *
 * <p>One account per pot, made with it. Several would buy nothing here and would multiply every
 * question this feature has to answer about the money — whose euros left, which account a proposal
 * is about, what a settlement pays back out of.
 *
 * <p>Nothing on this row says who opened the pot, and that is deliberate: the opener is its first
 * owner, ownership can be passed on, and a column recording who it once belonged to would be a
 * second answer to "whose pot is this" that nothing keeps true.
 *
 * <p>The moment comes off the application's clock rather than the machine's, so a pot opened against
 * a wound-forward clock is dated where the trainer wound it to.
 *
 * <p>Package-private, like the repository that reads it: a row of this module's record is not
 * something another module gets a handle on. {@link ASharedPot} is what leaves.
 */
@Entity
class SharedPot {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * What the people saving into it call it — "Kitchen", "Greece 2027" — stored trimmed and
     * otherwise exactly as it was typed, the way a customer's name and a goal's name are.
     */
    private String name;

    /** The savings account the pot's euros live in, which is held by nobody and opened with it. */
    private long savingsAccountId;

    private Instant openedAt;

    /**
     * When an owner closed the pot, and null for as long as it is open.
     *
     * <p><strong>A moment rather than a state, which is the opposite of what a proposal and an
     * invitation carry — and the difference is that there is only one way for a pot to end.</strong>
     * {@link ProposalState} exists because a proposal can finish approved, rejected or taken back,
     * and a page shows the three differently; a pot is closed by an owner and by nothing else, so a
     * state enum here would be a vocabulary with one word in it and a second answer to "is it
     * closed" that nothing keeps agreed with the column beside it. A goal draws the same line the
     * other way for the same reason: it has two ways to end and so it carries a state.
     *
     * <p>And the moment is worth keeping rather than a flag, because a closed pot is a record. "When
     * did we finish with the kitchen" is a question the pot's history is read for, and a boolean
     * would be the one fact about the ending that the ending did not keep.
     *
     * <p>It comes off the application's clock like every other moment this module writes, so a pot
     * closed against a wound-forward clock is dated where the trainer wound it to.
     */
    private Instant closedAt;

    protected SharedPot() {
        // for JPA
    }

    private SharedPot(String name, long savingsAccountId, Instant openedAt) {
        this.name = name;
        this.savingsAccountId = savingsAccountId;
        this.openedAt = openedAt;
    }

    /** A pot about to be opened, with the account that will hold its money already made. */
    static SharedPot of(String name, long savingsAccountId, Instant openedAt) {
        return new SharedPot(name, savingsAccountId, openedAt);
    }

    Long getId() {
        return id;
    }

    String getName() {
        return name;
    }

    long getSavingsAccountId() {
        return savingsAccountId;
    }

    Instant getOpenedAt() {
        return openedAt;
    }

    Instant getClosedAt() {
        return closedAt;
    }

    /**
     * Whether the pot has been closed, which is the whole of what every rule in front of an action
     * on one asks.
     *
     * <p>Asked of the row rather than compared at the places that ask, the line
     * {@link ProposalState#isStillWaiting} draws: a dozen rules turn on it — paying in, inviting,
     * answering an invitation, changing a role, proposing, approving, leaving, closing again — and a
     * null check written at each of those would be one decision kept in a dozen places that could
     * quietly disagree.
     */
    boolean isClosed() {
        return closedAt != null;
    }

    /**
     * Closes the pot at the moment given, which is the one change this row ever undergoes.
     *
     * <p>There is no reopening, and there is deliberately no method for one. Closing returned every
     * member's euros to them and abandoned the goals the group was saving towards; a pot brought
     * back would be an empty pot with a history that says money left it, which is not the pot
     * anybody closed.
     */
    void closedAt(Instant closedAt) {
        this.closedAt = closedAt;
    }
}
