package io.dataroots.savingstreak.sharedpots;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One member asking the pot to let money out: which pot, who asked, how much, which of their own
 * current accounts it would go to, where the asking stands, and when it was made and closed.
 *
 * <p>A row of its own rather than a withdrawal that has not happened yet, and the distinction is the
 * whole point of the feature: a withdrawal is a movement of money recorded in the Deposits module,
 * and this is a question the members of a pot are being asked. Nothing moves when one is written.
 * Answering a proposal is what turns an approved one into a real withdrawal, and the two records
 * stay separate afterwards, because the pot's history has to go on showing that somebody asked and
 * what became of it.
 *
 * <p><strong>Who must approve it is deliberately not stored.</strong> It is worked out from who is
 * in the pot and whose money is still in it, which are both facts that move: a member who leaves and
 * is settled between the proposal and its last approval has nothing left at stake, and a list
 * written down at proposal time would go on demanding an answer from them. {@link
 * WhoseAssentAWithdrawalNeeds} is the rule, it is asked afresh every time the question is put, and
 * that is what lets the set be recomputed when the last approval lands exactly as the spec requires.
 *
 * <p>The customer and the current account are identifiers and not relations, the way every other
 * module's references are: this module keeps no handle on {@code Customer} or on an account, asks
 * Accounts what somebody is called when it has to name them, and is therefore never a second place
 * where a renamed customer has an old name.
 *
 * <p>The state is stored as its word rather than as its position, so that a value added to
 * {@link ProposalState} cannot silently change what every existing row means.
 *
 * <p>Package-private, like the repository that reads it. {@link AWithdrawalProposal} is what leaves.
 */
@Entity
class WithdrawalProposal {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long sharedPotId;

    /** The member who asked. Kept after it is closed, because the pot's record says who proposed it. */
    private long proposedByCustomerId;

    /**
     * How much they asked to take out, as they asked for it.
     *
     * <p>Checked against what the pot holds when the proposal is made and again when the last
     * approval lands, because a pot's balance moves underneath a proposal that is waiting: somebody
     * else's deposit can arrive and a settlement can take money away. Storing the figure rather than
     * a share of the balance is what makes both of those checks possible.
     */
    private BigDecimal amount;

    /**
     * The proposer's own current account the money would return to.
     *
     * <p>Theirs, and checked to be theirs when the proposal is made: a proposal naming somebody
     * else's account would be a way of moving a pot's money to a stranger with the other members'
     * blessing, and the members approving it are reading a sentence about an amount rather than
     * auditing an account number.
     */
    private long destinationCurrentAccountId;

    @Enumerated(EnumType.STRING)
    private ProposalState state;

    /** When it was made, off the application's clock rather than the machine's. */
    private Instant proposedAt;

    /** When it stopped waiting, whoever stopped it, and null for as long as it still is. */
    private Instant closedAt;

    protected WithdrawalProposal() {
        // for JPA
    }

    private WithdrawalProposal(long sharedPotId, long proposedByCustomerId, BigDecimal amount,
                               long destinationCurrentAccountId, Instant proposedAt) {
        this.sharedPotId = sharedPotId;
        this.proposedByCustomerId = proposedByCustomerId;
        this.amount = amount;
        this.destinationCurrentAccountId = destinationCurrentAccountId;
        this.state = ProposalState.PROPOSED;
        this.proposedAt = proposedAt;
    }

    /**
     * A proposal about to be made. It starts {@link ProposalState#PROPOSED} and can start nowhere
     * else: a proposal nobody has answered is the only kind there is to make, and one that could be
     * born approved would be a withdrawal with the gate painted on.
     */
    static WithdrawalProposal of(long sharedPotId, long proposedByCustomerId, BigDecimal amount,
                                 long destinationCurrentAccountId, Instant proposedAt) {
        return new WithdrawalProposal(sharedPotId, proposedByCustomerId, amount,
                destinationCurrentAccountId, proposedAt);
    }

    /**
     * Closes the proposal, one way or another, at the moment it stopped waiting.
     *
     * <p>It does not check that it was waiting, nor who is closing it. Whether this proposal may be
     * answered at all, and by whom, is a rule about the pot's membership and about what has already
     * happened to it, and it is {@link SharedPotsService}'s to keep — a row that policed itself
     * would be a second place the rule lived, with nothing keeping the two agreed. The same line
     * {@link PotInvitation} draws.
     */
    void closedAs(ProposalState closing, Instant closedAt) {
        this.state = closing;
        this.closedAt = closedAt;
    }

    Long getId() {
        return id;
    }

    long getSharedPotId() {
        return sharedPotId;
    }

    long getProposedByCustomerId() {
        return proposedByCustomerId;
    }

    BigDecimal getAmount() {
        return amount;
    }

    long getDestinationCurrentAccountId() {
        return destinationCurrentAccountId;
    }

    ProposalState getState() {
        return state;
    }

    Instant getProposedAt() {
        return proposedAt;
    }

    Instant getClosedAt() {
        return closedAt;
    }
}
