package io.dataroots.savingstreak.sharedpots;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One member's answer to one proposal: which proposal, who answered, which way, and when.
 *
 * <p><strong>A row rather than a counter on the proposal.</strong> A count of approvals could say
 * that three people had agreed; it could not say which three, and every rule this slice has is about
 * <em>which</em>. Whether this member may answer at all is read off whether their money is still in
 * the pot; whether they have answered already is read off whether one of these exists; and whose
 * assent is still outstanding is the members who must answer less the members who have. A number
 * would answer none of those, and a proposal that had been approved by somebody who left and come
 * back would be indistinguishable from one approved twice.
 *
 * <p>It is also the record. Story 58 asks that a proposal show who has answered it, and a decision
 * that left no trace of who made it would be a vote counted in private.
 *
 * <p><strong>One answer per member per proposal</strong>, which is a rule the database keeps rather
 * than one this module merely intends: {@link SharedPotsOnStartUp} makes the index that says so, for
 * the reason it makes the one on memberships. Without it, two approvals arriving together would both
 * be written, the second one counting somebody's assent twice — and the withdrawal would go through
 * on an approval that one member gave and one member never did.
 *
 * <p>The customer is an identifier and not a relation, the way every other reference in this module
 * is: names are asked of Accounts when somebody has to be named, so a renamed customer is renamed
 * everywhere at once.
 *
 * <p>The proposal is an identifier for the same reason, and the pot is deliberately not on this row
 * at all: a proposal belongs to exactly one pot, and a second copy of that fact is a second place it
 * could be wrong.
 *
 * <p>Package-private, like the repository that reads it. {@link AnAnswerToAProposal} is what leaves.
 */
@Entity
class WithdrawalProposalAnswer {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long withdrawalProposalId;

    /** The member who answered. Kept after they leave the pot, because the record says who decided. */
    private long customerId;

    @Enumerated(EnumType.STRING)
    private ProposalAnswer answer;

    /** When they answered, off the application's clock rather than the machine's. */
    private Instant answeredAt;

    protected WithdrawalProposalAnswer() {
        // for JPA
    }

    private WithdrawalProposalAnswer(long withdrawalProposalId, long customerId,
                                     ProposalAnswer answer, Instant answeredAt) {
        this.withdrawalProposalId = withdrawalProposalId;
        this.customerId = customerId;
        this.answer = answer;
        this.answeredAt = answeredAt;
    }

    static WithdrawalProposalAnswer of(long withdrawalProposalId, long customerId,
                                       ProposalAnswer answer, Instant answeredAt) {
        return new WithdrawalProposalAnswer(withdrawalProposalId, customerId, answer, answeredAt);
    }

    long getWithdrawalProposalId() {
        return withdrawalProposalId;
    }

    long getCustomerId() {
        return customerId;
    }

    ProposalAnswer getAnswer() {
        return answer;
    }

    Instant getAnsweredAt() {
        return answeredAt;
    }
}
