package io.dataroots.savingstreak.deposits;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One movement of money out of a current account and into a savings account, and how much of it is
 * still sitting there.
 *
 * <p>The two accounts are held by identifier rather than by association: they belong to the Accounts
 * module, and a deposit only needs to name them. Neither is written to from here — the money comes
 * out of the current account by asking Accounts to take it, and the savings account's balance is
 * derived from the deposits made into it rather than kept anywhere.
 *
 * <p>What was put in is written once and never again — a deposit's amount is what happened, and what
 * it earned was decided from it. What remains starts out as the whole of it and is the figure the
 * savings account's balance is summed from, so that money leaving the account reduces the deposits it
 * came out of rather than being subtracted from a total that no longer agrees with them. The two
 * figures are identical until something can take money back out, which is the whole reason for
 * keeping them apart: the day a withdrawal draws a deposit down, "how much of this deposit is still
 * here" is a question about that deposit, and a balance cannot answer it.
 *
 * <p>Package-private, like the repository: what the Deposits module records, and how, is nobody
 * else's business.
 */
@Entity
class Deposit {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long savingsAccountId;

    /**
     * Whose saving this is.
     *
     * <p>Written down rather than looked up through the account, because it is what a week and a run
     * of weeks are counted by: both are the customer's, so both are one query over the deposits this
     * column names rather than a query per account they hold. Which account the money went into is
     * the column above, and it is still what a balance and a history are read by.
     *
     * <p>Nullable in the database only because a deposit recorded before a week belonged to a
     * customer has no value in it. {@link DepositsOnStartUp} fills those in before the application
     * serves a single request, so nothing that reads this ever sees a null.
     */
    private Long customerId;

    private long sourceCurrentAccountId;

    private BigDecimal amount;

    /**
     * How much of the amount is still in the savings account.
     *
     * <p>Nullable in the database only because a deposit recorded before this column existed has no
     * value in it. {@link DepositsOnStartUp} fills those in before the application serves a single
     * request, so nothing that reads this ever sees a null.
     */
    private BigDecimal remainingAmount;

    /**
     * The rate this deposit was paid at, per whole euro.
     *
     * <p>History, and the reason it is written down rather than derived. What a run of weeks pays is
     * worked out from the ledger every time it is asked for, so that a movable clock cannot leave a
     * counter behind describing a week that is now in the future — but what a deposit <em>was</em>
     * paid must not move when the ladder changes or when the run it was paid on lapses. The
     * derivation answers "what is my rate"; this answers "what was this deposit paid".
     *
     * <p>Written a moment after the row is inserted rather than in the constructor, because the rate
     * is the rate of the run that includes this deposit and the run cannot be walked until the
     * deposit is in the ledger to be walked over.
     *
     * <p>Nullable in the database only because a deposit recorded before this column existed has no
     * value in it. Those were all paid at the ordinary rate, which is what
     * {@link DepositsService#depositsInto} reports for them — nothing is backfilled, because nothing
     * sums this column and a null read as the ordinary rate is the same answer a backfill would
     * write.
     */
    private BigDecimal multiplierApplied;

    private Instant depositedAt;

    protected Deposit() {
        // for JPA
    }

    Deposit(long savingsAccountId, long customerId, long sourceCurrentAccountId, BigDecimal amount,
            Instant depositedAt) {
        this.savingsAccountId = savingsAccountId;
        this.customerId = customerId;
        this.sourceCurrentAccountId = sourceCurrentAccountId;
        this.amount = amount;
        // All of it, because none of it has gone anywhere yet.
        this.remainingAmount = amount;
        this.depositedAt = depositedAt;
    }

    Long getId() {
        return id;
    }

    /** Which savings account the money landed in, which is what a ledger of one is assembled by. */
    long getSavingsAccountId() {
        return savingsAccountId;
    }

    /** The everyday account it came out of, which is the other end of the movement. */
    long getSourceCurrentAccountId() {
        return sourceCurrentAccountId;
    }

    BigDecimal getAmount() {
        return amount;
    }

    BigDecimal getRemainingAmount() {
        return remainingAmount;
    }

    /** Records money leaving this deposit, never allowing more to leave than remains. */
    void reduceBy(BigDecimal amount) {
        if (remainingAmount.compareTo(amount) < 0) {
            throw new IllegalArgumentException("cannot reduce a deposit by more than remains");
        }
        remainingAmount = remainingAmount.subtract(amount);
    }

    /**
     * Records the rate this deposit was paid at, once and never again — a deposit's reward cannot
     * change after the fact.
     *
     * @throws IllegalStateException if this deposit has already been priced, which would be a second
     *                               answer to a question that has one
     */
    void paidAt(BigDecimal multiplier) {
        if (multiplierApplied != null) {
            throw new IllegalStateException("deposit " + id + " was already paid at "
                    + multiplierApplied + " and cannot be repriced at " + multiplier);
        }
        multiplierApplied = multiplier;
    }

    /** The rate it was paid at, or nothing at all for a deposit recorded before the column existed. */
    BigDecimal getMultiplierApplied() {
        return multiplierApplied;
    }

    Instant getDepositedAt() {
        return depositedAt;
    }
}
