package io.dataroots.savingstreak.deposits;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One movement of money out of a current account and into a savings account.
 *
 * <p>The two accounts are held by identifier rather than by association: they belong to the Accounts
 * module, and a deposit only needs to name them. Neither is written to from here — the money comes
 * out of the current account by asking Accounts to take it, and the savings account's balance is
 * derived from the deposits made into it rather than kept anywhere.
 *
 * <p>Package-private, like the repository: what the Deposits module records, and how, is nobody
 * else's business.
 */
@Entity
class Deposit {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long savingsAccountId;

    private long sourceCurrentAccountId;

    private BigDecimal amount;

    private Instant depositedAt;

    protected Deposit() {
        // for JPA
    }

    Deposit(long savingsAccountId, long sourceCurrentAccountId, BigDecimal amount, Instant depositedAt) {
        this.savingsAccountId = savingsAccountId;
        this.sourceCurrentAccountId = sourceCurrentAccountId;
        this.amount = amount;
        this.depositedAt = depositedAt;
    }

    Long getId() {
        return id;
    }

    BigDecimal getAmount() {
        return amount;
    }

    Instant getDepositedAt() {
        return depositedAt;
    }
}
