package io.dataroots.savingstreak.gifting;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One gift of points from one customer to another: who gave, who received, how many points, and the
 * moment it happened off the application's clock.
 *
 * <p>One row, not two. Nothing is written on the sender's side beyond the decrement their batches
 * already take: this row <em>is</em> the outgoing record, and which direction it reads in is a
 * property of who is looking at it rather than of the data — the same idiom the money-movement
 * ledger set with its own direction.
 *
 * <p>It outlives the points. A gift stays in both customers' lists after the points have been spent,
 * given onward or expired, because what somebody did is not undone by what later happened to the
 * points they did it with. That is also why the figure is written down rather than derived: the
 * batches it created are gone by then.
 *
 * <p>Deriving the same list out of the points ledger was rejected for the reason the loyalty record
 * was: it would need Points to say out loud which batches came from where and who held them before,
 * which is precisely the question that module refuses. A counter on the customer was rejected
 * because it discards the counterparty and the moment.
 *
 * <p>There is nothing else on it and that is deliberate — no message, no occasion, no acceptance, no
 * reversal. A gift is final the moment it is made.
 *
 * <p>It is also everything a limit would need to be written against after the fact. There is no cap,
 * cooldown or daily total in this feature and that absence was asked for explicitly; should one ever
 * be wanted, these rows are the history it could be applied to.
 *
 * <p>Package-private, like the repository: what the Gifting module records, and how, is nobody
 * else's business.
 */
@Entity
class Gift {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Whose pot the points came out of. */
    private long senderCustomerId;

    /** Whose pot they arrived in, from the moment the gift went through. */
    private long recipientCustomerId;

    /**
     * How many points changed hands, which is exactly what left the sender and exactly what reached
     * the recipient. Nothing is created, skimmed or destroyed on the way: there is no fee, no tax
     * and no spread on a gift.
     */
    private long points;

    /**
     * The moment it happened, read off the application's clock rather than the machine's, so that a
     * gift made against a wound-forward clock is dated where the trainer wound it to.
     *
     * <p>Not the moment the points were earned. The batches that arrive in the recipient's pot carry
     * that, and they carry the sender's dates rather than this one — which is the whole of why a
     * chain of gifts cannot keep points alive past their twelve months.
     */
    private Instant givenAt;

    protected Gift() {
        // for JPA
    }

    private Gift(long senderCustomerId, long recipientCustomerId, long points, Instant givenAt) {
        this.senderCustomerId = senderCustomerId;
        this.recipientCustomerId = recipientCustomerId;
        this.points = points;
        this.givenAt = givenAt;
    }

    /**
     * A gift about to be made, with everything that decided it.
     *
     * <p>Written before the points move, because the batches arriving in the recipient's pot
     * reference this row and cannot be written without its identifier. {@link GiftingService#give}
     * says why that is the opposite order to a reward claim's and what makes it safe.
     */
    static Gift of(long senderCustomerId, long recipientCustomerId, long points, Instant givenAt) {
        return new Gift(senderCustomerId, recipientCustomerId, points, givenAt);
    }

    Long getId() {
        return id;
    }

    long getSenderCustomerId() {
        return senderCustomerId;
    }

    long getRecipientCustomerId() {
        return recipientCustomerId;
    }

    long getPoints() {
        return points;
    }

    Instant getGivenAt() {
        return givenAt;
    }
}
