package io.dataroots.savingstreak.automation;

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Where one firing's money actually went: this occurrence put that much into that goal.
 *
 * <p>One row per goal that took something, written the night the rule fired and never rewritten,
 * for the reason {@link RuleOccurrence} is never rewritten: what a rule did on a day is what it did,
 * and a later change to the rule — a share re-worded, a goal abandoned, a target raised — changes
 * what it does next rather than what it did.
 *
 * <p><strong>This is what makes "where did my money go" answerable, and it cannot be derived.</strong>
 * The rule's split says what was <em>offered</em>. What each goal took depends on what it still
 * needed on the night, which is a figure nothing writes down: a reader redoing the percentages
 * against the rule and the goals as they read today would get a different answer from the one the
 * money actually took, and would get a different one again next week.
 *
 * <p>No row for a goal that took nothing. Nothing moved and the goals ledger holds nothing either,
 * so a 0.00 here would be a claim that a movement happened. What the split could not place is one
 * figure on the occurrence itself.
 *
 * <p>The goal is an identifier and not a relation, exactly as everywhere else in this module: the
 * edge points outward to Goals and nothing points back.
 *
 * <p>Package-private, like every row in this module. {@link WhatAGoalGot} is what leaves.
 */
@Entity
class OccurrenceAllocation {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The firing this happened on. Every read of these is scoped by it, without exception. */
    private long ruleOccurrenceId;

    /** The goal that took it. */
    private long goalId;

    /** What it took, quoted to the cent — never nothing, because a goal that took nothing has no row. */
    private BigDecimal amount;

    /**
     * Where the goal sat in the rule's split when the money moved, from zero.
     *
     * <p>Stored rather than looked up, so that the history reads in the order the money was offered
     * even after the rule's split has been re-worded — and so that the two goals of a split that
     * both took something come back in the order the customer wrote them rather than in whatever
     * order the rows were fetched.
     */
    @Column(name = "spot_in_the_split")
    private int spot;

    protected OccurrenceAllocation() {
        // for JPA
    }

    OccurrenceAllocation(long ruleOccurrenceId, long goalId, BigDecimal amount, int spot) {
        this.ruleOccurrenceId = ruleOccurrenceId;
        this.goalId = goalId;
        this.amount = amount;
        this.spot = spot;
    }

    long getRuleOccurrenceId() {
        return ruleOccurrenceId;
    }

    long getGoalId() {
        return goalId;
    }

    BigDecimal getAmount() {
        return amount;
    }

    int getSpot() {
        return spot;
    }
}
