package io.dataroots.savingstreak.automation;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One goal's share of what a rule moves: this rule, that goal, that many whole percent, in the place
 * the customer wrote it.
 *
 * <p>A row per share rather than a column on the rule, because a split is a list and a list in a
 * column is a list nothing can query, order or check. The shares on one rule add to a hundred, which
 * is a rule about the whole list and is settled in {@link AutomationService} before any of these are
 * written.
 *
 * <p><strong>The goal is an identifier and not a relation</strong>, exactly as the two accounts on
 * {@link SavingRule} are. The edge points from this module to Goals and never back, and a foreign key
 * would be this module's schema knowing about another module's rows — and would also make a goal
 * undeletable by a module that has never heard of saving rules.
 *
 * <p><strong>A goal that is abandoned after the split was written keeps its row.</strong> It is what
 * the customer said, and what the customer said is the record: the firing offers the share to the
 * goal anyway, finds it is no longer live, and spills it to the next goal in the split. Deleting the
 * row on the customer's behalf would quietly re-word their instruction.
 *
 * <p>Package-private, like the rule it belongs to and like every row in this module.
 * {@link AShareOfWhatMoves} is what leaves.
 */
@Entity
class RuleSplit {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The rule this share belongs to. Every read of a split is scoped by it, without exception. */
    private long savingRuleId;

    /** The goal the share is offered to, which was live on the account when the split was written. */
    private long goalId;

    /**
     * How much of what the rule moves this goal is offered, as a whole percentage of it.
     *
     * <p>Under a column name of its own because {@code share} is a reserved word in more than one
     * SQL dialect: SQLite would take it today, and a column named after a keyword is one dialect
     * upgrade away from a start-up that does not parse. The Java side keeps the word the customer
     * uses — the same trade {@code SavingsGoal} makes for {@code goal_rank}.
     */
    @Column(name = "share_of_what_moves")
    private int share;

    /**
     * Where it sits in the split, from zero, which is the order the customer wrote the shares in.
     *
     * <p>Load-bearing twice over and stored rather than inferred for exactly that reason. It is how
     * a leftover cent is settled when two shares are owed the same fraction of one, and it is the
     * order a share a goal will not take spills along. A list whose order came from whatever the
     * database happened to return would make both of those answers different from one firing to the
     * next.
     */
    @Column(name = "spot_in_the_split")
    private int spot;

    protected RuleSplit() {
        // for JPA
    }

    RuleSplit(long savingRuleId, long goalId, int share, int spot) {
        this.savingRuleId = savingRuleId;
        this.goalId = goalId;
        this.share = share;
        this.spot = spot;
    }

    Long getId() {
        return id;
    }

    long getSavingRuleId() {
        return savingRuleId;
    }

    long getGoalId() {
        return goalId;
    }

    int getShare() {
        return share;
    }

    int getSpot() {
        return spot;
    }
}
