package io.dataroots.savingstreak.automation;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One stretch of time a customer stopped a rule for: the moment the pause began, and the moment it
 * ended.
 *
 * <p><strong>This row is how the application tells a pause from downtime</strong>, which is the one
 * real idea in this feature. Both look the same from the occurrences: days a rule was due on and did
 * not fire. Downtime is the application's fault and is always caught up; a pause is the customer's
 * instruction and is honoured, and resuming a rule paused for two months must not hand its holder a
 * lump sum they never asked for. Nothing about a rule's state a fortnight later can answer which of
 * the two a given day fell in — only a record of when each pause began and ended can, and this is it.
 *
 * <p><strong>A row per pause rather than a pair of columns on the rule.</strong> A customer may
 * pause, resume, and pause again, and a single remembered window would forget every window but the
 * last — which matters because the days inside an older one can still be offered to the run
 * afterwards. A payday rule is where that actually happens: its days come out of the record of
 * salaries actually credited, and a salary credited <em>late</em>, after a resume, for a day that
 * fell <em>inside</em> the pause, arrives at the run with nothing about the cursor to exclude it.
 * Every window this rule has ever had is asked, so that day is excluded whichever pause it fell in.
 *
 * <p><strong>The window is open at the bottom and closed at the top</strong>, which is the boundary
 * a rule's cursor already uses: a day is inside the pause when it <em>begins</em> strictly after the
 * moment the customer paused, and at or before the moment they resumed. A day that had already begun
 * when they pressed pause is a day the pause did not cover, in the same way a day that had already
 * begun when they wrote the rule is a day the rule did not exist for.
 *
 * <p>{@code endedAt} is null while the pause is still on. A rule in that state is not in the set the
 * nightly run walks at all, so the open window is not what stops it firing — it is what lets the
 * resume say how many occurrences were passed over, and what keeps the record honest if the
 * application is read while a customer is still paused.
 *
 * <p>Package-private, like every row in this module. What leaves is the rule's state and the moment
 * it was paused, on {@link RecordedSavingRule}.
 */
@Entity
class RulePause {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The rule that was stopped. Every read of a pause is scoped by it, without exception. */
    private long savingRuleId;

    /** The moment the customer paused it, off the application's clock. */
    private Instant begunAt;

    /** The moment they resumed it, and null while the pause is still on. */
    private Instant endedAt;

    protected RulePause() {
        // for JPA
    }

    RulePause(long savingRuleId, Instant begunAt) {
        this.savingRuleId = savingRuleId;
        this.begunAt = begunAt;
    }

    Long getId() {
        return id;
    }

    long getSavingRuleId() {
        return savingRuleId;
    }

    Instant getBegunAt() {
        return begunAt;
    }

    Instant getEndedAt() {
        return endedAt;
    }

    /** Whether the customer has not resumed the rule yet. */
    boolean isStillOn() {
        return endedAt == null;
    }

    /**
     * Ends the pause at the given moment, and answers whether that moment is the one it now carries.
     *
     * <p>The row decides, so nothing outside can end one twice: a pause already ended answers
     * {@code false} and keeps the moment it was originally ended with. It is the shape
     * {@link SavingRule#end} has, for the same reason — a record that could be rewritten afterwards
     * is not a record.
     */
    boolean ended(Instant moment) {
        if (endedAt != null) {
            return false;
        }
        endedAt = moment;
        return true;
    }

    /**
     * Whether a day that begins at this moment fell inside this pause.
     *
     * <p>Open at the bottom and closed at the top, for the reason given above. A pause that is still
     * on covers everything after it began, which is the honest answer while nobody has resumed it.
     *
     * <p>A row written before this column existed cannot exist — a pause is only ever written with
     * the moment it began — but a null is answered as "covers nothing" rather than thrown over, so
     * that one unreadable row cannot abort a night for every other rule.
     */
    boolean covers(Instant theMomentADayBegins) {
        if (begunAt == null) {
            return false;
        }
        return theMomentADayBegins.isAfter(begunAt)
                && (endedAt == null || !theMomentADayBegins.isAfter(endedAt));
    }
}
