package io.dataroots.savingstreak.automation;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One day a saving rule fell due, and what became of it: which rule, the day it was due, the moment
 * it was actually dealt with, how it went, what moved, what it was short if it could not be
 * honoured, and the deposit that moved it.
 *
 * <p><strong>One row per rule per day due, unique over the pair, and that uniqueness is the
 * idempotency.</strong> A trainer runs the nightly job by hand, twice, and a demonstration that
 * doubled every figure in it would be worse than no demonstration. The rule's cursor also keeps a
 * second run from finding anything due — but the check and the guarantee are different things. Two
 * runs at the same moment would both read the same cursor and the same empty set of settled days,
 * and only a rule the database keeps stops both of them from depositing. On this table that is
 * money, not points. It is the same bargain {@code IncomePaid} and {@code LoyaltyBonusPaid} strike.
 *
 * <p>The uniqueness is not declared here, and that is not an oversight. The schema is generated from
 * the entity model ({@code ddl-auto=update}) against SQLite, whose dialect writes a composite unique
 * clause nowhere: declared as {@code @UniqueConstraint} — or as a {@code @Index} marked unique,
 * which Hibernate turns into one — the table is created without it and the only statement that
 * reaches the database is an {@code alter table ... drop constraint} that does nothing. So
 * {@link AutomationOnStartUp} creates the index itself, in a statement SQLite does accept, before
 * the application serves anything.
 *
 * <p><strong>The record is written whether money moved or not</strong>, and that is why this table
 * exists beside the deposits ledger rather than being derived from it. An occurrence that found an
 * empty account is as much a part of the history as one that moved a hundred euros, and a ledger of
 * movements has no row for a movement that did not happen.
 *
 * <p>Both moments are kept because they are different facts. {@code dueOn} is the day the rule was
 * supposed to move on and is half the key; {@code settledAt} is when the application got round to
 * it, which on a wound clock or after downtime is a different day — and the gap between them is the
 * lateness. The money is dated at the moment it actually moved rather than back-dated to the day it
 * was due: {@code DepositsService} prices points off the streak run as it stands when a deposit is
 * counted, so a deposit inserted five months ago would mis-price every manual deposit made after it.
 *
 * <p>Never rewritten. What a rule did on a day is what it did, and a later change to the rule — its
 * figure, its day, its ending — changes what it does next rather than what it did.
 *
 * <p>Package-private, like the rule it belongs to and like every row in this module.
 * {@link RecordedOccurrence} is what leaves.
 */
@Entity
class RuleOccurrence {

    /** Two, like every other amount of money in this application. */
    private static final int DECIMAL_PLACES_IN_MONEY = 2;

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The rule this happened to, as an identifier rather than a relation — the same way this module
     * holds the two accounts, and for the same reason a history has to outlive what it is about: a
     * rule that has been ended keeps its occurrences, and they read exactly as they did.
     */
    private long savingRuleId;

    /**
     * The day the rule was due to move, and the other half of the key.
     *
     * <p>A day rather than a moment, because a day is what a trigger names: "every Monday", "the
     * 25th", "payday". It is also what makes the pair a key at all — two moments a night apart are
     * two different values, and "the twenty-fifth" is one.
     */
    private LocalDate dueOn;

    /** The moment the occurrence was actually dealt with, off the application's clock. */
    private Instant settledAt;

    /** How it went, written as its name so a row read with a SQLite client says what happened. */
    @Enumerated(EnumType.STRING)
    private OccurrenceOutcome outcome;

    /**
     * What actually moved — the whole amount on a rule that fired, and nothing at all on one that
     * found nothing above its floor or could not be honoured.
     *
     * <p>What moved rather than what was asked for, because that is the figure a customer adds up
     * against their balance. What a rule that could not be honoured was short of is a different
     * figure and is {@link #shortfall}.
     */
    private BigDecimal amount;

    /**
     * How much more the account would have needed for this occurrence to be honoured, and null on
     * every occurrence that did not fail for want of money.
     *
     * <p>Only {@link OccurrenceOutcome#NOT_ENOUGH_MONEY} carries one, and the nullability is the
     * statement: nothing is short on an occurrence that moved its whole amount, and a sweep that
     * found nothing above its floor was not short of anything either — its figure was derived from
     * the balance and came out at nothing, which is arithmetic rather than a failure. Writing a
     * zero in those two rows would make "short of nothing" and "short of EUR 0,00" the same reading,
     * and the second is a sentence a page would have to draw.
     *
     * <p><strong>Stored rather than derived.</strong> It is the difference between what the rule
     * asked for on the day and what the account held on the day, and neither of those two survives:
     * the rule's amount is an instruction that can be changed the morning after, and a balance is
     * never written down anywhere at all. A history that worked the shortfall out from the rule as
     * it reads today would answer a different figure every time somebody edited the rule, which is
     * the one thing a record of what happened must not do.
     */
    private BigDecimal shortfall;

    /** The deposit this occurrence made, and null when it made none. */
    private Long depositId;

    protected RuleOccurrence() {
        // for JPA
    }

    private RuleOccurrence(long savingRuleId, LocalDate dueOn, Instant settledAt,
                           OccurrenceOutcome outcome, BigDecimal amount, BigDecimal shortfall,
                           Long depositId) {
        this.savingRuleId = savingRuleId;
        this.dueOn = dueOn;
        this.settledAt = settledAt;
        this.outcome = outcome;
        this.amount = amount;
        this.shortfall = shortfall;
        this.depositId = depositId;
    }

    /** An occurrence that moved money, naming the deposit it made. */
    static RuleOccurrence moved(long savingRuleId, LocalDate dueOn, Instant settledAt,
                                BigDecimal amount, long depositId) {
        return new RuleOccurrence(savingRuleId, dueOn, settledAt, OccurrenceOutcome.MOVED, amount,
                null, depositId);
    }

    /**
     * A sweep that found nothing above its floor. Recorded as fully as one that moved money — that
     * is the whole argument for this table — and carrying nothing as the amount, because nothing is
     * what moved, and no shortfall, because a sweep cannot be short of anything.
     */
    static RuleOccurrence nothingToMove(long savingRuleId, LocalDate dueOn, Instant settledAt) {
        return new RuleOccurrence(savingRuleId, dueOn, settledAt, OccurrenceOutcome.NOTHING_TO_MOVE,
                nothing(), null, null);
    }

    /**
     * A fixed amount the account could not cover, carrying what it was short.
     *
     * <p>Its own factory rather than an outcome handed to a shared one, so that the shortfall and
     * the outcome cannot be written apart: a {@code NOT_ENOUGH_MONEY} row with no figure on it, or a
     * {@code NOTHING_TO_MOVE} row claiming to have been short, are both rows this class simply has
     * no way to make.
     */
    static RuleOccurrence couldNotBeHonoured(long savingRuleId, LocalDate dueOn, Instant settledAt,
                                             BigDecimal shortfall) {
        return new RuleOccurrence(savingRuleId, dueOn, settledAt, OccurrenceOutcome.NOT_ENOUGH_MONEY,
                nothing(), shortfall, null);
    }

    /**
     * A day that fell due on a savings account that had been closed since the rule was left
     * standing.
     *
     * <p>Nothing as the amount, because nothing moved, and no shortfall, because the account the
     * money would have come out of was never the problem — a figure here would be the history
     * inviting somebody to top up an account that is already full enough. Its own factory for the
     * reason the shortfall has one: the outcome and the absence of a figure are written together
     * and cannot be written apart.
     */
    static RuleOccurrence intoAnAccountThatIsClosed(long savingRuleId, LocalDate dueOn,
                                                    Instant settledAt) {
        return new RuleOccurrence(savingRuleId, dueOn, settledAt,
                OccurrenceOutcome.THE_ACCOUNT_IS_CLOSED, nothing(), null, null);
    }

    /** Nothing, quoted to the cent, because what moved is money and is written as money. */
    private static BigDecimal nothing() {
        return BigDecimal.ZERO.setScale(DECIMAL_PLACES_IN_MONEY);
    }

    Long getId() {
        return id;
    }

    long getSavingRuleId() {
        return savingRuleId;
    }

    LocalDate getDueOn() {
        return dueOn;
    }

    Instant getSettledAt() {
        return settledAt;
    }

    OccurrenceOutcome getOutcome() {
        return outcome;
    }

    BigDecimal getAmount() {
        return amount;
    }

    BigDecimal getShortfall() {
        return shortfall;
    }

    Long getDepositId() {
        return depositId;
    }
}
