package io.dataroots.savingstreak.automation;

import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One instruction a customer has left standing: move money out of that current account into this
 * savings account, on these days, in this quantity.
 *
 * <p>It moves no money by itself and holds none. It is a sentence the customer said, and the job
 * that reads it is a later slice; everything here is about what the sentence is allowed to say.
 *
 * <p><strong>Both accounts are identifiers and not relations.</strong> Every module in this
 * application that belongs to an account holds it that way. Here it is load-bearing rather than
 * stylistic: this module has to be able to reach the modules that move money without any of them
 * reaching back, and a foreign key to {@code SavingsAccount} would be this module's schema knowing
 * about another module's rows. Whether either identifier names an account that exists, and whether
 * one customer holds both, is settled before a rule is ever written — see {@link AutomationService}.
 *
 * <p><strong>The day a rule moves on lives in whichever column its trigger needs, and in no
 * other.</strong> A weekly rule carries a day of the week and no day of the month; a monthly rule
 * the reverse; a rule that fires on payday carries neither, because its day is the one its holder
 * already declared as their income's and is read from there on demand. The same goes for the two
 * figures: a fixed-amount rule has an amount and no floor, a sweep a floor and no amount. Keeping
 * the unused column empty rather than merely ignoring it is what stops a rule changed from one kind
 * to the other going on carrying a figure that no longer means anything — and what makes a row
 * readable with a SQLite client without a key to it.
 *
 * <p>{@code endedAt} is a moment rather than a flag, set once, exactly as a goal's {@code
 * abandonedAt} is: a moment records when something happened, and one that could be overwritten would
 * record when it was last asked about.
 *
 * <p><strong>When it was paused is not here at all</strong>, and that is deliberate. A rule may be
 * stopped and started more than once, and every one of those windows goes on mattering after it has
 * closed — see {@link RulePause}, which is a row per pause for exactly that reason. What this row
 * carries is which of the three states it is in now.
 *
 * <p>Package-private, like the repository that reads it: a row of this module's record is not
 * something another module gets a handle on. {@link RecordedSavingRule} is what leaves.
 */
@Entity
class SavingRule {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The account the money lands in. Every read in this module is scoped by it, without exception. */
    private long savingsAccountId;

    /** The account the money is taken from, which its holder holds as well as the savings account. */
    private long currentAccountId;

    /** What the customer calls it, so that a list of three rules says what each of them is for. */
    private String name;

    /**
     * What makes it move, written as its name rather than as its position, so a row means the same
     * thing after a value is added to the enumeration and so a reviewer reading the table sees the
     * trigger rather than an ordinal to look up.
     *
     * <p>Under a column name of its own because {@code TRIGGER} is a reserved word in SQL and in
     * SQLite: a generated {@code create table} naming an unquoted column {@code trigger} does not
     * parse, and the application would fail to start rather than fail a test. The Java side keeps
     * the word, because the word is what the domain calls it — the same trade {@code SavingsGoal}
     * makes for {@code goal_rank}.
     */
    @Column(name = "what_makes_it_move")
    @Enumerated(EnumType.STRING)
    private RuleTrigger trigger;

    /** The day a {@link RuleTrigger#WEEKLY} rule moves on, and null on every other kind. */
    @Enumerated(EnumType.STRING)
    private DayOfWeek dayOfWeek;

    /**
     * The day a {@link RuleTrigger#MONTHLY} rule moves on, 1 to 31 as the customer said it, and null
     * on every other kind while it is standing.
     *
     * <p>Kept as the day that was said rather than as the day it will actually fall on, for the
     * reason a monthly income's is: they differ every February and the customer's answer is the 31st
     * all the same. Which day a short month lands it on is arithmetic made when the rule fires.
     *
     * <p><strong>An ended {@link RuleTrigger#ON_PAYDAY} rule carries a day here too</strong>, written
     * once by {@link #end}: the day it was actually moving on when it stopped. A standing payday rule
     * has none, because its day is its holder's declaration and is read from there on demand — but an
     * ended rule is a record, and a record that went on following a declaration would say a different
     * thing about last year every time the customer moved payday. See {@code AutomationService}.
     */
    private Integer dayOfMonth;

    /** Whether it moves a figure or a surplus, written as its name for the reason the trigger is. */
    @Enumerated(EnumType.STRING)
    private HowMuchMoves howMuchMoves;

    /** What an {@link HowMuchMoves#A_FIXED_AMOUNT} rule moves, and null on a sweep. */
    private BigDecimal amount;

    /**
     * The line an {@link HowMuchMoves#EVERYTHING_ABOVE} rule sweeps down to, and null on a fixed
     * amount.
     *
     * <p>Under a column name of its own for the same reason the trigger is under one: {@code floor}
     * is a scalar function in SQL, and while SQLite would accept it today, a column named after a
     * function is one dialect upgrade away from a start-up that does not parse. The Java side keeps
     * the word the customer uses.
     */
    @Column(name = "sweep_floor")
    private BigDecimal floor;

    @Enumerated(EnumType.STRING)
    private RuleState state;

    /** When it was left standing, off the application's clock so a wound clock dates it where it is. */
    private Instant createdAt;

    /** When it was ended, and null while it is still standing. */
    private Instant endedAt;

    /**
     * The moment through which this rule's occurrences have been settled — its cursor.
     *
     * <p><strong>It starts at the moment the rule was left standing, and that is what makes a new
     * rule not a bill for the past.</strong> Every day a trigger falls on is judged against this
     * moment: a day that had already begun when the customer wrote the rule is a day the rule did
     * not exist for, and firing it would be charging somebody for a week they had not asked to save
     * in. The same boundary stops one run's last occurrence being the next run's first.
     *
     * <p>Moved forward by the nightly run once everything it found due has been settled, and never
     * backwards — see {@link #settledThrough}. It is the twin of {@code MonthlyIncome}'s
     * {@code paidThrough} and exists for the same two reasons: it bounds the catch-up, so a clock
     * wound a century forward is walked from the rule's own creation rather than from the beginning
     * of time, and it is the cheap answer to "is there anything to do" on a night when there is not.
     *
     * <p>It is not, on its own, what makes the run idempotent. That is the record — one occurrence
     * per rule per day due, unique in the database — for the reason {@link RuleOccurrence} gives: a
     * cursor is a number this application writes, and a guarantee that money does not move twice
     * cannot rest on a number this application could rewrite.
     *
     * <p>Null only on a row written before this column existed. Nothing in this application writes
     * one, and the run reads such a row from its creation moment rather than throwing over it, so
     * that one old row cannot abort a night for every other rule.
     */
    private Instant settledThrough;

    protected SavingRule() {
        // for JPA
    }

    SavingRule(long savingsAccountId, long currentAccountId, String name, RuleTrigger trigger,
               DayOfWeek dayOfWeek, Integer dayOfMonth, HowMuchMoves howMuchMoves, BigDecimal amount,
               BigDecimal floor, Instant createdAt) {
        this.savingsAccountId = savingsAccountId;
        this.currentAccountId = currentAccountId;
        this.name = name;
        this.trigger = trigger;
        this.dayOfWeek = dayOfWeek;
        this.dayOfMonth = dayOfMonth;
        this.howMuchMoves = howMuchMoves;
        this.amount = amount;
        this.floor = floor;
        this.state = RuleState.LIVE;
        this.createdAt = createdAt;
        // A rule's occurrences are settled through the moment it was written, so the first day it
        // can ever fire on is one that begins after its holder said it. A cursor starting anywhere
        // earlier would make a rule left standing today a bill for last week.
        this.settledThrough = createdAt;
    }

    Long getId() {
        return id;
    }

    long getSavingsAccountId() {
        return savingsAccountId;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    String getName() {
        return name;
    }

    RuleTrigger getTrigger() {
        return trigger;
    }

    DayOfWeek getDayOfWeek() {
        return dayOfWeek;
    }

    Integer getDayOfMonth() {
        return dayOfMonth;
    }

    HowMuchMoves getHowMuchMoves() {
        return howMuchMoves;
    }

    BigDecimal getAmount() {
        return amount;
    }

    BigDecimal getFloor() {
        return floor;
    }

    RuleState getState() {
        return state;
    }

    Instant getCreatedAt() {
        return createdAt;
    }

    Instant getEndedAt() {
        return endedAt;
    }

    /**
     * The moment this rule's occurrences are settled through, or null on a row written before the
     * column existed. The caller decides what to do about the null, because only the caller knows
     * whether it is judging a rule or reporting one.
     */
    Instant getSettledThrough() {
        return settledThrough;
    }

    /**
     * Moves the cursor forward to the given moment, and never backwards.
     *
     * <p>Forward only, for the reason {@code MonthlyIncome} gives about its own: a cursor that could
     * go back would let an occurrence that has already fired fall due a second time, and on this
     * table that is money. Two runs in one night are the ordinary way it is asked to go back, and
     * the answer is that the later moment wins and the earlier one changes nothing.
     */
    void settledThrough(Instant moment) {
        if (settledThrough == null || moment.isAfter(settledThrough)) {
            settledThrough = moment;
        }
    }

    /**
     * Whether it has been ended for good, which is the one thing every change is refused for.
     *
     * <p>Asked of the state rather than compared against a value here, so that a fourth state has to
     * say what it means by it exactly once. {@link RuleState#isStillStanding} is where that is said,
     * and this is the only way a rule is asked it — there is deliberately no second method here
     * putting the same question the other way round.
     */
    boolean isEnded() {
        return !state.isStillStanding();
    }

    /** Whether the customer has stopped it for a while, which is the state it fires nothing in. */
    boolean isPaused() {
        return state == RuleState.PAUSED;
    }

    /**
     * Stops it at its holder's word, and answers whether that changed anything.
     *
     * <p>A rule already paused answers {@code false} and is left exactly as it was — pressing a
     * button twice is not a mistake worth a sentence, and re-stamping the pause would move the
     * moment it began and with it the window of occurrences that are never made up. An ended rule is
     * refused before this is ever called; it answers {@code false} here as well, so that nothing
     * outside can reopen one by accident.
     *
     * <p><strong>The cursor is deliberately left where it was.</strong> What a pause excludes is
     * written down as a window of its own ({@link RulePause}) rather than by moving the cursor
     * forward, because the cursor cannot say <em>why</em> it moved and the difference between a
     * pause and downtime is exactly that why.
     */
    boolean pause() {
        if (state != RuleState.LIVE) {
            return false;
        }
        state = RuleState.PAUSED;
        return true;
    }

    /**
     * Starts it again, and answers whether that changed anything.
     *
     * <p>A rule that was not paused answers {@code false} and is left exactly as it was, for the
     * reason pausing a paused rule is: a button pressed twice is not a mistake worth a sentence.
     *
     * <p><strong>The cursor is left where it was, and that is the whole of the ticket's other
     * half.</strong> What a rule paused for two months must not do is fire three times on the
     * morning it comes back, and the recorded window is what stops it: {@link RulePause#covers}
     * takes every day inside the pause out of the catch-up range outright, so none of them is ever
     * offered. Moving the cursor to the resume moment as well would stop the same three days a
     * second time and, in the same stroke, throw away the days that fell due <em>before</em> the
     * pause began and had not fired yet — downtime, which is the application's fault and is always
     * caught up. A customer who pauses on a Friday after a fortnight the job never ran would lose
     * that fortnight for pressing a button and pressing it again.
     *
     * <p>The application already argues this everywhere else it holds a cursor: a run that cannot
     * settle an occurrence leaves the cursor where it is rather than lose it, and a catch-up capped
     * at five hundred parks the cursor mid-way for the same reason. A pause is not a reason to
     * settle a rule through days nobody settled it through.
     *
     * <p>It is the window, then, that carries the difference between the two gaps, which is right:
     * a cursor cannot say <em>why</em> it moved, and why is the whole distinction. See
     * {@link RulePause}.
     */
    boolean resume() {
        if (state != RuleState.PAUSED) {
            return false;
        }
        state = RuleState.LIVE;
        return true;
    }

    /**
     * Says the rule differently, in one go.
     *
     * <p>All of it at once rather than a setter per field, because what a rule says is only legal as
     * a whole: a trigger without the day it needs, or a sweep still carrying the fixed amount it used
     * to move, is not a rule anybody could fire. Whether the new sentence is one this application
     * will keep is settled before this is called, and the caller is the only one that could settle
     * it — which is why there is no partial way in.
     */
    void nowSays(String name, RuleTrigger trigger, DayOfWeek dayOfWeek, Integer dayOfMonth,
                 HowMuchMoves howMuchMoves, BigDecimal amount, BigDecimal floor) {
        this.name = name;
        this.trigger = trigger;
        this.dayOfWeek = dayOfWeek;
        this.dayOfMonth = dayOfMonth;
        this.howMuchMoves = howMuchMoves;
        this.amount = amount;
        this.floor = floor;
    }

    /**
     * Ends it, as at the given moment and on the day it was moving on, and answers whether that
     * moment is the one it now carries.
     *
     * <p>The rule decides, so nothing outside can end one twice: one already ended answers
     * {@code false} and keeps the moment and the day it was originally ended with. It is the same
     * shape a goal's {@code abandon} has, and it exists for the same reason — a record that could be
     * rewritten afterwards is not a record.
     *
     * <p><strong>The day is written down here, and this is the only place a rule's day is settled by
     * anything other than its holder saying it.</strong> A payday rule's day is the day its holder's
     * declared income lands on at this moment, which until now was read afresh on every read — right
     * for an instruction waiting to fire, and wrong the instant the instruction becomes history.
     * Frozen rather than derived so that moving payday, or withdrawing the declaration altogether,
     * cannot make an ended rule claim it moved on a day it never moved on.
     *
     * <p><strong>And only a payday rule's.</strong> A weekly rule has no day of the month and a
     * monthly rule's is the one its holder typed; for those two the day already stored <em>is</em>
     * the record, so the value handed in is ignored rather than written back. Ignored rather than
     * trusted to be equal, because a caller that worked out the wrong day would otherwise rewrite a
     * monthly rule's own day as it closed, and the row that explains a year of deposits would be
     * quietly wrong with nothing to compare it against.
     *
     * @param theDayItWasMovingOn the day of the month a payday rule moved on as it stopped, or null
     *                            if nothing said when it moved — which is the honest record of a
     *                            payday rule ended by a holder who had declared no income. Ignored
     *                            for the other two triggers.
     */
    boolean end(Instant endedAt, Integer theDayItWasMovingOn) {
        if (this.state == RuleState.ENDED) {
            return false;
        }
        this.state = RuleState.ENDED;
        this.endedAt = endedAt;
        if (this.trigger == RuleTrigger.ON_PAYDAY) {
            this.dayOfMonth = theDayItWasMovingOn;
        }
        return true;
    }
}
