package io.dataroots.savingstreak.rewards;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One line of a bundle: an offer that is inside another offer, and how many of it go in.
 *
 * <p><strong>A table rather than a column, because a bundle is a list and a column is not
 * one.</strong> {@link RewardOffer} already says so in its own javadoc — "a bundle is a row with
 * member lines hanging off it, so it is a table rather than a column" — and this is that table.
 * The alternatives were a comma-separated string in a column, which is a list nobody can query
 * and a quantity nobody can add up, and a duplicated offer per bundle, which is the thing the
 * whole feature exists to stop somebody doing by hand.
 *
 * <p><strong>Codes rather than foreign keys, which is the same decision a claim already
 * makes.</strong> A claim names the offer it was made against by its code as text, because the
 * code is the offer's immutable natural key and a voucher has to stay readable after the offer
 * behind it has been withdrawn. A member line is the same kind of reference — the offer it names
 * is never deleted, never renamed and never re-coded — and pointing at the row's generated
 * identifier instead would buy referential integrity this application already has by
 * construction, at the price of a join on every read of a figure that is otherwise pure
 * arithmetic over codes. The stock arithmetic in {@link RewardsService} is keyed by code from end
 * to end, because {@code HowManyHaveGone} is grouped by code, and a line that spoke a
 * different language would have to be translated before it could be added up.
 *
 * <p><strong>A quantity of at least one, checked before this is written.</strong> Nought of
 * something is not a thing that is in a bundle, and a negative number of it would take stock back
 * out of the world every time somebody claimed. What the least a quantity may be is a rule about
 * the catalogue and is refused in {@link RewardsService} in a sentence somebody reads, exactly as
 * every other rule about what an offer may say is.
 *
 * <p><strong>Nothing here draws anything down.</strong> A line is a fact about the catalogue and
 * not a ledger: when a bundle is claimed, the claim row names the <em>bundle</em>, and how much of
 * each member that took is worked out by multiplying that bundle's claims by these quantities.
 * The argument for deriving it rather than writing a phantom claim per member is on
 * {@code RewardsService.whatIsLeftOf}, and it is the same argument the stock column already
 * makes: two stored figures that must agree eventually stop agreeing.
 *
 * <p>Package-private, like {@link RewardOffer} and the repository that reads it. What leaves this
 * module is {@link WhatABundleContains}.
 */
@Entity
class OfferMemberLine {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The code of the bundle this line belongs to. */
    @Column(nullable = false)
    private String bundleCode;

    /** The code of the offer that is inside it. Never a bundle itself: nesting is refused. */
    @Column(nullable = false)
    private String memberCode;

    /** How many of the member one of the bundle hands over. One or more, checked before writing. */
    @Column(nullable = false)
    private int quantity;

    protected OfferMemberLine() {
        // For JPA.
    }

    OfferMemberLine(String bundleCode, String memberCode, int quantity) {
        this.bundleCode = bundleCode;
        this.memberCode = memberCode;
        this.quantity = quantity;
    }

    String bundleCode() {
        return bundleCode;
    }

    String memberCode() {
        return memberCode;
    }

    int quantity() {
        return quantity;
    }
}
