package io.dataroots.savingstreak.rewards;

import java.security.SecureRandom;
import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One reward claimed by a savings account: what was taken, what it cost, the voucher that was issued
 * for it, and when.
 *
 * <p>The cost is written down rather than read back off the catalogue. What the reward costs today
 * and what this customer paid for theirs are two different facts, and the day a price changes is the
 * day reading one as the other would rewrite history — a claim from last month would silently start
 * saying it cost what the reward costs now.
 *
 * <p>Package-private, like the repository: what the Rewards module records, and how, is nobody
 * else's business.
 */
@Entity
class Redemption {

    /** No 0/O or 1/I: a voucher code gets read off a screen and typed in at a counter. */
    private static final String VOUCHER_ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ";

    private static final int VOUCHER_CHARACTERS = 6;

    private static final SecureRandom RANDOM = new SecureRandom();

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long savingsAccountId;

    @Enumerated(EnumType.STRING)
    private Reward reward;

    private long pointsSpent;

    /**
     * Unique, so that two vouchers can never be issued under one code. There is no retry behind it:
     * a collision across a billion codes is rarer than the database being unavailable, and a claim
     * that fails loudly is recoverable, while two customers holding the same voucher is not.
     */
    @Column(nullable = false, unique = true)
    private String voucherCode;

    private Instant claimedAt;

    protected Redemption() {
        // for JPA
    }

    private Redemption(long savingsAccountId, Reward reward, long pointsSpent, String voucherCode,
                       Instant claimedAt) {
        this.savingsAccountId = savingsAccountId;
        this.reward = reward;
        this.pointsSpent = pointsSpent;
        this.voucherCode = voucherCode;
        this.claimedAt = claimedAt;
    }

    /**
     * A claim, with its voucher already on it. The voucher is not something that arrives afterwards:
     * redemption is instant and final, so a record of a claim without one would be a moment in which
     * the points were gone and the customer had nothing.
     */
    static Redemption issue(long savingsAccountId, Reward reward, long pointsSpent, Instant claimedAt) {
        return new Redemption(savingsAccountId, reward, pointsSpent, aVoucherFor(reward), claimedAt);
    }

    /** Something like SS-CIN-7F3K2Q: the scheme, what it is for, and what makes it this one. */
    private static String aVoucherFor(Reward reward) {
        StringBuilder voucher = new StringBuilder("SS-").append(reward.voucherPrefix()).append('-');
        for (int character = 0; character < VOUCHER_CHARACTERS; character++) {
            voucher.append(VOUCHER_ALPHABET.charAt(RANDOM.nextInt(VOUCHER_ALPHABET.length())));
        }
        return voucher.toString();
    }

    ClaimedReward asClaimed() {
        return new ClaimedReward(id, reward, pointsSpent, voucherCode, claimedAt);
    }
}
