package io.dataroots.savingstreak.rewards;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * The last one, put aside for one customer for seventy-two hours: which offer, whose it is, when
 * they took it, and when it stops being theirs.
 *
 * <p><strong>A table of its own, and not a column on anything.</strong> A hold is not a state a
 * claim can be in — a claim is final the moment it is made, which {@code Redemption} says at
 * length about itself — and it is not a state an offer can be in either, because an offer with
 * three of something left can be held by three different people at once. It is a relationship
 * between a person and an offer with a clock running on it, which is a row.
 *
 * <p><strong>A hold takes stock and never points, and this row is where that decision is
 * visible: there is no amount on it.</strong> The points stay in the ledger running their own
 * twelve-month clocks, exactly as they were. Holding points was the alternative and it is
 * rejected hard: it would require a second "held" notion inside the points ledger — a batch that
 * is present for the balance but absent for spending, or a fifth kind of movement — and it would
 * have to interact with the oldest-first spending order and the twelve-month expiry rules, which
 * are the most carefully built and most carefully tested thing in this application. The price of
 * not doing it is one honest and explainable outcome: a customer whose points expire underneath
 * their hold cannot convert it, is told they are short, and still holds the thing. That is a true
 * sentence about what happened, and it is a far better outcome than a ledger with two kinds of
 * point in it.
 *
 * <p><strong>Nothing about what it costs is on this row either</strong>, and for a related
 * reason. Converting spends the points at the moment of conversion at the price in force then, so
 * a hold taken the day before a promotion and converted during it pays the sale price. A price
 * frozen here would be a promise this application had decided not to keep, and it would be the
 * one figure on the customer's screen that the catalogue could not correct.
 *
 * <p>The offer is named by its code rather than by a reference to the row, matching what a claim
 * does and for a plainer version of the same reason: the code is the catalogue's immutable
 * natural key, it is what every other table in this module already speaks, and a hold outlives no
 * offer anyway — seventy-two hours is shorter than any administrative decision.
 *
 * <p>Package-private, like {@link Redemption} and {@link RewardOffer}: what this module records,
 * and how, is nobody else's business. What leaves is {@link AHoldOnAnOffer}.
 */
@Entity
class RewardHold {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Whose hold this is.
     *
     * <p>Not null, and unlike the customer column on {@link Redemption} that is true in the
     * database as well as in the domain. This is a new table: no database anywhere has a row in
     * it that was written before customers owned points, so there is nothing to backfill and no
     * reason to leave the column open to a null that could only ever be a bug.
     */
    @Column(nullable = false)
    private Long customerId;

    /** The catalogue code of the offer being held, as text, exactly as a claim names one. */
    @Column(nullable = false)
    private String offerCode;

    @Column(nullable = false)
    private Instant takenAt;

    /**
     * The moment it stops being theirs, written down at the moment it is taken.
     *
     * <p>Stored rather than derived from {@link #takenAt} plus a constant, which is a departure
     * from the line this module otherwise holds and is the same departure a voucher's
     * {@code expiresOn} makes for the same reason. Seventy-two hours is a promise made to a named
     * person at a moment. If the number ever moved — and it is the sort of number that moves — a
     * hold that worked its own deadline out would silently change the deadline of a hold somebody
     * was already counting down, in whichever direction the change went. What the customer was
     * told when they took it is a fact about what happened.
     *
     * <p>It is also what makes the derivation cheap: every question about whether a hold is still
     * live is this column against the clock, in the query, rather than arithmetic over a
     * constant applied row by row.
     */
    @Column(nullable = false)
    private Instant lapsesAt;

    /**
     * Where it is in its life. The argument for the four values, and for why the sweep is not
     * what ends a hold, is on {@link HoldState}.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private HoldState state;

    /**
     * The moment it actually stopped being live, and null while it has not.
     *
     * <p>Beside {@link #lapsesAt} rather than instead of it, because the two answer different
     * questions and a scheme that kept only one of them could not tell a hold somebody gave up
     * after an hour from one that ran the full seventy-two. It is also the only record of when a
     * conversion happened that is on the hold itself; the claim has its own moment, and the two
     * being separately written is what lets anybody check afterwards that they agree.
     */
    private Instant endedAt;

    protected RewardHold() {
        // for JPA
    }

    private RewardHold(long customerId, String offerCode, Instant takenAt, Instant lapsesAt) {
        this.customerId = customerId;
        this.offerCode = offerCode;
        this.takenAt = takenAt;
        this.lapsesAt = lapsesAt;
        // Held, here rather than anywhere a caller could reach, for the reason a voucher is
        // ISSUED in its own constructor: there is no other state a hold can begin in.
        this.state = HoldState.HELD;
    }

    /**
     * The last one, set aside. The moment it lapses is worked out here rather than handed in, so
     * that no caller can write a hold with a deadline of its own choosing.
     */
    static RewardHold takenBy(long customerId, String offerCode, Instant takenAt) {
        return new RewardHold(customerId, offerCode,
                takenAt, TheShelfLifeOfAHold.theMomentItLapses(takenAt));
    }

    Long id() {
        return id;
    }

    long customerId() {
        return customerId;
    }

    String offerCode() {
        return offerCode;
    }

    Instant takenAt() {
        return takenAt;
    }

    Instant lapsesAt() {
        return lapsesAt;
    }

    HoldState state() {
        return state;
    }

    /**
     * Whether this hold is still keeping anything from anybody, as of one moment.
     *
     * <p>Both halves, always: the state <em>and</em> the clock. A hold the sweep has not reached
     * yet is still {@code HELD} and is nevertheless over, and every caller that asked only about
     * the state would be handing somebody a thing they had already lost — or refusing them one
     * that was free. The argument for the clock being the authority rather than the sweep is on
     * {@link HoldState}.
     *
     * <p>Strictly after, so a hold is live right up to its moment and not one instant past it,
     * which is the same reading the query the sweep uses takes of the same column. The two have
     * to agree exactly or a hold could be swept while a conversion still thought it was good.
     */
    boolean isLiveAt(Instant moment) {
        return state == HoldState.HELD && lapsesAt.isAfter(moment);
    }

    /**
     * Turns the hold into the claim it was being held for.
     *
     * <p>Every one of the three endings goes through {@link #endedAs}, which refuses to move a
     * hold that has already ended. That refusal is the last line of defence rather than the
     * first — {@link RewardsService} has read the state and the clock and answered the customer in
     * words long before anything gets here — and it exists for the reason {@code Redemption} gives
     * for its own: the alternative is a method that will silently rewrite a terminal state the day
     * somebody calls it from a second place, and the whole value of a hold is that it cannot be
     * promised to two people.
     */
    void converted(Instant moment) {
        endedAs(HoldState.CONVERTED, moment);
    }

    /** They changed their mind. The stock is back in the window from this moment. */
    void givenUp(Instant moment) {
        endedAs(HoldState.GIVEN_UP, moment);
    }

    /**
     * The seventy-two hours went by and nobody said anything.
     *
     * <p>Written by the sweep, which is recording a thing that has already happened rather than
     * making it happen — the stock came back the moment the clock passed {@link #lapsesAt}, and
     * every reading of what is left has said so since. What the row buys is that whoever is next
     * in line can be handed a hold of their own without two rows both claiming to be live, and
     * that anybody reading the table afterwards can see how a night went.
     */
    void lapsed(Instant moment) {
        endedAs(HoldState.LAPSED, moment);
    }

    private void endedAs(HoldState ending, Instant moment) {
        if (state != HoldState.HELD) {
            throw new IllegalStateException("hold " + id + " on " + offerCode + " is " + state
                    + " and cannot become " + ending);
        }
        this.state = ending;
        this.endedAt = moment;
    }

    /**
     * The hold as the rest of the application reads it, with the two things only the catalogue
     * knows handed in.
     *
     * <p>The title and the price come from the offer as it stands rather than off this row,
     * deliberately, and the argument is written out on {@link AHoldOnAnOffer}: a hold is a live
     * thing rather than a record of one, so there is nothing about it worth freezing.
     */
    AHoldOnAnOffer asItStands(String title, long costInPoints) {
        return new AHoldOnAnOffer(id, customerId, offerCode, title, costInPoints,
                takenAt, lapsesAt, state, endedAt);
    }
}
