package io.dataroots.savingstreak.rewards;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One person's place in the queue for one sold-out offer: whose it is, which offer, when they
 * joined, and what became of it.
 *
 * <p><strong>A table of its own, for the reason {@link RewardHold} is one.</strong> A place in a
 * queue is not a state an offer can be in — forty people can be waiting for one thing — and it
 * is not a state a claim can be in either, because nothing has been claimed and no points have
 * moved. It is a relationship between a person and an offer, and a relationship is a row.
 *
 * <p><strong>There is no position column, and that is the decision this row is built
 * on.</strong> Where somebody stands is counted on every read, from {@link #joinedAt} and the
 * identifier behind it, exactly as what is left of a scarce offer is counted rather than
 * decremented. A stored position would have to be rewritten for everybody behind anybody who
 * left, which is the sort of bookkeeping that is correct on the day it is written and wrong the
 * first time two people leave at once — and it is the second stored figure the whole feature
 * refuses on the grounds that two figures which must agree eventually stop agreeing. The one
 * this must agree with is the order people actually joined in, which is already on the row.
 *
 * <p><strong>Nothing about the offer's price, title or stock is on it either.</strong> A place
 * in a queue is a live thing, not a record of one: the customer is waiting for whatever the
 * offer turns out to be when it comes back, at whatever it costs then, and being promoted buys
 * them a hold rather than a price. The argument is the one {@link AHoldOnAnOffer} makes about a
 * hold's title, only stronger, because a queue can be a great deal longer than seventy-two
 * hours.
 *
 * <p>The offer is named by its code rather than by a reference to the row, matching what a claim
 * and a hold both do: the code is the catalogue's immutable natural key and it is what every
 * other table in this module speaks.
 *
 * <p>There is deliberately no unique constraint over the customer, the offer and the state.
 * Joining twice is refused by {@link RewardsService} in a sentence somebody can read, which is
 * where every other rule in this module is enforced; a constraint would turn the same mistake
 * into a 500 on whichever of the two paths happened to be second. The rule holds for the reason
 * the one-live-hold rule holds — a single connection and a transaction round the check and the
 * write — and it is written down here rather than left lucky.
 *
 * <p>Package-private, like {@link RewardHold} and {@link Redemption}: what this module records,
 * and how, is nobody else's business. What leaves is {@link APlaceInTheQueue}.
 */
@Entity
class WaitingListPlace {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Whose place this is.
     *
     * <p>Not null in the database as well as in the domain, for the reason the same column on
     * {@link RewardHold} is: this is a new table, no database anywhere holds a row in it that
     * was written before customers owned points, and there is nothing to backfill.
     */
    @Column(nullable = false)
    private Long customerId;

    /** The catalogue code of the offer being waited for, as text, exactly as a hold names one. */
    @Column(nullable = false)
    private String offerCode;

    /**
     * When they joined, which is the whole of what decides the order.
     *
     * <p>Off the injected clock like every other moment in this module, so that a trainer
     * winding the clock forward can build a queue in an afternoon and have it come out in the
     * order they built it.
     */
    @Column(nullable = false)
    private Instant joinedAt;

    /**
     * Where it is in its life. The argument for the three values, and for why nothing here
     * expires, is on {@link WaitingState}.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private WaitingState state;

    /**
     * The moment they stopped waiting, and null while they have not.
     *
     * <p>Beside the state rather than instead of it, for the reason {@code RewardHold.endedAt}
     * is beside its own: a scheme that kept only the state could not tell a queue that emptied
     * last night from one that emptied in March, and the night a waiter was promoted is exactly
     * the thing somebody asking "when did this hold appear" needs to be able to line up against
     * the sweep's own line in the log.
     */
    private Instant endedAt;

    protected WaitingListPlace() {
        // for JPA
    }

    private WaitingListPlace(long customerId, String offerCode, Instant joinedAt) {
        this.customerId = customerId;
        this.offerCode = offerCode;
        this.joinedAt = joinedAt;
        // Waiting, here rather than anywhere a caller could reach, for the reason a hold is HELD
        // and a voucher is ISSUED in their own constructors: there is no other state a place in
        // a queue can begin in.
        this.state = WaitingState.WAITING;
    }

    /** Somebody joins the back of the queue, at the moment the application's clock reads. */
    static WaitingListPlace joinedBy(long customerId, String offerCode, Instant joinedAt) {
        return new WaitingListPlace(customerId, offerCode, joinedAt);
    }

    Long id() {
        return id;
    }

    long customerId() {
        return customerId;
    }

    String offerCode() {
        return offerCode;
    }

    Instant joinedAt() {
        return joinedAt;
    }

    WaitingState state() {
        return state;
    }

    /**
     * Their turn came and the sweep handed them a hold.
     *
     * <p>Not "they got the thing": what they were given is seventy-two hours in which the last
     * one is theirs, and whether they convert it is between them and the hold. The queue has
     * nevertheless done everything it promised, which is why this is terminal — the argument is
     * on {@link WaitingState#PROMOTED}.
     */
    void promoted(Instant moment) {
        stoppedWaiting(WaitingState.PROMOTED, moment);
    }

    /** They changed their mind and said so, which closes the gap behind them at once. */
    void left(Instant moment) {
        stoppedWaiting(WaitingState.LEFT, moment);
    }

    /**
     * Both endings go through here, which refuses to move a place that has already ended.
     *
     * <p>The last line of defence rather than the first, exactly as {@code RewardHold.endedAs}
     * is: {@link RewardsService} has read the state and answered the customer in words long
     * before anything gets here. It exists because the alternative is a method that will
     * silently rewrite a terminal state the day somebody calls it from a second place, and the
     * whole value of a queue is that one place in it is promoted once.
     */
    private void stoppedWaiting(WaitingState ending, Instant moment) {
        if (state != WaitingState.WAITING) {
            throw new IllegalStateException("the place " + id + " in the queue for " + offerCode
                    + " is " + state + " and cannot become " + ending);
        }
        this.state = ending;
        this.endedAt = moment;
    }

    /**
     * The place as the rest of the application reads it, with the two things only a count and
     * the catalogue know handed in.
     *
     * <p>The position is counted by {@link RewardsService} against the rest of the queue and the
     * title is read off the offer as it stands, for the reason {@link RewardHold#asItStands}
     * takes both from outside: this row has no queue in it and no catalogue in it, and a row
     * that worked its own position out would be a row that had to see every other one.
     */
    APlaceInTheQueue asItStands(String title, int position) {
        return new APlaceInTheQueue(id, customerId, offerCode, title, position, joinedAt);
    }
}
