package io.dataroots.savingstreak.budgets;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One recurring bill put in one spending category: this module's own row, keyed on the bill.
 *
 * <p><strong>This row is here rather than a column on {@code RecurringBill}, and that is the whole
 * reason this slice exists.</strong> A category reference on the bill would make {@code accounts}
 * depend on {@code budgets} and close a cycle around the largest module in the application — and
 * {@code accounts} would then have to have an opinion about a word it has never heard of, on every
 * read of a bill, in a nightly run that has nothing to do with budgeting. The dependency runs one
 * way: this module reads Accounts' public read models, Accounts gains nothing and learns nothing,
 * and the price of that is one join this module does for itself. The money-movements ledger already
 * pays the same price for the same reason, and a module boundary is worth more than the convenience
 * of a foreign key.
 *
 * <p><strong>The bill is named by identifier and nothing else is copied.</strong> What the bill is
 * called, what it costs and the day it goes out on are Accounts' record of it, read from there when
 * somebody wants them; a copy here would be a second answer to "what is this bill" and the two would
 * disagree the first time a customer changed one. Renaming a bill does not touch this row, which is
 * the correct outcome: the category is a label on the thing, not on what it was called that month.
 *
 * <p><strong>The account is on the row as well as the bill</strong>, although a bill belongs to
 * exactly one account and is therefore enough on its own. It is what lets one account's whole
 * picture be read in a single query rather than a query per bill, and it is what the uniqueness
 * index is written over — see {@link BudgetsOnStartUp}.
 *
 * <p><strong>At most one category per bill, and a bill is never split.</strong> A bill is one
 * declared payment to one provider for an amount the declaration fixes, and every occurrence of it
 * counts wholly in one place; a customer who wants their rent divided between Housing and Utilities
 * declares two bills, which is both simpler and truer to what a bill is. A spend is the thing that
 * splits, because a supermarket trip really was half food and half wine.
 *
 * <p><strong>There is no ending and no history.</strong> Moving a bill from Housing to Utilities
 * re-labels the whole of that bill's history, because it is one label on one thing and somebody
 * fixing it wants it fixed everywhere — so the row is moved rather than closed and reopened, and
 * taking a bill out of every category deletes it. That is the one deletion in this module, and it is
 * right here for the same reason: what is being unmade is an opinion about a payment rather than the
 * record of the payment, which lives on the bill's own occurrences and is untouched by any of this.
 *
 * <p><strong>A category that has been ended keeps the bills that pointed at it.</strong> Nothing
 * here is unpicked when a category ends: the row stands, every read says the category is ended, and
 * a customer who wants the bill somewhere else moves it themselves. Silently unlinking would make
 * ending a category quietly rewrite what the months before it were filed under.
 *
 * <p>Package-private, like every row in this module. {@link TheCategoryABillIsIn} is what leaves.
 */
@Entity
class CategorisedBill {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The account the bill leaves, so that one account's whole picture is one query. Not unique:
     * a household files several bills under several words.
     */
    private long currentAccountId;

    /**
     * The bill, named by the identifier {@code accounts} gave it. Unique per account, and the
     * guarantee is the index {@link BudgetsOnStartUp} creates rather than anything this class can
     * say.
     */
    private long billId;

    /** The category it is in. An ended category is a category, and stays pointed at. */
    private long categoryId;

    /**
     * When the bill was last put where it is now, which is what a page prints beside the label.
     *
     * <p>Moved forward when a bill is moved from one category to another, because that is when this
     * row started saying what it says. It is deliberately not "when the bill was first categorised":
     * nothing in this module asks that question, and a moment that survived a correction would be a
     * moment describing a row that no longer exists.
     */
    private Instant filedAt;

    protected CategorisedBill() {
        // for JPA
    }

    CategorisedBill(long currentAccountId, long billId, long categoryId, Instant filedAt) {
        this.currentAccountId = currentAccountId;
        this.billId = billId;
        this.categoryId = categoryId;
        this.filedAt = filedAt;
    }

    long getBillId() {
        return billId;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    long getCategoryId() {
        return categoryId;
    }

    Instant getFiledAt() {
        return filedAt;
    }

    /**
     * The customer says this bill belongs somewhere else now, and answers whether that was a move
     * at all — so that putting a bill back where it already is can be logged as the nothing it is
     * rather than written twice.
     *
     * <p>The row is moved rather than replaced, so the whole of the bill's history is re-labelled by
     * one write. That is the point: somebody who discovers in June that the rent has been in
     * Groceries since March wants March fixed, not a note saying March was wrong.
     */
    boolean isNowIn(long categoryId, Instant filedAt) {
        if (this.categoryId == categoryId) {
            return false;
        }
        this.categoryId = categoryId;
        this.filedAt = filedAt;
        return true;
    }
}
