package io.dataroots.savingstreak.budgets;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.YearMonth;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * What one spending category is allowed to cost in a month, and the stretch of months that figure
 * was in force for.
 *
 * <p><strong>A declaration of its own rather than a column on {@link SpendingCategory}.</strong> A
 * category is a word and outlives every figure ever put on it: it can be renamed without the figure
 * moving, it can carry no figure at all, and it can carry several over its life — one for the months
 * before the customer changed their mind and one for the months after. A budget on the category
 * itself could not do the last of those without either rewriting history or growing a second table
 * to remember it, which is this one.
 *
 * <p><strong>Superseded, never mutated, and that is the point of the two month columns.</strong>
 * Changing what a category is allowed to cost ends the standing row at the month before this one and
 * opens a new row effective this month. So a customer who raises their grocery budget in June leaves
 * April and May quoting the figure that stood then — the history is what happened rather than what
 * they currently intend — and every month read is a lookup rather than a guess about which figure
 * was in force. One mechanism covers a change of amount and, from the next slice, a change of
 * rollover rule; the fold simply reads whichever row covered the month it was asked about.
 *
 * <p><strong>Months are held as the day they begin.</strong> {@code effectiveFrom} is the first day
 * of the first month this figure governs, and {@code stoodThrough} is the first day of the last one
 * — not a day inside it, and not the last day of it. A database has dates and has no months, and
 * "the first of the month" is a date that sorts and compares correctly without anybody decoding it;
 * {@link TheMonthAMomentFallsIn} is the one place the two representations meet, and it is the same
 * bargain the notification record strikes when it carries the month a warning was about in its
 * existing {@code occursOn} column.
 *
 * <p><strong>{@code stoodThrough} before {@code effectiveFrom} is a legal row and not a broken
 * one.</strong> A budget declared and superseded inside one month governs no month at all: it was
 * never the figure any complete month was judged against, and the row is kept so that the log and
 * the record say a figure was named and replaced rather than silently losing it. Every read asks
 * whether a month falls in the closed range between the two, so such a row answers for nothing, and
 * no reader needs a special case for it.
 *
 * <p><strong>The rollover rule sits beside the amount, and the supersession covers both.</strong>
 * It is the budget that has a surplus, so it is the budget that says what becomes of one; and a rule
 * changed in June must leave April alone exactly as an amount changed in June does. Nothing about
 * the shape here had to move to make that true — the two month columns and the three states were
 * always the mechanism, and the rule is simply the second field they govern. A customer who turns
 * Groceries into an envelope ends one row and opens another, and the fold reads whichever row
 * covered the month it was asked about. {@link RolloverRule} argues what the three rules mean.
 *
 * <p><strong>Per category rather than per account</strong>, and the account is carried beside it all
 * the same. A budget belongs to one category and a category belongs to one account, so the account
 * could be looked up — but every read in this module is scoped by the account in the path, and a
 * query that had to join through the categories to honour that scope would be a join on the hot path
 * of the page this feature exists to draw.
 *
 * <p>Package-private, like every row in this module. {@link ABudgetOnACategory} is what leaves.
 */
@Entity
class MonthlyBudget {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The account whose money this figure is a limit on. Carried rather than looked up through the
     * category, so that every read here is scoped the way every other read in this module is.
     */
    private long currentAccountId;

    /** The category the figure is on. Several rows per category over its life, one standing. */
    private long categoryId;

    /**
     * What the category is allowed to cost in a month, in euros, quoted to the cent by the time it
     * is written.
     *
     * <p>An amount and never a nought: a budget of nothing is not a budget, it is the customer
     * saying they have stopped budgeting the category, and that is what stopping is for. The
     * refusal says so in words.
     */
    private BigDecimal amount;

    /**
     * What becomes of the difference between this figure and what the category actually cost, when
     * a month it governs ends.
     *
     * <p>Beside the amount rather than on the category, because it is the figure that has a surplus
     * and because the two are changed by the one declaration. A row written before this column
     * existed carries nothing here and is read as the default — see
     * {@link RolloverRule#orTheDefault}, where that reading is argued; the schema in this
     * application is generated and there are no migrations, so an empty column on an older row is
     * the ordinary case rather than a fault.
     */
    @Enumerated(EnumType.STRING)
    private RolloverRule rollover;

    /** The first day of the first month this figure governs. Always the first of some month. */
    private LocalDate effectiveFrom;

    /**
     * The first day of the last month this figure governs, and nothing at all while it still
     * stands.
     *
     * <p>Filled exactly when the state stops being {@link BudgetState#STANDING}. A standing budget
     * has no last month, because the customer has not said there is one — and a date put here in
     * advance would be this application deciding on their behalf when they stop caring.
     */
    private LocalDate stoodThrough;

    /** Whether this is the figure in force, or the record of one that used to be. */
    @Enumerated(EnumType.STRING)
    private BudgetState state;

    /** When the customer named this figure. */
    private Instant declaredAt;

    /** When it stopped being the figure in force, and nothing at all while it still stands. */
    private Instant stoodDownAt;

    protected MonthlyBudget() {
        // for JPA
    }

    MonthlyBudget(long currentAccountId, long categoryId, BigDecimal amount, RolloverRule rollover,
                  YearMonth effectiveFrom, Instant declaredAt) {
        this.currentAccountId = currentAccountId;
        this.categoryId = categoryId;
        this.amount = amount;
        this.rollover = RolloverRule.orTheDefault(rollover);
        this.effectiveFrom = TheMonthAMomentFallsIn.theDayItBegins(effectiveFrom);
        this.declaredAt = declaredAt;
        this.state = BudgetState.STANDING;
    }

    Long getId() {
        return id;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    long getCategoryId() {
        return categoryId;
    }

    BigDecimal getAmount() {
        return amount;
    }

    /**
     * What this figure hands on when a month it governs ends, with a row that predates the column
     * read as the default rather than as a hole.
     *
     * <p>Read through {@link RolloverRule#orTheDefault} here rather than at the half-dozen places
     * that ask, so that no caller can be the one that forgot: a null reaching the fold would be a
     * carry that threw in the middle of drawing somebody's month.
     */
    RolloverRule getRollover() {
        return RolloverRule.orTheDefault(rollover);
    }

    /** The first month this figure governs, read back as the month it was written down as. */
    YearMonth effectiveFrom() {
        return TheMonthAMomentFallsIn.of(effectiveFrom);
    }

    /** The last month it governs, or nothing at all while it still stands. */
    YearMonth stoodThrough() {
        return stoodThrough == null ? null : TheMonthAMomentFallsIn.of(stoodThrough);
    }

    BudgetState getState() {
        return state;
    }

    Instant getDeclaredAt() {
        return declaredAt;
    }

    Instant getStoodDownAt() {
        return stoodDownAt;
    }

    /** Whether this is still the figure in force, which is what every change to one asks first. */
    boolean isStillStanding() {
        return state.isStillStanding();
    }

    /**
     * Whether this figure is the one that month was judged against.
     *
     * <p>The one lookup every derived figure in this module rests on, written here so that it cannot
     * be written two ways. A standing row has no top, so it governs every month from its first
     * onwards — including months the clock has not reached yet, which is what makes "what is this
     * month allowed to cost" answerable on the first of the month rather than only at the end of it.
     */
    boolean stoodIn(YearMonth month) {
        if (month.isBefore(effectiveFrom())) {
            return false;
        }
        YearMonth last = stoodThrough();
        return last == null || !month.isAfter(last);
    }

    /**
     * Ends this figure's run at the end of the month before this one, because a figure the customer
     * preferred takes effect now.
     *
     * <p>The month it is superseded in belongs to the row replacing it, which is what makes
     * "changing the figure leaves last month alone" true from both ends: this row keeps every month
     * up to the one before, and the new one starts here. Superseding inside the month this row
     * itself began in leaves it governing nothing, which is exactly what it did.
     */
    void supersededFrom(YearMonth thisMonth, Instant when) {
        stoodDown(BudgetState.SUPERSEDED, thisMonth.minusMonths(1), when);
    }

    /**
     * Stops the budget without touching the category, from this month onwards.
     *
     * <p>This month included, which is the difference between stopping a budget and ending the
     * category it is on. Stopping is a customer saying they are no longer policing this — so the
     * month they say it in reports what they spent and no figure, because a limit they have
     * disowned is not one they should still be measured against. Ending the category is the other
     * way round, and {@link #stoppedBecauseTheCategoryEnded} says why.
     */
    void stoppedFrom(YearMonth thisMonth, Instant when) {
        stoodDown(BudgetState.STOPPED, thisMonth.minusMonths(1), when);
    }

    /**
     * Stops the budget because the word it was a limit on is no longer one the customer uses,
     * leaving this month still governed by it.
     *
     * <p><strong>This month is kept, and that is deliberately the opposite of {@link
     * #stoppedFrom}.</strong> A customer who ends Groceries on the twentieth spent three weeks of
     * that month against a figure they had agreed to, and a month read that dropped the figure would
     * erase the standard they were actually held to — the spending is still there, so the limit it
     * was measured against has to be. Stopping a budget is a decision about the limit; ending a
     * category is a decision about the word, and the limit merely stops with it.
     *
     * <p>No month after this one is governed, which is the whole of what "stops its budget at once"
     * means for a category that will never be spent on again.
     */
    void stoppedBecauseTheCategoryEnded(YearMonth thisMonth, Instant when) {
        stoodDown(BudgetState.STOPPED, thisMonth, when);
    }

    /**
     * The one place a budget stops standing, so that the state, the last month and the moment can
     * never be written apart from each other.
     */
    private void stoodDown(BudgetState state, YearMonth lastMonth, Instant when) {
        this.state = state;
        this.stoodThrough = TheMonthAMomentFallsIn.theDayItBegins(lastMonth);
        this.stoodDownAt = when;
    }
}
