package io.dataroots.savingstreak.budgets;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One thing a customer says their money goes on: a word of their own, on one current account.
 *
 * <p><strong>A name, and nothing else.</strong> No colour, no icon and no parent category. A colour
 * is a reading of a category rather than a fact about one and belongs to the page that draws it —
 * the same bargain {@code NotificationReason} strikes about severity — and a hierarchy would be a
 * second arithmetic, because every figure this module derives would then have to say whether it
 * counted the children. What a category is allowed to cost is not here either: that is a budget,
 * which is a declaration with a figure and a rollover rule and a month it takes effect from, and it
 * is superseded rather than mutated. A category outlives every budget that was ever set on it.
 *
 * <p><strong>Here rather than in {@code accounts}</strong>, which already carries the customer, both
 * account kinds, the declared income, the bills, the arrears and the month ahead. The dependency
 * runs one way: this module reads Accounts' public read models and takes money through
 * {@code AccountsService.withdrawFrom}, exactly as {@code deposits} does, and Accounts gains nothing
 * and learns nothing. A category on a {@code RecurringBill} would close that cycle, which is why a
 * bill's category is a row in this module keyed on the bill rather than a column on the bill.
 *
 * <p><strong>Per current account rather than per customer.</strong> A household in this application
 * <em>is</em> a current account — that is the language the demo seed already uses — and a category
 * scoped to the customer would put a budget beside a balance it does not match on any account the
 * customer holds more than one of.
 *
 * <p><strong>Many per account, capped at twenty standing</strong>, mirroring the bills cap and for
 * the same two reasons: an unbounded list is a denial of service on every fold in this module that
 * walks one account's categories, and twenty is what a page can promise to draw. Ended categories do
 * not count against it, so ending one makes room for another.
 *
 * <p><strong>A name stands only once on an account at a time.</strong> Two live categories called
 * Groceries would be two answers to "what did the groceries cost", and nothing could say which the
 * customer meant. The same name on another account is another household's word, and the same name
 * declared again after the first was ended is a new category with a new identifier and no claim on
 * the old one's months. The guarantee is a partial unique index created by hand at start-up rather
 * than a constraint on this class — see {@link BudgetsOnStartUp}, which says why the entity cannot
 * say it.
 *
 * <p><strong>Ending is one-way</strong>, following bills, saving rules and goals: the category
 * leaves the standing list, stays readable among the ended, and cannot be renamed or ended again.
 * {@link CategoryState} argues why.
 *
 * <p>Package-private, like every row in this module. {@link ADeclaredCategory} is what leaves.
 */
@Entity
class SpendingCategory {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The account whose money goes on it. Not unique, deliberately: a household describes its
     * spending in several words, and the cap rather than a constraint is what keeps the list finite.
     */
    private long currentAccountId;

    /**
     * What the customer calls it — "Groceries", "Fuel", "Going out".
     *
     * <p>The whole reason a category is a row rather than a figure, and the whole reason this
     * feature exists: spending described in the application's words rather than in the customer's is
     * spending nobody argues with, and arguing with it is the skill this application is here to
     * teach.
     *
     * <p>Kept trimmed and as typed otherwise. Two categories differing only in case are two
     * categories, because the alternative is this module deciding that a customer who wrote
     * "groceries" meant the "Groceries" they already have — and a rule the customer did not ask for
     * is worse than a list they can tidy themselves by renaming one of the two.
     */
    private String name;

    /** When the category now standing was declared. */
    private Instant declaredAt;

    /** Whether the customer is still filing money under it, or has ended it for good. */
    @Enumerated(EnumType.STRING)
    private CategoryState state;

    /** When it was ended, and nothing at all while it still stands. Filled exactly when ended. */
    private Instant endedAt;

    protected SpendingCategory() {
        // for JPA
    }

    SpendingCategory(long currentAccountId, String name, Instant declaredAt) {
        this.currentAccountId = currentAccountId;
        this.name = name;
        this.declaredAt = declaredAt;
        this.state = CategoryState.STANDING;
    }

    Long getId() {
        return id;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    String getName() {
        return name;
    }

    Instant getDeclaredAt() {
        return declaredAt;
    }

    CategoryState getState() {
        return state;
    }

    Instant getEndedAt() {
        return endedAt;
    }

    /** Whether this category is over, which is the one thing every change to it has to ask first. */
    boolean isEnded() {
        return !state.isStillStanding();
    }

    /**
     * The customer says this is what they call it now.
     *
     * <p>The name and nothing else, because a category is a name and nothing else. The moment it was
     * declared is deliberately untouched: it is when this word started being used, and a rename is a
     * correction to how it was spelled rather than a new beginning — the months already filed under
     * it stay filed under it, which is the whole difference between renaming one and ending one to
     * declare another.
     */
    void isNowCalled(String name) {
        this.name = name;
    }

    /**
     * Ends the category for good, and answers whether it was still standing — so that a second
     * ending can be refused by whoever asked rather than quietly written twice.
     *
     * <p>The name is left exactly as it was. It is what the record is <em>for</em>: a customer
     * reading what March went on is reading it, and an ending that cleared it would leave a row
     * saying only that money once went on something.
     */
    boolean end(Instant endedAt) {
        if (isEnded()) {
            return false;
        }
        this.state = CategoryState.ENDED;
        this.endedAt = endedAt;
        return true;
    }
}
