package io.dataroots.savingstreak.budgets;

import java.math.BigDecimal;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One part of what a spend was for: an amount, and the category it is filed under — or no category
 * at all.
 *
 * <p><strong>A row rather than a column on the spend</strong>, because a supermarket trip that was
 * half food and half wine is one payment and two claims on two budgets, and a spend that could name
 * only one category would force the customer to record it as something it was not. The parts of a
 * split sum to the spend exactly, to the cent, and that invariant has no exceptions: a split a cent
 * over or a cent under is refused in words and nothing moves, because an application that quietly
 * lost a euro here would lose it out of a figure the customer is about to make a decision on.
 *
 * <p><strong>A category is optional, and that is the feature.</strong> A part with no category is
 * <em>uncategorised</em> — a legitimate state and not a missing value. Somebody in a hurry records
 * the spend now and files it later, which is the honest record of what happened, and a spend may be
 * half filed and half not: thirty euros to Groceries and twenty still unfiled is a split this module
 * keeps as written. Recording a spend at all should never be the hard part, and the correction path
 * exists precisely so that a rushed entry can become a good record afterwards instead of staying a
 * bad one.
 *
 * <p><strong>No relation to {@link SpendingCategory} and none to {@link Spend}</strong>, only their
 * identifiers — the shape {@code WithdrawalAllocation} already uses for the same reason. A foreign
 * key to the category would make an ended category undeletable by the database rather than by this
 * module's own rule, and a null one would be a null foreign key doing the work of a meaning. Which
 * categories a part may name is a rule, it is asked before a row is written, and it is written down
 * in {@code SpendsService}.
 *
 * <p><strong>Capped at ten per spend.</strong> A purchase split eleven ways is not a purchase
 * anybody is describing honestly, every fold in this module walks these rows, and ten is what a page
 * can promise to draw. The eleventh is refused in words rather than dropped.
 *
 * <p>Package-private, like every row in this module. {@link ASpendPart} is what leaves.
 */
@Entity
class SpendPart {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The spend this is part of. Its parts are read in the order they were written. */
    private long spendId;

    /**
     * The category this part is filed under, or nothing at all when it is uncategorised.
     *
     * <p>Nullable on purpose, and the one nullable identifier in this module. Nothing is a meaning
     * here rather than an absence of data: it says the customer recorded the money and has not
     * decided what it was for, which is a state every read in this feature has to be able to report
     * — a euro nobody has filed is still a euro that left the account.
     */
    private Long categoryId;

    /**
     * What of the spend this part accounts for, to the cent.
     *
     * <p>More than zero, judged by {@code AmountOfMoney} like every other amount in this
     * application. A part worth nothing describes nothing, and allowing a negative one would let a
     * split add up to the right total out of figures that were never spent.
     */
    private BigDecimal amount;

    protected SpendPart() {
        // for JPA
    }

    SpendPart(long spendId, Long categoryId, BigDecimal amount) {
        this.spendId = spendId;
        this.categoryId = categoryId;
        this.amount = amount;
    }

    Long getId() {
        return id;
    }

    long getSpendId() {
        return spendId;
    }

    /** The category, or nothing at all, which is what uncategorised means. */
    Long getCategoryId() {
        return categoryId;
    }

    BigDecimal getAmount() {
        return amount;
    }
}
