package io.dataroots.savingstreak.budgets;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One outgoing a customer actually made: what they called it, what it cost, and the moment it was
 * recorded — which is the moment the money left the current account.
 *
 * <p><strong>Declared, never invented.</strong> Nothing in this application generates a spend, and
 * this class is the front door every one of them comes through: a customer typing what they bought
 * today, the seed writing a household's history, and — when it is built — the spending simulator,
 * which produces candidate spends through this door rather than down a parallel path. Nothing here
 * assumes a spend came from a person typing.
 *
 * <p><strong>The money is gone by the time this row exists.</strong> A spend is recorded and taken
 * in one transaction, through {@code AccountsService.withdrawFrom} — the same all-or-nothing
 * withdrawal a bill and a deposit use, which refuses rather than going negative. A spend larger than
 * the balance is refused outright: nothing moves, and no row is written to be explained away later.
 * There is no partial spend and no overdraft, because a half-made purchase is neither a lesson nor a
 * thing that happens.
 *
 * <p><strong>The amount is on the spend and the split is beside it.</strong> The amount is what left
 * the account and it is a fact; the split is an opinion about what it was for, and the two are
 * separated exactly along that line. {@link SpendPart} carries the opinion, sums to this figure to
 * the cent, and is the only part of a spend a correction may rewrite.
 *
 * <p><strong>Not backdated.</strong> There is no date on this row a caller may set: the moment comes
 * from the application's clock, and the day the spend counts to is the day that clock reads. Letting
 * a customer file a spend into a month they have already read would let them rewrite a rollover
 * chain retroactively by typing a date, which is a different feature and a worse one. History here
 * is made the way every other history in this application is made — by winding the clock, or by the
 * seed.
 *
 * <p><strong>No deletion and no change of amount.</strong> There is no setter for either, and none
 * is coming: the money moved, and a record that can be unmade is not a record. A mistyped amount
 * stands. What can be changed is the only thing that was ever an opinion, which is the split.
 *
 * <p><strong>A correction rewrites everything derived from it, and that is the point.</strong>
 * Re-splitting a spend moves its euros out of one category's month and into another's, and every
 * figure this module derives from that month moves with them. A customer who discovers in June that
 * they filed March's car repair under Groceries wants March fixed rather than a note saying March
 * was wrong. The one thing that is <em>not</em> rewritten is a notification already raised about
 * that month: an inbox is a log of what was said on the nights it was said, and the budget is what
 * is true now. Both are right, and they will look inconsistent to somebody reading a June inbox
 * against a June budget, so this is written down on both sides rather than on neither.
 *
 * <p><strong>No start-up index joins {@link BudgetsOnStartUp} for this table or for
 * {@link SpendPart}'s</strong>, and that is a decision rather than an omission. That component
 * exists for composite <em>unique</em> rules, which the SQLite dialect writes nowhere and which
 * therefore have to be created by hand — and a spend has no natural key for such a rule to be made
 * of. Two spends of fifty euros called "Groceries" on one day are two trips to the shop, not a
 * duplicate; a split naming one category twice adds up to exactly what a split naming it once would.
 * There is nothing here a database could refuse that this module would want refused.
 *
 * <p>Package-private, like every row in this module. {@link ARecordedSpend} is what leaves.
 */
@Entity
class Spend {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The account the money left. Per current account rather than per customer, like everything else
     * in this module: a household in this application <em>is</em> a current account, and a spend
     * counted against a balance it did not come out of would be a figure nobody could check.
     */
    private long currentAccountId;

    /**
     * What the customer calls it — "Delhaize", "Round of drinks", "New tyres".
     *
     * <p>A name and not a merchant, a reference or a description. A list of spends should read like
     * somebody's week rather than like a bank statement, and the only way to get that is to let them
     * write it. Kept trimmed and as typed otherwise, exactly as a category's name is: deciding that
     * somebody meant something other than what they wrote is a rule they did not ask for.
     */
    private String name;

    /**
     * What left the account, to the cent.
     *
     * <p>Judged by {@code AmountOfMoney} before it is written, so a figure quoted more finely than
     * money is quoted is refused rather than rounded — the same rule and the same sentence a deposit
     * and a withdrawal of it would meet. SQLite has no decimal type and hands 12.50 back as 12.5,
     * so it is quoted to the cent again on the way out of this module rather than where it is read.
     */
    private BigDecimal amount;

    /**
     * When it was recorded, which is when the money left.
     *
     * <p>One moment and not two. A spend "happened" when the balance fell, and a second column
     * saying when the customer typed it in would be a second answer to which month it belongs in —
     * with nothing to say which of the two every figure derived below should use.
     */
    private Instant recordedAt;

    /**
     * When the split was last put right, or nothing at all on a spend nobody has corrected.
     *
     * <p><strong>Nullable on purpose, and a stand-in date would be the bug.</strong> The whole
     * reason this column exists is so that the ledger does not pretend somebody got it right the
     * first time: a spend that was never corrected has to read as one that was never corrected, and
     * a moment copied from {@link #recordedAt} would make every spend in the application look like a
     * spend that had been argued with.
     *
     * <p>It says when the split was <em>last</em> put right rather than how many times it has been.
     * A correction is the customer stating what the spend was for, not an entry in a log of their
     * indecision — what the record owes a reader is that it was not right the first time and when it
     * stopped being wrong, and a second correction moves the moment rather than adding a row.
     *
     * <p>It is not a version and it does not decide anything. Which month a spend counts to is
     * {@link #recordedAt}'s answer and stays {@link #recordedAt}'s answer however often the split
     * changes: a correction re-files euros that already left the account, so letting this moment
     * move a spend into the month it was corrected in would be backdating by the back door.
     */
    private Instant correctedAt;

    protected Spend() {
        // for JPA
    }

    Spend(long currentAccountId, String name, BigDecimal amount, Instant recordedAt) {
        this.currentAccountId = currentAccountId;
        this.name = name;
        this.amount = amount;
        this.recordedAt = recordedAt;
    }

    Long getId() {
        return id;
    }

    long getCurrentAccountId() {
        return currentAccountId;
    }

    String getName() {
        return name;
    }

    BigDecimal getAmount() {
        return amount;
    }

    Instant getRecordedAt() {
        return recordedAt;
    }

    /** When the split was last put right, or nothing at all when it never was. */
    Instant getCorrectedAt() {
        return correctedAt;
    }

    /**
     * Says that the split was put right at this moment, which is the only thing about a spend that
     * may be said twice.
     *
     * <p>The one mutator on this row, and it changes nothing the money did: the amount, the name and
     * the moment the balance fell are all exactly where they were. The parts themselves are rows
     * beside this one and are replaced wholesale by {@link SpendsService}, in the one transaction
     * that also calls this — so a reader who finds a moment here finds the split it belongs to.
     *
     * <p>It overwrites rather than refusing a second call. A customer who gets a category wrong
     * twice is a customer who has to be able to put it right twice, and the moment a reader of the
     * ledger is asking about is the last one.
     */
    void wasCorrectedAt(Instant moment) {
        this.correctedAt = moment;
    }
}
