package io.dataroots.savingstreak.products;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import io.dataroots.savingstreak.deposits.AmountOfMoney;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One month that has been judged: which account, which of its periods, the days it covered, the
 * average and the lowest balance across them, the rate it was paid at, the version that rate came
 * from, whether the bonus was earned, and what it paid.
 *
 * <p><strong>It explains itself, and that is the point of it.</strong> A customer asking why they
 * were paid forty-one cents can read the period, the balance it was worked out on and the rate off
 * one row and redo the multiplication. Nothing here is derivable afterwards: the average daily
 * balance of last March is a walk over a ledger that has moved since, and the version an account
 * was on is a thing that can change. Written down, it is an answer; derived later, it is a
 * reconstruction that might disagree with the euros that were actually paid.
 *
 * <p><strong>What makes the sweep idempotent, and by construction rather than by care.</strong> A
 * row per account per period, unique over the pair, means a second pass over the same months cannot
 * pay twice even if the rule underneath were rewritten. The sweep also checks in Java, so a second
 * run pays nothing without the index; but the check and the guarantee are different things, and two
 * runs at the same moment would both read the same empty set of periods already paid. The
 * uniqueness is not declared here for the reason {@code LoyaltyBonusPaid} gives at length — the
 * SQLite dialect writes a composite unique clause nowhere — so {@link ProductsOnStartUp} creates
 * the index itself before the application serves anything.
 *
 * <p><strong>A period that paid nothing is written down all the same</strong>, and that is the one
 * place this parts company with the loyalty record beside it. There, an anniversary worth nothing
 * leaves no row, because money never comes back into a deposit and an anniversary worth nothing
 * today is worth nothing for ever. Here, a period is a window that has closed: it will never be
 * judged again, whatever happens to the account afterwards, so the row is the statement that it
 * <em>was</em> judged. Without it, an account that was empty for a month would have that month
 * re-walked on every sweep for the rest of its life, and a customer asking why nothing arrived in
 * March would be answered with a silence rather than with a row saying the average balance was
 * nought.
 *
 * <p><strong>What it paid is written here and the ledger row it became is named beside it</strong>,
 * which is the arrangement the loyalty record already settles: the figure is the audit trail and
 * the identifier is where the euros actually went. They are not two answers to one question — the
 * ledger says what the account holds today, and this says what the month was worth when it was
 * judged, which nothing afterwards can change.
 *
 * <p><strong>The lowest balance and whether the bonus was earned are what make a month paid less
 * explainable from the row alone.</strong> The walk that produces the average produces the lowest
 * for nothing, and the condition a minimum-balance account has to keep is judged on exactly that
 * figure: a customer looking at a month that paid the headline rate can read, on the same row, how
 * low the balance went and compare it with the floor their agreement names. The rate beside them is
 * what was <em>actually</em> paid — headline plus bonus on a month that earned it, headline alone
 * on one that did not — so the three figures are one consistent statement rather than an advertised
 * rate and a separate excuse. Every posting written before the bonus existed says it was not
 * earned, which was true then and is true now: those accounts had no bonus on offer.
 *
 * <p>Package-private, like the repository: what this module records, and how, is nobody else's
 * business. {@link AnInterestPosting} is what leaves.
 */
@Entity
class InterestPosting {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The account whose month this was, held by identifier like every reference to one here. */
    @Column(nullable = false)
    private long savingsAccountId;

    /**
     * Which of that account's periods this was — one for the first month, two for the second.
     *
     * <p>The ordinal rather than only the dates. Half of the unique constraint is this column, and
     * an ordinal is the half a sweep can ask about without recomputing a calendar: "has this
     * account been paid its ninth month?" is the question, and the days that month covered are an
     * answer to a different one.
     */
    @Column(nullable = false)
    private int periodOrdinal;

    /** The first day the period covers. */
    @Column(nullable = false)
    private LocalDate periodFrom;

    /**
     * The day the period ended, which it does not itself cover.
     *
     * <p>Half-open, like every other stretch of time in this application, so that two adjacent
     * periods agree about the day between them. It is also the day the money is dated at, because a
     * month's interest is paid for a month that has ended.
     */
    @Column(nullable = false)
    private LocalDate periodUntil;

    /**
     * The average daily balance across the period, in cents, floored.
     *
     * <p>The figure the interest was worked out from, written down rather than recomputed. The
     * ledger it was walked over goes on moving, so this is the only place the month's own answer
     * survives.
     */
    @Column(nullable = false)
    private long averageDailyBalanceCents;

    /**
     * The lowest the balance went on any day of the period, in cents.
     *
     * <p>What a floor is judged on, and what a single day's dip is visible in. Recorded before
     * anything reads it, for the reason the class says: the walk that found it will not be run
     * again.
     */
    @Column(nullable = false)
    private long lowestDailyBalanceCents;

    /**
     * The rate it was actually paid at, in basis points a year — 60 is 0.60%.
     *
     * <p><strong>Actually</strong> is load-bearing: on a month that kept the floor this is the
     * headline rate and the bonus added together, and on one that did not it is the headline rate
     * alone. Storing the headline and letting a reader add the bonus back when the flag beside it
     * says so would put the arithmetic that priced the month in two places — here and in whatever
     * screen drew it — and the day a third condition earns a rate they would disagree.
     */
    @Column(nullable = false)
    private int rateBasisPoints;

    /**
     * Whether the condition that wins the bonus rate was kept.
     *
     * <p>True when the bonus is inside {@link #rateBasisPoints} above and false when it is not, so
     * that the flag and the rate are one fact rather than two that could drift apart. False on a
     * product with no bonus to offer as well as on a month that went under the floor, and those two
     * are told apart by the agreement rather than by a third value here: a month with no bonus on
     * offer has no floor on its terms to have missed.
     *
     * <p>It was written from the first posting this application ever made rather than added with
     * the rule that fills it in, so that a posting is the whole answer to "what was decided about
     * this month" from the first one onwards — a column added afterwards would be null on every
     * month already paid, and the question "was the bonus earned in March" would have two answers
     * depending on when March was swept.
     */
    @Column(nullable = false)
    private boolean bonusEarned;

    /**
     * Which version of the account's terms the rate came from.
     *
     * <p>The number alone, never a copy of what the version says, for the reason a deposit gives
     * about the same column: it is meaningless without a product to belong to, this row already
     * names the account, and the account names exactly one agreement — so the pair is the address
     * and the terms are read from the row that has always held them. An account that takes newer
     * terms next year leaves this month saying what it was actually paid under.
     */
    @Column(nullable = false)
    private int termsVersion;

    /** What the period paid, in cents, and nought for a month that paid nothing. */
    @Column(nullable = false)
    private long interestCents;

    /**
     * The ledger row the euros became, or nothing at all when the period paid nothing.
     *
     * <p>Where the money went, so that a posting and the balance it raised can be put beside each
     * other without either being searched for by date and amount. It is absent rather than nought
     * on a month that paid nothing, because no row was written — and a nought would be an
     * identifier, since identifiers here start at one.
     */
    private Long paidAsDepositId;

    /** The moment the sweep wrote this, which is the one thing here about when rather than about what. */
    @Column(nullable = false)
    private Instant postedAt;

    protected InterestPosting() {
        // for JPA
    }

    private InterestPosting(long savingsAccountId, int periodOrdinal, LocalDate periodFrom,
                            LocalDate periodUntil, long averageDailyBalanceCents,
                            long lowestDailyBalanceCents, int rateBasisPoints, boolean bonusEarned,
                            int termsVersion, long interestCents, Long paidAsDepositId,
                            Instant postedAt) {
        this.savingsAccountId = savingsAccountId;
        this.periodOrdinal = periodOrdinal;
        this.periodFrom = periodFrom;
        this.periodUntil = periodUntil;
        this.averageDailyBalanceCents = averageDailyBalanceCents;
        this.lowestDailyBalanceCents = lowestDailyBalanceCents;
        this.rateBasisPoints = rateBasisPoints;
        this.bonusEarned = bonusEarned;
        this.termsVersion = termsVersion;
        this.interestCents = interestCents;
        this.paidAsDepositId = paidAsDepositId;
        this.postedAt = postedAt;
    }

    /**
     * A month that has just been judged, with everything it was decided from.
     *
     * <p>A factory rather than a public constructor, so that the call site reads as the event it
     * is. There is one caller and there will only ever be one: a month is judged by the sweep, and
     * nothing else in this application has any business writing down what one paid.
     *
     * <p>Twelve figures, which is a smell everywhere except here. A posting <em>is</em> this list —
     * it exists so that nothing has to be re-derived — and the alternative is a half-written row
     * that exists for a moment with some of its answers missing. There is no mutator to finish one
     * with, so they arrive together or not at all.
     */
    static InterestPosting of(long savingsAccountId, int periodOrdinal, LocalDate periodFrom,
                              LocalDate periodUntil, long averageDailyBalanceCents,
                              long lowestDailyBalanceCents, int rateBasisPoints, boolean bonusEarned,
                              int termsVersion, long interestCents, Long paidAsDepositId,
                              Instant postedAt) {
        return new InterestPosting(savingsAccountId, periodOrdinal, periodFrom, periodUntil,
                averageDailyBalanceCents, lowestDailyBalanceCents, rateBasisPoints, bonusEarned,
                termsVersion, interestCents, paidAsDepositId, postedAt);
    }

    Long getId() {
        return id;
    }

    long savingsAccountId() {
        return savingsAccountId;
    }

    int periodOrdinal() {
        return periodOrdinal;
    }

    long averageDailyBalanceCents() {
        return averageDailyBalanceCents;
    }

    long lowestDailyBalanceCents() {
        return lowestDailyBalanceCents;
    }

    /**
     * This month as the rest of the application reads it: the same figures, in the units everything
     * outside this module speaks — euros rather than cents, and a percentage rather than basis
     * points.
     */
    AnInterestPosting asPaid() {
        return new AnInterestPosting(
                periodOrdinal,
                periodFrom,
                periodUntil,
                asEuros(averageDailyBalanceCents),
                asEuros(lowestDailyBalanceCents),
                BasisPoints.asAPercentage(rateBasisPoints),
                bonusEarned,
                termsVersion,
                asEuros(interestCents),
                postedAt);
    }

    /**
     * The cents as the euros everything outside this module speaks, through {@code AmountOfMoney}
     * like the floor on a set of terms: how many places a euro amount has is a decision this
     * application made once, and this module has no business making it again.
     */
    private static BigDecimal asEuros(long cents) {
        return AmountOfMoney.quotedToTheCent(BigDecimal.valueOf(cents, 2));
    }
}
