package io.dataroots.savingstreak.products;

import java.time.Instant;
import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One maturity that has been settled: which account, which of its maturities, the day it fell, what
 * the terms said to do about it, and what the account was on before and after.
 *
 * <p><strong>What makes the sweep idempotent, and by construction rather than by care.</strong> A
 * row per account per maturity, unique over the pair, means a second pass over the same morning
 * cannot settle twice even if the rule underneath were rewritten. The sweep also checks in Java and
 * would settle nothing twice on its own; the check and the guarantee are different things, and two
 * runs at the same moment would both read the same empty set of maturities already settled. The
 * uniqueness is not declared here for the reason {@code LoyaltyBonusPaid} gives at length — the
 * SQLite dialect writes a composite unique clause nowhere, whether it is spelled as a constraint or
 * as an index marked unique — so {@link ProductsOnStartUp} creates the index itself, in a statement
 * SQLite does accept, before the application serves anything.
 *
 * <p><strong>Two of the three endings move the agreement and the third does not, and that is
 * precisely why this row exists.</strong> A rolled-over term has a new maturity date, so a second
 * sweep finds nothing due; an account moved to instant access is on a product with no term at all,
 * so a second sweep finds no term. A term left <em>waiting</em> changes nothing whatsoever about the
 * agreement: the product stays, the version stays, the maturity date stays, and it stays passed.
 * Without a row saying so, every night for the rest of that account's life would find a maturity due
 * and settle it again. The record is what makes "it sits where it is until somebody acts" a thing
 * that happens once rather than a thing that happens nightly.
 *
 * <p><strong>The skip is keyed on the day and the index is keyed on the ordinal, and they agree
 * because only a roll-over makes a new day.</strong> The sweep asks "has the maturity falling on
 * this date been settled for this account", which is the question a derived maturity date can
 * actually answer; the ordinal is then allocated in sequence — one more than the highest this
 * account has — so a rolling term's maturities read 1, 2, 3 in the order they fell. Deriving the
 * ordinal from the calendar instead was rejected: the months between an opening date and a maturity
 * are not a whole number of terms once {@code plusMonths} has clamped a February, and an ordinal
 * that came out one short would collide with a row already written.
 *
 * <p><strong>It is an audit trail as well as a guard, which is why the four product-and-version
 * columns are on it.</strong> What an account was on before a maturity is otherwise gone the moment
 * it rolls: the agreement row names only what it is on now, and the interest postings of the months
 * before it name a version without saying it was the one that matured. A reviewer asking "which
 * terms decided that this account rolled over rather than coming free" reads it here, on one row,
 * a year later.
 *
 * <p>Never rewritten. What was done about a maturity is what happened, and the ending was decided by
 * a version that cannot be edited.
 *
 * <p>Package-private, like the repository: what this module records, and how, is nobody else's
 * business. What a customer reads is what their term says <em>now</em>, which is
 * {@link TheTermOnAnAccount}, and what they will be told when one matures is a notification ticket's.
 */
@Entity
class MaturitySettled {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The account whose term came up, held by identifier like every reference to one here. */
    @Column(nullable = false)
    private long savingsAccountId;

    /**
     * Which of that account's maturities this was — one for the first, two for the second.
     *
     * <p>The ordinal rather than only the day. Half of the unique index is this column, and the
     * ordinal is the half that makes "a clock wound three years forward settles three maturities, in
     * order" a fact anybody can read off the rows rather than a story about the dates.
     */
    @Column(nullable = false)
    private int maturityOrdinal;

    /**
     * The day the term was up, which is the day this settlement is dated by and the day the new
     * agreement starts from.
     *
     * <p>The maturity rather than the moment the sweep noticed, for the reason a paid anniversary
     * and an interest posting both give: the term was up whether or not anything was running at a
     * quarter past three that morning, and dating it by the run would make the same maturity report
     * a different day depending on when the job was actually run. It is also what the roll-over's new
     * term starts from, so a sweep that is a fortnight late still produces the same calendar.
     */
    @Column(nullable = false)
    private LocalDate maturedOn;

    /**
     * What the terms the account was opened under said to do, which is what was done.
     *
     * <p>Written down rather than looked back up, because the version that said it can be read only
     * through the columns beside it and a reader should not have to join three tables to find out
     * why an account is suddenly on free savings. Stored as its name, so that adding an ending never
     * reinterprets a row already written.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MaturityAction action;

    /** The product the account was on when the term matured. */
    @Column(nullable = false)
    private String productBefore;

    /** The version of that product's terms it was living under, which decided the ending above. */
    @Column(nullable = false)
    private int versionBefore;

    /**
     * The product it was on once the maturity had been settled.
     *
     * <p>The same as {@link #productBefore} for a roll-over and for a term left waiting, and free
     * savings for one that moved to instant access. Written even when it did not change, because a
     * column that was null when nothing moved would make "what did this settlement do" two readings
     * instead of one.
     */
    @Column(nullable = false)
    private String productAfter;

    /** The version it was pinned to afterwards — the one on offer on {@link #maturedOn}. */
    @Column(nullable = false)
    private int versionAfter;

    /**
     * The moment the sweep ran, off the application's clock rather than the machine's.
     *
     * <p>Beside {@link #maturedOn} rather than instead of it, and the two are deliberately different
     * questions: when the term was up, and when this application got round to noticing. A trainer
     * who winds a clock three years forward settles three maturities at one moment, and the three
     * rows say so — three days a year apart, one instant.
     */
    @Column(nullable = false)
    private Instant settledAt;

    protected MaturitySettled() {
        // for JPA
    }

    private MaturitySettled(long savingsAccountId, int maturityOrdinal, LocalDate maturedOn,
                            MaturityAction action, String productBefore, int versionBefore,
                            String productAfter, int versionAfter, Instant settledAt) {
        this.savingsAccountId = savingsAccountId;
        this.maturityOrdinal = maturityOrdinal;
        this.maturedOn = maturedOn;
        this.action = action;
        this.productBefore = productBefore;
        this.versionBefore = versionBefore;
        this.productAfter = productAfter;
        this.versionAfter = versionAfter;
        this.settledAt = settledAt;
    }

    /**
     * A maturity that has just been settled, with everything that decided it.
     *
     * <p>Written for every maturity the sweep settles, including the one that changed nothing —
     * unlike a paid anniversary, which leaves no row when it was worth nothing. The difference is
     * the same one an interest posting draws: an anniversary worth nothing today is worth nothing
     * for ever, so there is nothing to remember; a maturity that has been settled is a morning that
     * has closed, and without the row it would be settled again tomorrow.
     */
    static MaturitySettled of(long savingsAccountId, int maturityOrdinal, LocalDate maturedOn,
                              MaturityAction action, String productBefore, int versionBefore,
                              String productAfter, int versionAfter, Instant settledAt) {
        return new MaturitySettled(savingsAccountId, maturityOrdinal, maturedOn, action,
                productBefore, versionBefore, productAfter, versionAfter, settledAt);
    }

    Long getId() {
        return id;
    }
}
