package io.dataroots.savingstreak.products;

import java.math.BigDecimal;
import java.time.LocalDate;

import io.dataroots.savingstreak.deposits.AmountOfMoney;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One published version of a product's terms: the day it took effect, every number the agreement
 * carries, what happens at the end of it, and one line saying what changed.
 *
 * <p><strong>A version is a row, and a row that has been written is never written again.</strong>
 * There is no mutator on this class and nothing outside it can reach a field. Changing what a
 * product offers writes version <em>n+1</em>; it does not edit version <em>n</em>, because an
 * account is living under version <em>n</em> and an agreement somebody is living under cannot be
 * rewritten. That is not a convention this class hopes callers will keep — there is simply nothing
 * here to call.
 *
 * <p><strong>This reverses a decision recorded in the rewards catalogue's spec</strong>, which
 * chose an edited row plus a snapshot copied onto each claim, and explicitly rejected a version
 * table. The reversal is argued rather than quiet. A claim is a single moment and a snapshot
 * answers everything about it. A savings account is years of nightly decisions — interest,
 * maturity, refusals, anniversaries — each of which has to point at the agreement it was decided
 * under, and a snapshot would copy a dozen numbers onto every account and every posting in order to
 * say what one row already says. Neither choice is wrong in general; they are answers to
 * differently shaped questions, and this module's question is the shaped one.
 *
 * <p><strong>It belongs to its product by code rather than by association.</strong> The code is the
 * product's natural key, it never changes, and holding it as a string is what every other pair in
 * this codebase does — a challenge names its campaign, a deposit names its accounts. A
 * {@code @ManyToOne} would buy a cascade nobody wants (there is no delete here) and would make
 * every read of a version drag a product row behind it.
 *
 * <p><strong>Every rate is an {@code int} of basis points and every amount is a {@code long} of
 * cents.</strong> {@link BasisPoints} argues the unit; what matters here is that the integers stop
 * at this class. Everything that leaves is a {@link BigDecimal} — a percentage a page can print, or
 * a euro amount quoted through the money vocabulary the rest of the application already speaks.
 *
 * <p><strong>Zero is the absence of the rule, in every one of the seven figures, and that reading
 * is uniform on purpose.</strong> No rate pays nothing; no bonus is nothing to earn or lose; no
 * notice days is money that may leave today; no term months is not a term account; no floor is no
 * floor to keep; no penalty days is nothing to pay for leaving. A boxed {@code Integer} per column
 * would have let null mean the same thing and would have made seven columns that every reader has
 * to null-check before arithmetic — and a null rate and a zero rate would be two spellings of one
 * fact.
 *
 * <p><strong>One figure and one only can never be zero, and it is not both of the loyalty
 * ones.</strong> An earlier reading of this class said neither of them ever was, and the
 * administration door that publishes a version disagrees with it:
 * {@link BasisPoints#whyItIsNotAMultipleThatCanBeHeld} refuses a points multiplier of nought
 * because nought <em>times</em> is not an offer, and
 * {@link BasisPoints#whyItIsNotAPercentageThatCanBeHeld} accepts an anniversary rate of nought
 * because a product that pays nothing for staying is a real and perfectly sayable agreement —
 * exactly as a product that pays no interest is. So the multiplier reads {@code 1.0000} where the
 * rule changes nothing and can be nothing else; the anniversary rate reads zero as the absence of
 * the rule, like the other five. The seed gives every product at least
 * {@link BasisPoints#ONE_WHOLE_MULTIPLE} and the tenth {@code LoyaltyRate} has always paid, which
 * is what makes "an account on free savings earns what it always earned" a fact about the rows
 * rather than a hope about the arithmetic; it is not a rule about what a row may hold.
 *
 * <p>Package-private, like the repository that reads it. {@link ASetOfTerms} is what leaves this
 * module.
 */
@Entity
class ProductTerms {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Which product's agreement this is, by the code that never changes. */
    @Column(nullable = false)
    private String productCode;

    /**
     * Which version of it, counting from one.
     *
     * <p>Per product rather than across the catalogue, so that "free savings, version 2" is a
     * sentence a customer can read off their own account. Unique with the code above, which is a
     * rule the database keeps rather than one this module merely intends —
     * {@link ProductTermsRepository#makeAVersionUniquePerProduct} is where that guarantee comes
     * from and why it is not declared here.
     */
    @Column(nullable = false)
    private int version;

    /**
     * The day it took effect.
     *
     * <p>A {@link LocalDate} rather than an instant, for the reason every other window in this
     * codebase is one: a rate change is a thing announced, and an instant would start it an evening
     * early for anybody reading west of here. It is also what an account opened on a particular day
     * is matched against, so the granularity has to be the day rather than the moment.
     */
    @Column(nullable = false)
    private LocalDate effectiveFrom;

    /** The headline rate, in basis points a year — 60 is 0.60%. */
    @Column(nullable = false)
    private int annualRateBasisPoints;

    /**
     * On top of the headline rate, in basis points a year, and only for a period in which the
     * product's condition was kept.
     *
     * <p>Zero on three of the four products, because only a minimum-balance account has a condition
     * to keep. It is a column on every version all the same rather than a column on the one kind
     * that uses it: a terms row is a flat list of numbers by design, and a nullable column that is
     * meaningful for one {@link ProductKind} is the beginning of a row that means different things
     * depending on another column.
     */
    @Column(nullable = false)
    private int bonusRateBasisPoints;

    /** Days of warning before money may leave, and zero when none is needed. */
    @Column(nullable = false)
    private int noticeDays;

    /** How long the money is locked, in months, and zero when it is not a term account. */
    @Column(nullable = false)
    private int termMonths;

    /** The floor, in cents, and zero when there is no floor to keep. */
    @Column(nullable = false)
    private long minimumBalanceCents;

    /**
     * Days of interest given up for breaking a term early, and zero when there is nothing to pay
     * for leaving.
     *
     * <p>Days rather than an amount, because the price has to scale with the balance somebody is
     * taking out: ninety days of interest on five thousand euros is a real deterrent and ninety
     * days on fifty is a rounding error, and a flat fee would have been either punitive or
     * meaningless depending on who broke the term.
     */
    @Column(nullable = false)
    private int earlyExitPenaltyDays;

    /**
     * What a euro saved into this product is worth in points, in basis points of a whole multiple —
     * 10 000 is unchanged, 12 500 is a quarter more.
     *
     * <p>A multiplier rather than an addition, because it has to compose with the streak multiplier
     * this application already pays: a run of weeks should be worth more in a product that pays
     * more, and an addition would make the product's benefit worth the same whether somebody had
     * saved for one week or twenty.
     */
    @Column(nullable = false)
    private int pointsMultiplierBasisPoints;

    /**
     * What an anniversary pays on money still sitting in this product, in basis points — 1 000 is a
     * tenth.
     *
     * <p>Seeded at exactly the tenth {@code LoyaltyRate} has always paid, on the products that have
     * no better offer to make, so that a customer on free savings sees the figure they saw
     * yesterday. It is the rate becoming an argument rather than a constant, which is the one part
     * of this feature that reaches into a module that was finished.
     */
    @Column(nullable = false)
    private int anniversaryRateBasisPoints;

    /**
     * What happens on the day the term is up, and {@link MaturityAction#HOLD} on every product that
     * has no term to reach one.
     *
     * <p>Written as its name, which is a {@code check} constraint in the generated schema and the
     * right constraint here: three endings is a set that belongs to the code, because each of them
     * is different behaviour rather than a different number.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MaturityAction maturityAction;

    /**
     * One line saying what changed and why, for the customer comparing this version with the one
     * they are on.
     *
     * <p>Written down rather than computed from the previous row, and the two are not the same
     * thing. A difference between two versions is a list of figures that moved, and this module
     * will produce that list mechanically; what it cannot produce is the reason. "Rate cut in line
     * with the market" is an explanation, and a customer deciding whether to take newer terms is
     * reading an explanation rather than a diff.
     *
     * <p>Long, for the reason the product's own words are long: the sentence that matters here is
     * the one that does not fit in six words.
     */
    @Column(length = 1000)
    private String whatChanged;

    protected ProductTerms() {
        // for JPA
    }

    private ProductTerms(String productCode, int version, LocalDate effectiveFrom,
                         int annualRateBasisPoints, int bonusRateBasisPoints, int noticeDays,
                         int termMonths, long minimumBalanceCents, int earlyExitPenaltyDays,
                         int pointsMultiplierBasisPoints, int anniversaryRateBasisPoints,
                         MaturityAction maturityAction, String whatChanged) {
        this.productCode = productCode;
        this.version = version;
        this.effectiveFrom = effectiveFrom;
        this.annualRateBasisPoints = annualRateBasisPoints;
        this.bonusRateBasisPoints = bonusRateBasisPoints;
        this.noticeDays = noticeDays;
        this.termMonths = termMonths;
        this.minimumBalanceCents = minimumBalanceCents;
        this.earlyExitPenaltyDays = earlyExitPenaltyDays;
        this.pointsMultiplierBasisPoints = pointsMultiplierBasisPoints;
        this.anniversaryRateBasisPoints = anniversaryRateBasisPoints;
        this.maturityAction = maturityAction;
        this.whatChanged = whatChanged;
    }

    /**
     * A version as somebody publishing it describes it: every figure, the day it starts, and the
     * line saying what changed.
     *
     * <p>Thirteen parameters, which is a smell everywhere except here. A set of terms <em>is</em>
     * this list of numbers — that is the design, and the alternative to naming them all at once is
     * a half-built agreement that exists for a moment with some of its figures unset. There is no
     * mutator to finish one with, so they arrive together or not at all, and the seed's calls are
     * written one figure per line with the table in the spec beside them.
     *
     * <p>The only factory there is, and it takes no state: a version is published, always, because
     * an unpublished one is a draft and this module has no drafts. The day it takes effect is the
     * whole of what "not yet" means here, and a version dated ahead of today is one
     * {@link TheTermsOnOfferToday} simply does not offer yet.
     */
    static ProductTerms published(String productCode, int version, LocalDate effectiveFrom,
                                  int annualRateBasisPoints, int bonusRateBasisPoints,
                                  int noticeDays, int termMonths, long minimumBalanceCents,
                                  int earlyExitPenaltyDays, int pointsMultiplierBasisPoints,
                                  int anniversaryRateBasisPoints, MaturityAction maturityAction,
                                  String whatChanged) {
        return new ProductTerms(productCode, version, effectiveFrom, annualRateBasisPoints,
                bonusRateBasisPoints, noticeDays, termMonths, minimumBalanceCents,
                earlyExitPenaltyDays, pointsMultiplierBasisPoints, anniversaryRateBasisPoints,
                maturityAction, whatChanged);
    }

    String productCode() {
        return productCode;
    }

    /**
     * The headline rate, in the unit the column holds it in, for the one caller that multiplies by
     * it rather than printing it.
     *
     * <p>Basis points rather than the percentage {@link #asPublished} hands out, and that is the
     * whole reason it is here. A month's interest is the average balance times the rate divided by
     * twelve, worked out in whole cents; doing that from a percentage means dividing by a hundred
     * first and choosing what to do with what falls off the end, which is a rounding decision made
     * in the wrong place. An integer of basis points multiplies exactly, and the one division that
     * remains is floored where the spec says to floor it.
     *
     * <p>Package-private, like every other reading of a column here: no basis point ever leaves
     * this module.
     */
    int annualRateBasisPoints() {
        return annualRateBasisPoints;
    }

    /**
     * What is paid on top of the headline rate for a period in which this product's condition was
     * kept, in the same unit as the headline rate and for the same one caller.
     *
     * <p>Beside {@link #annualRateBasisPoints()} rather than folded into it, and the two are added
     * where a period is priced rather than here. A method answering "the rate this month is paid
     * at" would have to be handed the lowest balance the month held in order to answer, which is a
     * question about a walk over a ledger and not a question about a row of the catalogue — and it
     * would put the judgement in the class that stores the figures instead of in
     * {@link TheRateAPeriodIsPaidAt}, which is where this slice argues it belongs.
     *
     * <p>Nought is no bonus on offer, on three of the four products, and that reading is the same
     * one every other figure on this row makes.
     */
    int bonusRateBasisPoints() {
        return bonusRateBasisPoints;
    }

    /**
     * The floor that has to be kept for the bonus, in cents, for the one caller that compares it
     * with a balance rather than printing it.
     *
     * <p>Cents rather than the euro amount {@link #asPublished} hands out, because what it is
     * compared against is the lowest daily balance — which {@link TheDailyBalancesOfAnAccount}
     * works out in cents, for the reason it gives about fractions. Comparing a {@link BigDecimal}
     * of euros with a walk's {@code long} of cents means a conversion at the comparison, and a
     * conversion at a comparison is where an off-by-a-hundred goes unnoticed: five euros would keep
     * a five hundred euro floor and nobody would see it in a test that used round numbers.
     *
     * <p>Nought is no floor to keep, which {@link TheRateAPeriodIsPaidAt} reads as a condition
     * nothing can fail rather than as one nothing can meet.
     */
    long minimumBalanceCents() {
        return minimumBalanceCents;
    }

    int version() {
        return version;
    }

    LocalDate effectiveFrom() {
        return effectiveFrom;
    }

    /**
     * How long this agreement locks money away, in months, and nought when it locks none.
     *
     * <p>Off the row directly, for the two callers that ask the question rather than print the
     * answer: the nightly maturity sweep, which works out when the term is up, and the rule that
     * decides whether a matured term left waiting is still earning its own rate. Both of them hold a
     * {@link ProductTerms} already and neither wants the twelve other figures {@link #asPublished}
     * would assemble in order to hand back one integer — the same argument {@link #pointsMultiplier}
     * makes about the same shortcut, and the same unit, because months are months either way.
     */
    int termMonths() {
        return termMonths;
    }

    /**
     * What this agreement says happens on the day its term is up.
     *
     * <p>Off the row directly, and for exactly one caller: the nightly sweep that settles a maturity
     * by the action in the terms the account was <em>opened</em> under. Reading it through
     * {@link #asPublished} would work and would drag a dozen converted figures behind a question
     * that is one word wide; reading it off {@link TheTermsOnOfferToday} would be the mistake this
     * whole module exists to prevent, because what happens at the end is part of what was agreed at
     * the beginning and the bank may have published a different ending since.
     */
    MaturityAction maturityAction() {
        return maturityAction;
    }

    /**
     * What a euro saved into this product is worth in points, as a plain multiple of one —
     * {@code 1.0000} changes nothing and {@code 1.2500} is a quarter more.
     *
     * <p>The same figure {@link #asPublished} sends out on {@link ASetOfTerms#pointsMultiplier},
     * read off the row directly for the one caller that has to multiply by it rather than print it.
     * A pricing that went through the published record would drag twelve other figures — a floor, a
     * penalty, a maturity action — past a question that is one number wide, and would read the
     * agreement out of whatever {@link TheTermsOnOfferToday} is selling unless the caller was
     * careful, which is precisely the mistake a deposit must not make: it is priced by the version
     * its account is living under, not by the version on the shelf.
     */
    BigDecimal pointsMultiplier() {
        return BasisPoints.asAMultiple(pointsMultiplierBasisPoints);
    }

    /**
     * What an anniversary pays here <strong>per whole euro</strong>: a fraction of a point, so
     * {@code 0.1000} is the tenth this application has always paid and {@code 0.1200} is twelve
     * percent.
     *
     * <p><strong>A fraction, and emphatically not the percentage beside it.</strong> The column
     * holds 1 000 basis points and there are three honest readings of that integer — 1 000 basis
     * points, 10.00 percent, and the fraction 0.1000 — which are the same rate and three different
     * numbers. {@code LoyaltyRate} multiplies whole euros by a fraction, so handing it the basis
     * points would pay ten thousand times too much and handing it the percentage a hundred times
     * too much, and neither mistake would throw: a EUR 500 deposit would simply pay 500 000 points
     * or 5 000 instead of 50, and the first anybody would know of it is a customer's balance. This
     * method exists so that the conversion happens once, here, in the module that owns the unit,
     * rather than at the far end of an interface where the number arrives without its unit
     * attached.
     *
     * <p>{@link BasisPoints#asAMultiple} rather than a division, because a fraction of a point and
     * a multiple of one are the same arithmetic — both are basis points with the decimal point
     * moved four places — and the exactness argued there is the exactness wanted here. A division
     * by ten thousand would be a rounding mode somebody had to choose.
     *
     * <p>It may be nought, unlike the multiplier above, and nought is a real agreement: a product
     * that pays nothing for money staying put. {@code LoyaltyRate} is what makes that honest — no
     * anniversary is ever worth a point at that rate, whatever is in the deposit, and there is no
     * threshold to quote because there is no amount that would clear one.
     */
    BigDecimal anniversaryRatePerWholeEuro() {
        return BasisPoints.asAMultiple(anniversaryRateBasisPoints);
    }

    /**
     * This agreement as the rest of the application reads it: the same numbers, in the units
     * everything outside this module speaks.
     *
     * <p>The floor goes out through {@code AmountOfMoney} rather than as a raw division, because
     * how many places a euro amount has is a decision this application made once and this module
     * has no business making again.
     */
    ASetOfTerms asPublished() {
        return new ASetOfTerms(
                productCode,
                version,
                effectiveFrom,
                BasisPoints.asAPercentage(annualRateBasisPoints),
                BasisPoints.asAPercentage(bonusRateBasisPoints),
                noticeDays,
                termMonths,
                AmountOfMoney.quotedToTheCent(BigDecimal.valueOf(minimumBalanceCents, 2)),
                earlyExitPenaltyDays,
                BasisPoints.asAMultiple(pointsMultiplierBasisPoints),
                BasisPoints.asAPercentage(anniversaryRateBasisPoints),
                maturityAction,
                whatChanged);
    }
}
