package io.dataroots.savingstreak.products;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * One savings product the bank sells: what it is called, what shape of agreement it is, what it
 * says to a customer, where it sits in the list, and whether anybody may still open an account on
 * it.
 *
 * <p><strong>None of the numbers are here.</strong> The rate, the bonus, the notice period, the
 * term, the floor, the early-exit price and the two loyalty benefits live on {@link ProductTerms},
 * one row per version, and that split is the whole design of this module rather than a tidying of
 * it. A product is the thing a customer chooses and keeps choosing; a set of terms is what was
 * agreed on a particular day. Putting a rate on this row would mean a rate cut edited the thing
 * every account points at, and the money somebody put away in January would quietly start living
 * under March's agreement — which is the failure this whole feature exists to prevent.
 *
 * <p><strong>The code is the natural key and it never changes.</strong> Unique, because it is what
 * an account will name, what a version row belongs to, and what {@link ProductsOnStartUp} matches
 * on when it decides whether this row is already there; two rows sharing one would be two answers
 * to the same request. A single-column unique constraint is one SQLite accepts from a generated
 * schema, which is why it is declared here rather than made into an index at start-up the way this
 * module's composite guarantee has to be — {@link ProductTermsRepository} says the rest of that.
 *
 * <p><strong>Nothing deletes a product, and there is no way to ask for it.</strong> An account
 * points at one, every interest posting will point at one through the version it was paid under,
 * and a row that went away would orphan all of them. The same argument a goal is abandoned rather
 * than removed by, and the same one {@code RewardOffer} makes about an offer a voucher names.
 * Retiring a product is {@link #openToNewAccounts} going false, which stops the next account and
 * disturbs none of the ones already on it.
 *
 * <p><strong>The sort order is a decision somebody made, not an accident of insertion.</strong>
 * The four seeded products are written cheapest-and-freest first, so the catalogue reads as a
 * ladder from the account that asks nothing of you up to the one that asks for a year — which is
 * the order a person actually weighs these in. Ordering by rate would give the same answer today
 * and a different one the first time two products pay the same; ordering by identifier would make
 * the list depend on which row the seed happened to write first. This column is what the
 * {@code sort_order} of a catalogue means everywhere else in this codebase: the order somebody
 * chose.
 *
 * <p>Package-private, like the repository that reads it. {@link AProductOnOffer} is what leaves
 * this module.
 */
@Entity
class SavingsProduct {

    /** SQLite has no sequences, so identity values are generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * What an account names this product by, what a version row belongs to, and what the seed
     * matches on when it decides whether this row is already there.
     */
    @Column(nullable = false, unique = true)
    private String code;

    /** What the card is headed with — "Free savings", "32-day notice". */
    @Column(nullable = false)
    private String name;

    /**
     * Which of the four shapes this is, and the one thing about a product that is not a figure.
     *
     * <p>An enum written as its name, which is a {@code check} constraint in the generated schema
     * and the right constraint here: the set genuinely belongs to the code, because each value is a
     * different question asked of a withdrawal. {@link ProductKind} argues that at length.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ProductKind kind;

    /**
     * What the card says underneath: what the customer is giving up and what they are getting for
     * it, in one sentence.
     *
     * <p>Long, like the reward cards' and the challenge cards', because this is the only place a
     * product explains itself and the sentence that matters — the rate weighed against the
     * condition — does not fit in six words.
     */
    @Column(length = 1000)
    private String words;

    /** Where it sits in the list somebody chose, lowest first. */
    @Column(nullable = false)
    private int sortOrder;

    /**
     * Whether a new savings account may be opened on it.
     *
     * <p>A boolean rather than a state with a name, because there are exactly two answers and
     * neither of them is a draft: a product is seeded already on sale, and the only thing an
     * administrator does to one is stop offering it. Closing it touches nothing that is already on
     * it — the accounts carry on, the versions still read, and the product still appears in the
     * catalogue marked as closed, because a customer who holds one has every right to see what
     * they are holding.
     */
    @Column(nullable = false)
    private boolean openToNewAccounts;

    protected SavingsProduct() {
        // for JPA
    }

    private SavingsProduct(String code, String name, ProductKind kind, String words, int sortOrder,
                           boolean openToNewAccounts) {
        this.code = code;
        this.name = name;
        this.kind = kind;
        this.words = words;
        this.sortOrder = sortOrder;
        this.openToNewAccounts = openToNewAccounts;
    }

    /**
     * A product as the seed describes it: on sale, in the place somebody put it.
     *
     * <p>The one constructor there is, and deliberately so. Every row this application writes today
     * is one of the four it sells, and a factory that can only produce a product that is open is a
     * factory that cannot accidentally seed a closed one. The slice that lets an administrator
     * write a product is the slice that adds the way to say anything else.
     */
    static SavingsProduct onOffer(String code, String name, ProductKind kind, String words,
                                  int sortOrder) {
        return new SavingsProduct(code, name, kind, words, sortOrder, true);
    }

    String code() {
        return code;
    }

    String name() {
        return name;
    }

    ProductKind kind() {
        return kind;
    }

    /** What the card says under the name, and null only for a row somebody wrote without one. */
    String words() {
        return words;
    }

    int sortOrder() {
        return sortOrder;
    }

    boolean openToNewAccounts() {
        return openToNewAccounts;
    }

    /**
     * Stops anybody opening a new account on it, and does nothing else at all.
     *
     * <p><strong>The one mutator in this module, and it is worth saying why it is allowed to exist
     * when {@link ProductTerms} has none.</strong> A published version is an agreement somebody's
     * money is living under, so changing one would rewrite what was agreed; this flag is not part
     * of any agreement. It says whether the bank is still selling the thing, which is a fact about
     * today rather than about anybody's account, and an account already on the product cannot tell
     * the difference: its version row is untouched, its rate is untouched, and nothing in this
     * module reads this flag when deciding what an account is owed.
     *
     * <p><strong>Retiring rather than deleting</strong>, which is the whole reason the flag is here
     * — the argument is in this class's own javadoc and in {@link SavingsProductRepository}'s. A
     * row that went away would orphan every account and every interest posting pointing at it.
     *
     * @return whether this actually changed anything, so that the caller's log can tell a decision
     *         from a repeated press. Closing a product that is already closed is not refused: there
     *         is no state to be in the wrong one of, the administrator asked for it to be shut and
     *         it is shut, and a refusal would be this module arguing with somebody who got what
     *         they wanted.
     */
    boolean closeToNewAccounts() {
        if (!openToNewAccounts) {
            return false;
        }
        openToNewAccounts = false;
        return true;
    }

    /**
     * Puts it back on sale, and does nothing else — in particular, it does not republish anything.
     * The product comes back offering whatever version is effective on the day somebody next opens
     * an account on it, which may well not be the version it was offering when it closed.
     *
     * @return whether this actually changed anything, read the same way as {@link
     *         #closeToNewAccounts}
     */
    boolean reopenToNewAccounts() {
        if (openToNewAccounts) {
            return false;
        }
        openToNewAccounts = true;
        return true;
    }

    /**
     * This product and the set of terms it is selling today, as the rest of the application reads
     * it.
     *
     * <p>The terms are handed in rather than looked up, because which version is on offer today is
     * a question about a list and a date — {@link TheTermsOnOfferToday} answers it — and an entity
     * that fetched its own would be a row holding a repository.
     */
    AProductOnOffer with(ASetOfTerms currentTerms) {
        return new AProductOnOffer(code, name, kind, words, sortOrder, openToNewAccounts,
                currentTerms);
    }
}
